SELECT
	'BWS' AS [OriginCompany]
	,'Options' AS [OriginTable]
	,ROW_NUMBER() OVER(
		ORDER BY [BWS_O].[ID#]
	) AS [Options_OptionID]
	,NULL AS [Orders_Quote]
	,[BWS_O].[ID#] AS [O_ID]
	,[BWS_O].[Model No] AS [O_ModelNo]
	,[BWS_O].[Option No] AS [O_OptionNo]
	,[BWS_O].[Start Date] AS [O_DateStart]
	,[BWS_O].[End Date] AS [O_DateEnd]
	,[BWS_O].[Price] AS [O_Price]
	,[BWS_O].[Sections] AS [O_Sections]
	,[BWS_O].[Description] AS [O_Description]
	,[BWS_O].[Weight] AS [O_Weight]
	,[BWS_O].[Width] AS [O_Width]
	,[BWS_O].[Deck Length] AS [O_DeckLength]
	,[BWS_O].[Spread] AS [O_Spread]
	,[BWS_O].[SortSe] AS [O_SortSe]
	,[BWS_O].[Draw/Part#] AS [O_DrawPart]
	,[BWS_O].[Std Hours] AS [O_StdHours]
	,[BWS_O].[Obsolete] AS [O_Obsolete]
	,[BWS_O].[Selection] AS [O_Selection]
	,[BWS_O].[New Option Wording] AS [O_NewOptionWording]
	,[BWS_O].[OptionInfo] AS [O_OptionInfo]
	,[BWS_O].[OptionPromptFlag] AS [O_OptionPromptFlag]
	,[BWS_O].[OptionPrompt] AS [O_OptionPrompt]
	,[BWS_O].[OptionConfigInfo] AS [O_OptionConfigInfo]
	,[BWS_O].[Option_timestamp] AS [O_Option_timestamp]
	,[BWS_O].[US Price] AS [O_USPrice]
	,[BWS_O].[Sections_French] AS [O_Sections_French]
	,[BWS_O].[Description_French] AS [O_Description_French]
	,[BWS_O].[OptionInfo_French] AS [O_OptionInfo_French]
	,[BWS_O].[OptionPrompt_French] AS [O_OptionPrompt_French]
	,NULL AS [O_Tarp]
	,0 AS [O_CompanyID]
FROM
	[BWSdb].[dbo].[Options] AS [BWS_O] WITH (NOLOCK)

UNION

SELECT
	'STG' AS [OriginCompany]
	,'OptionsV2' AS [OriginTable]
	,ROW_NUMBER() OVER(
		ORDER BY [STG_O2].[ID#]
	) AS [Options_OptionID]
	,NULL AS [Orders_Quote]
	,[STG_O2].[ID#] AS [O_ID]
	,[STG_O2].[Model No] AS [O_ModelNo]
	,[STG_O2].[Option No] AS [O_OptionNo]
	,[STG_O2].[Start Date] AS [O_DateStart]
	,[STG_O2].[End Date] AS [O_DateEnd]
	,[STG_O2].[Price] AS [O_Price]
	,[STG_O2].[Sections] AS [O_Sections]
	,[STG_O2].[Description] AS [O_Description]
	,[STG_O2].[Weight] AS [O_Weight]
	,[STG_O2].[Width] AS [O_Width]
	,[STG_O2].[Deck Length] AS [O_DeckLength]
	,[STG_O2].[Spread] AS [O_Spread]
	,[STG_O2].[SortSe] AS [O_SortSe]
	,[STG_O2].[Draw/Part#] AS [O_DrawPart]
	,[STG_O2].[Std Hours] AS [O_StdHours]
	,[STG_O2].[Obsolete] AS [O_Obsolete]
	,[STG_O2].[Selection] AS [O_Selection]
	,[STG_O2].[New Option Wording] AS [O_NewOptionWording]
	,[STG_O2].[OptionInfo] AS [O_OptionInfo]
	,[STG_O2].[OptionPromptFlag] AS [O_OptionPromptFlag]
	,[STG_O2].[OptionPrompt] AS [O_OptionPrompt]
	,[STG_O2].[OptionConfigInfo] AS [O_OptionConfigInfo]
	,[STG_O2].[Option_timestamp] AS [O_Option_timestamp]
	,[STG_O2].[US Price] AS [O_USPrice]
	,NULL AS [O_Sections_French]
	,NULL AS [O_Description_French]
	,NULL AS [O_OptionInfo_French]
	,NULL AS [O_OptionPrompt_French]
	,[STG_O2].[Tarp] AS [STG_O2_Tarp]
	,[STG_O2].[CompanyID] AS [STG_O2_CompanyID]
FROM
	[BWSdb].[dbo].[OptionsV2] AS [STG_O2] WITH (NOLOCK)

UNION

SELECT
	'STG' AS [OriginCompany]
	,'Order Options' AS [OriginTable]
	,ROW_NUMBER() OVER(
		ORDER BY [BWS_OO].[ID]
	) AS [Options_OptionID]
	,[BWS_OO].[Quote#] AS [Orders_Quote]
	,[BWS_OO].[ID] AS [OO_ID]
	,[BWS_OO].[Quote Date] AS [OO_DateQuote]
	,[BWS_OO].[Order Date] AS [OO_DateOrder]
	,[BWS_OO].[WO#] AS [OO_WO]
	,[BWS_OO].[Option No] AS [OO_OptionNo]
	,[BWS_OO].[Price] AS [OO_Price]
	,[BWS_OO].[Qty] AS [OO_Qty]
	,[BWS_OO].[Sections] AS [OO_Sections]
	,[BWS_OO].[Description] AS [OO_Description]
	,[BWS_OO].[Comments] AS [OO_Comments]
	,[BWS_OO].[Weight] AS [OO_Weight]
	,[BWS_OO].[Cost] AS [OO_Cost]
	,[BWS_OO].[Material Cost] AS [OO_MaterialCost]
	,[BWS_OO].[Machine Shop] AS [OO_MachineShop]
	,[BWS_OO].[Steel Kit] AS [OO_SteelKit]
	,[BWS_OO].[Axles] AS [OO_Axles]
	,[BWS_OO].[Stakes/Bunks] AS [OO_StakesBunks]
	,[BWS_OO].[Beam] AS [OO_Beam]
	,[BWS_OO].[GNK] AS [OO_GNK]
	,[BWS_OO].[Parts] AS [OO_Parts]
	,[BWS_OO].[Line] AS [OO_Line]
	,[BWS_OO].[Step 1] AS [OO_Step1]
	,[BWS_OO].[Step 2] AS [OO_Step2]
	,[BWS_OO].[Blast] AS [OO_Blast]
	,[BWS_OO].[Paint] AS [OO_Paint]
	,[BWS_OO].[Finish] AS [OO_Finish]
	,[BWS_OO].[Finish - GNK] AS [OO_Finish-GNK]
	,[BWS_OO].[Final Assembly] AS [OO_FinalAssembly]
	,[BWS_OO].[Tire Assembly] AS [OO_TireAssembly]
	,[BWS_OO].[Shipping] AS [OO_Shipping]
	,[BWS_OO].[Start Date] AS [OO_DateStart]
	,[BWS_OO].[End Date] AS [OO_DateEnd]
	,[BWS_OO].[SortSe] AS [OO_SortSe]
	,[BWS_OO].[Width] AS [OO_Width]
	,[BWS_OO].[Spread] AS [OO_Spread]
	,[BWS_OO].[Draw/Part#] AS [OO_DrawPart]
	,[BWS_OO].[OptionInfo] AS [OO_OptionInfo]
	,[BWS_OO].[OptionPromptFlag] AS [OO_OptionPromptFlag]
	,[BWS_OO].[OptionPrompt] AS [OO_OptionPrompt]
	,[BWS_OO].[OptionConfigInfo] AS [OO_OptionConfigInfo]
	,[BWS_OO].[ordopt_timestamp] AS [OO_ordopt_timestamp]
	,[BWS_OO].[Are WO Specs Different?] AS [OO_AreWOSpecsDifferent]
	,[BWS_OO].[Comments V2] AS [OO_CommentsV2]
	,[BWS_OO].[Galvanized] AS [OO_Galvanized]
	,[BWS_OO].[Sections_French] AS [OO_Sections_French]
	,[BWS_OO].[Description_French] AS [OO_Description_French]
	,[BWS_OO].[OptionInfo_French] AS [OO_OptionInfo_French]
	,[BWS_OO].[OptionPrompt_French] AS [OO_OptionPrompt_French]
FROM
	[Order Options] AS [BWS_OO] WITH (NOLOCK)
;

;