USE SysproCompanyA
GO

SELECT TOP 200 *  FROM [ClkTransaction]
SELECT * FROM [ClkShiftDetail]
SELECT TOP 200 *  FROM [ClkShiftMaster]
SELECT TOP 200 *  FROM [ClkShiftRule]


SELECT TOP 200 *  FROM [ClkAllowedQuestion]
SELECT TOP 200 *  FROM [ClkClients]
SELECT TOP 200 *  FROM [ClkClientSessions]
SELECT TOP 200 *  FROM [ClkComputerwiseTerminal]
SELECT TOP 200 *  FROM [ClkConfiguration]
SELECT TOP 200 *  FROM [ClkConfiguredQuestion]
SELECT TOP 200 *  FROM [ClkEmployee]
SELECT TOP 200 *  FROM [ClkenetLog]
SELECT TOP 200 *  FROM [ClkGroup]
SELECT TOP 200 *  FROM [ClkLabourTransactionPost]
SELECT TOP 200 *  FROM [ClkLog]
SELECT TOP 200 *  FROM [ClkLogClientServerEvent]
SELECT TOP 200 *  FROM [ClkLogClientServerEventData]
SELECT TOP 200 *  FROM [ClkLogExceptions]
SELECT TOP 200 *  FROM [ClkLogTrace]
SELECT TOP 200 *  FROM [ClkMaterialTransactionPost]
SELECT TOP 200 *  FROM [ClkNextSharedID]
SELECT TOP 200 *  FROM [ClkNPCode]
SELECT TOP 200 *  FROM [ClkOperationType]
SELECT TOP 200 *  FROM [ClkQuestion]
SELECT TOP 200 *  FROM [ClkRequestStatusCategories]
SELECT TOP 200 *  FROM [ClkRequestTypeItems]
SELECT TOP 200 *  FROM [ClkShiftDetail]
SELECT TOP 200 *  FROM [ClkShiftMaster]
SELECT TOP 200 *  FROM [ClkShiftRule]
SELECT TOP 200 *  FROM [ClkShopFloorWorkcenter]
SELECT TOP 200 *  FROM [ClkSYSPROBOParameters]
SELECT TOP 200 *  FROM [ClkTransaction]
SELECT TOP 200 *  FROM [ClkTransaction63]
SELECT TOP 200 *  FROM [ClkTransactionEdits]
SELECT TOP 200 *  FROM [ClkTransactionEdits63]
SELECT TOP 200 *  FROM [ClkTransactionEditTypes]
SELECT TOP 200 *  FROM [ClkTransactionRequest]
SELECT TOP 200 *  FROM [ClkTransactionRequestHistory]
SELECT TOP 200 *  FROM [ClkTransactionRequestItems]
SELECT TOP 200 *  FROM [ClkTransactionReversals]
SELECT TOP 200 *  FROM [ClkTransactionSession]
SELECT TOP 200 *  FROM [ClkTransactionType]
SELECT TOP 200 *  FROM [ClkUser]
SELECT TOP 200 *  FROM [ClkUserItem]
SELECT TOP 200 *  FROM [ClkUserPermission]
SELECT TOP 200 *  FROM [ClkValidationErrors]
SELECT TOP 200 *  FROM [ClkWorkCentreConfiguredQuestion]


SELECT [ShiftID], [ShiftName] FROM [ClkShiftMaster]