DECLARE @dr1 NVARCHAR(MAX) = '1'
DECLARE @dr2 NVARCHAR(MAX) = '1;2'
DECLARE @dr3 NVARCHAR(MAX) = '1;2;3'

SELECT CASE WHEN @dr2 LIKE '%;2;%' THEN 1 ELSE 0 END
SELECT CASE WHEN @dr2 LIKE '%;2%' THEN 1 ELSE 0 END
SELECT CASE WHEN @dr2 LIKE '%2;%' THEN 1 ELSE 0 END

SELECT CASE WHEN ';2;' LIKE '%' + @dr1 + '%' THEN 1 ELSE 0 END
SELECT CASE WHEN '2' LIKE '%' + @dr1 + '%' THEN 1 ELSE 0 END

SELECT CASE WHEN ';2;' LIKE '%' + @dr2 + '%' THEN 1 ELSE 0 END
SELECT CASE WHEN '2' LIKE '%' + @dr2 + '%' THEN 1 ELSE 0 END

SELECT CASE WHEN ';2;' LIKE '%' + @dr3 + '%' THEN 1 ELSE 0 END
SELECT CASE WHEN '2' LIKE '%' + @dr3 + '%' THEN 1 ELSE 0 END