USE BWSdb
GO

SELECT * FROM [OrdersV2] WHERE [WO#] = 10000392 ORDER BY [WO#]
SELECT * FROM [Orders] WHERE [WO#] = 10000392 ORDER BY [WO#]
SELECT * FROM [OrdersV2] WHERE RIGHT(CAST([WO#] AS NVARCHAR(MAX)), 3) = '392' ORDER BY [WO#]
SELECT * FROM [Orders] WHERE RIGHT(CAST([WO#] AS NVARCHAR(MAX)), 3) = '392' ORDER BY [WO#]
SELECT * FROM [OrdersV2] WHERE RIGHT(CAST([WO#] AS NVARCHAR(MAX)), 3) = '392' ORDER BY [WO#]