USE SysproCompanyA
GO

DECLARE @SD AS DATETIME;
DECLARE @ED AS DATETIME;
SET @SD = '1900-08-12';
SET @ED = '2021-08-19';
/*
DECLARE @SDI AS INT;
DECLARE @EDI AS INT;
SET @SDI = DATEDIFF(SECOND,{d '1970-01-01'}, @SD);
SET @EDI = DATEDIFF(SECOND,{d '1970-01-01'}, @ED);*/

DECLARE @SDT AS TIMESTAMP;
SET @SDT = CAST(@SD AS TIMESTAMP)

SELECT @SD AS [SD], @ED AS [ED], CAST(@SD AS TIMESTAMP) AS [SDT], CAST(@ED AS TIMESTAMP) AS [EDT];

SELECT TOP 5
	[TimeStamp],
	*
FROM
	[WipJobAllMat]
/*WHERE
	[TimeStamp] BETWEEN CAST(@SD AS TIMESTAMP) AND CAST(@ED AS TIMESTAMP)*/