
DECLARE @SD AS DATETIME, @ED AS DATETIME, @TST1 AS DATETIME, @TST2 AS DATETIME, @TST3 AS DATETIME, @TST4 AS DATETIME;
SET @SD = '2021-01-01';
SET @ED = '2021-08-03';
SET @TST1 = '2021-06-06';
SET @TST2 = '2021-08-04';
SET @TST3 = '2020-12-25';
SET @TST4 = '2021-08-03';


-- Does @TST fall in RANGE(@SD, @ED)?

--SELECT (case when 1 <= 4 then 'yes' else 'no' end) as [A]

DECLARE @CTST AS DATETIME;

SET @CTST = @TST1;
SELECT 
	(CASE 
		WHEN YEAR(@SD) <= YEAR(@CTST) AND YEAR(@CTST) <= YEAR(@ED) AND MONTH(@SD) <= MONTH(@CTST) AND MONTH(@CTST) <= MONTH(@ED) THEN 'yes'
		ELSE 'no'
	END) AS [Does @TST1 fall in RANGE(@SD, @ED)?],
	'yes' AS [ANS]
	
SET @CTST = @TST2;
SELECT 
	(CASE 
		WHEN YEAR(@SD) <= YEAR(@CTST) AND YEAR(@CTST) <= YEAR(@ED) AND MONTH(@SD) <= MONTH(@CTST) AND MONTH(@CTST) <= MONTH(@ED) THEN 'yes'
		ELSE 'no'
	END) AS [Does @TST2 fall in RANGE(@SD, @ED)?],
	'no' AS [ANS]
	
SET @CTST = @TST3;
SELECT 
	(CASE 
		WHEN YEAR(@SD) <= YEAR(@CTST) AND YEAR(@CTST) <= YEAR(@ED) AND MONTH(@SD) <= MONTH(@CTST) AND MONTH(@CTST) <= MONTH(@ED) THEN 'yes'
		ELSE 'no'
	END) AS [Does @TST3 fall in RANGE(@SD, @ED)?],
	'no' AS [ANS]
	
SET @CTST = @TST4;
SELECT 
	(CASE 
		WHEN YEAR(@SD) <= YEAR(@CTST) AND YEAR(@CTST) <= YEAR(@ED) AND MONTH(@SD) <= MONTH(@CTST) AND MONTH(@CTST) <= MONTH(@ED) THEN 'yes'
		ELSE 'no'
	END) AS [Does @TST4 fall in RANGE(@SD, @ED)?],
	'yes' AS [ANS]
