USE [BWSdb]
GO

-- 2024-10-22 2100 - Avery Briggs - View of all Stargate WOs with the steps for quote cost calculations broken down. [NetCost] will be the total on the quote. Works for both US and CDN sales.

ALTER VIEW [v_SAL_OrdersPricingV2]
AS


SELECT
	[SGQuote]
	,[WO#]
	,[BasePrice]
	,[SumOfOptionPrice]
	,[SumOfNPOPrice]
	,[Discount1]
	,[Discount1_Name]
	,[Discount1_Type]
	,[Discount2]
	,[Discount2_Name]
	,[Discount2_Type]
	,[Discount3]
	,[Discount3_Name]
	,[Discount3_Type]
	,[Volume Discount]
	,[Program Discount]
	,[Total]
	,[D3]
	,[VolDis]
	,[D3SubTtl]
	,[SubTtl]
	,[ProDis]
	,[PDSubTtl]
	,[D1]
	,[PDSubTtl] + [D1] AS [NetCost]
FROM (
	SELECT
		[SGQuote]
		,[WO#]
		,[BasePrice]
		,[SumOfOptionPrice]
		,[SumOfNPOPrice]
		,[Discount1]
		,[Discount1_Name]
		,[Discount1_Type]
		,[Discount2]
		,[Discount2_Name]
		,[Discount2_Type]
		,[Discount3]
		,[Discount3_Name]
		,[Discount3_Type]
		,[Volume Discount]
		,[Program Discount]
		,[Total]
		,[D3]
		,[VolDis]
		,[D3SubTtl]
		,[SubTtl]
		,[ProDis]
		,[PDSubTtl]
		,(CASE WHEN [Discount1_Type] = 'Fixed' THEN [Discount1] ELSE (CASE WHEN [Discount1_Type] = 'Percent' THEN ([SubTtl] + [ProDis]) * ([Discount1] * -1) ELSE 0 END) END) AS [D1]
	FROM (
		SELECT
			[SGQuote]
			,[WO#]
			,[BasePrice]
			,[SumOfOptionPrice]
			,[SumOfNPOPrice]
			,[Discount1]
			,[Discount1_Name]
			,[Discount1_Type]
			,[Discount2]
			,[Discount2_Name]
			,[Discount2_Type]
			,[Discount3]
			,[Discount3_Name]
			,[Discount3_Type]
			,[Volume Discount]
			,[Program Discount]
			,[Total]
			,[D3]
			,[VolDis]
			,[D3SubTtl]
			,[SubTtl]
			,[ProDis]
			,[SubTtl] + [ProDis] AS [PDSubTtl]
		FROM (
			SELECT
				[SGQuote]
				,[WO#]
				,[BasePrice]
				,[SumOfOptionPrice]
				,[SumOfNPOPrice]
				,[Discount1]
				,[Discount1_Name]
				,[Discount1_Type]
				,[Discount2]
				,[Discount2_Name]
				,[Discount2_Type]
				,[Discount3]
				,[Discount3_Name]
				,[Discount3_Type]
				,[Volume Discount]
				,[Program Discount]
				,[Total]
				,[D3]
				,[VolDis]
				,[D3SubTtl]
				,[SubTtl]
				,[SubTtl] * ([Program Discount] * -1) AS [ProDis]
			FROM (
				SELECT
					[SGQuote]
					,[WO#]
					,[BasePrice]
					,[SumOfOptionPrice]
					,[SumOfNPOPrice]
					,[Discount1]
					,[Discount1_Name]
					,[Discount1_Type]
					,[Discount2]
					,[Discount2_Name]
					,[Discount2_Type]
					,[Discount3]
					,[Discount3_Name]
					,[Discount3_Type]
					,[Volume Discount]
					,[Program Discount]
					,[Total]
					,[D3]
					,[VolDis]
					,[D3SubTtl]
					,[D3SubTtl] + [VolDis] AS [SubTtl]
				FROM (
					SELECT
						[SGQuote]
						,[WO#]
						,[BasePrice]
						,[SumOfOptionPrice]
						,[SumOfNPOPrice]
						,[Discount1]
						,[Discount1_Name]
						,[Discount1_Type]
						,[Discount2]
						,[Discount2_Name]
						,[Discount2_Type]
						,[Discount3]
						,[Discount3_Name]
						,[Discount3_Type]
						,[Volume Discount]
						,[Program Discount]
						,[Total]
						,[D3]
						,(CASE WHEN [D3] IS NULL THEN [Total] ELSE [Total] + [D3] END) * ([Volume Discount] * -1) AS [VolDis]
						,[Total] + [D3] AS [D3SubTtl]
					FROM (
						SELECT
							[SGQuote]
							,[WO#]
							,[BasePrice]
							,[SumOfOptionPrice]
							,[SumOfNPOPrice]
							,[Discount1]
							,[Discount1_Name]
							,[Discount1_Type]
							,[Discount2]
							,[Discount2_Name]
							,[Discount2_Type]
							,[Discount3]
							,[Discount3_Name]
							,[Discount3_Type]
							,[Volume Discount]
							,[Program Discount]
							,[Total]
							,(CASE WHEN [Discount3_Type] = 'Fixed' THEN [Discount3] ELSE (CASE WHEN [Discount3_Type] = 'Percent' THEN [Total] * [Discount3] * -1 ELSE 0 END) END) AS [D3]
						FROM (
							SELECT
								[O2].[SGQuote]
								,[O2].[WO#]
								,[O2].[Price] AS [BasePrice]
								,SUM([OO2].[Price]) AS [SumOfOptionPrice]
								,SUM([CW2].[Price]) AS [SumOfNPOPrice]
								,ISNULL([Discount1], 0) AS [Discount1]
								,[Discount1_Name]
								,[Discount1_Type]
								,ISNULL([Discount2], 0) AS [Discount2]
								,[Discount2_Name]
								,[Discount2_Type]
								,ISNULL([Discount3], 0) AS [Discount3]
								,[Discount3_Name]
								,[Discount3_Type]
								,ISNULL([Volume Discount], 0) AS [Volume Discount]
								,ISNULL([Program Discount], 0) AS [Program Discount]
								,[O2].[Price] + [OO2].[Price] + (CASE WHEN [US Sale] = 1 THEN [CW2].[US Price] ELSE [CW2].[Price] END) AS [Total]
							FROM
								[BWSdb].[dbo].[OrdersV2] [O2]
							INNER JOIN
								[BWSdb].[dbo].[ProductsV2] [P2]
							ON
								[O2].[ProductID] = [P2].[IDTrailer]
							INNER JOIN (
								SELECT
									[SGQuote]
									,[WO#]
									,SUM([Qty] * [Price]) AS [Price]
								FROM
									[BWSdb].[dbo].[Order OptionsV2]
								GROUP BY
									[SGQuote]
									,[WO#]
							) AS [OO2]
							ON
								[O2].[SGQuote] = [OO2].[SGQuote]
							INNER JOIN(
								SELECT
									[Custom WorkV2].[SGQuote]
									,[Custom WorkV2].[WO#]
									,SUM(CASE WHEN [US Sale] = 1 THEN 0 ELSE [Custom WorkV2].[Price] END) AS [Price]
									,SUM(CASE WHEN [US Sale] = 1 THEN [Custom WorkV2].[US Price] ELSE 0 END) AS [US Price]
								FROM
									[BWSdb].[dbo].[Custom WorkV2]
								INNER JOIN
									[BWSdb].[dbo].[OrdersV2]
								ON
									[Custom WorkV2].[SGQuote] = [OrdersV2].[SGQuote]
								GROUP BY
									[Custom WorkV2].[SGQuote]
									,[Custom WorkV2].[WO#]
							) AS [CW2]
							ON
								[O2].[SGQuote] = [CW2].[SGQuote]
							GROUP BY
								[O2].[SGQuote]
								,[O2].[WO#]
								,[O2].[Price]
								,[O2].[US Sale]
								,[OO2].[Price]
								,[CW2].[Price]
								,[CW2].[US Price]
								,[Discount1]
								,[Discount1_Name]
								,[Discount1_Type]
								,[Discount2]
								,[Discount2_Name]
								,[Discount2_Type]
								,[Discount3]
								,[Discount3_Name]
								,[Discount3_Type]
								,[Volume Discount]
								,[Program Discount]
						) AS [BaseOptNPO]
					) AS [Step1]
				) AS [Step2]
			) AS [Step3]
		) AS [Step4]
	) AS [Step5]
) AS [Step6]
;

GO
