/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (100000) [HistoryID]
      ,[DateCreated]
      ,[UpdateType]
      ,[UpdatedColumn]
      ,[ValueBefore]
      ,[ValueAfter]
      ,[ChangedBy]
      ,[ITRequestID#]
      ,[StartDate]
      ,[RequestDate]
      ,[DueDate]
      ,[Request]
      ,[Priority]
      ,[SubPriority]
      ,[RequestedBy]
      ,[Department]
      ,[RequestFollowUpPerson]
      ,[RequestType]
      ,[RequestSubType]
      ,[Comments]
      ,[ITRequeststs]
      ,[Company]
      ,[Status]
      ,[Directory]
      ,[ITPersonAssignedID]
      ,[CompletionDate]
      ,[LastStatusUpdate]
      ,[LabourEstimate]
      ,[LabourActual]
      ,[TimerStart]
      ,[TimerStop]
      ,[Timer]
      ,[OpenCounter]
      ,[IsOpened]
      ,[RequestDateOriginal]
      ,[LinkNext]
      ,[LinkPrev]
      ,[RequesterLocked]
      ,[RequesterLockedDate]
      ,[AssignmentEmailDate]
  FROM [BWSdb].[dbo].[IT Requests History]
  WHERE [UpdatedColumn] <> 'TimerStop' AND [UpdatedColumn] <> 'TimerStart'
  ORDER BY [DateCreated] DESC, [HistoryID] DESC


  SELECT COUNT(*) FROM [BWSdb].[dbo].[IT Requests History]