SELECT
	'Avery' + CHAR(10) + 'Briggs'
SELECT
	'Avery' + CHAR(10) + 'Briggs'
	
SELECT (CASE WHEN 'Avery' <> NULL THEN 1 ELSE 0 END)  -- 1
SELECT (CASE WHEN 'Avery' = NULL THEN 1 ELSE 0 END) -- 0
SELECT (CASE WHEN 'Avery' IS NULL THEN 1 ELSE 0 END) -- 0

SELECT (CASE WHEN NULL <> NULL THEN 1 ELSE 0 END)  -- 0
SELECT (CASE WHEN NULL = NULL THEN 1 ELSE 0 END) -- 1
SELECT (CASE WHEN NULL IS NULL THEN 1 ELSE 0 END) -- 1