from utility import *

# Sample dictionaries to demonstrate the abilities of dict_print

WRITING = True

with open("dict_print_tests.txt", "w" if WRITING else "r") as out:
	
	def write(content):
		if WRITING:
			out.write(content + "\n")

	break_dict_print = {
		1: "A",
		2: ["A"],
		3: ["A", "B"],
		4: [i for i in range(12)],
		"I'm hoping this long key will have som e weird effect on the spacing": "A",
		6: "I'm hoping that this long value will have some weird effect on the spacing",
		7: "A",
		8: [i for i in range(12)],
		9: {"A":"".join(["#" for i in range(16)]), "B":2, "C":3, "D":4, "E":5},
		10: "A",
		11: "A",
		12: "A",
		13: [i for i in range(120)],
		14: "A",
		15: ["A", "B", "C", "D", "E", "F"],
		16: ["print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))"],
		17: ["print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))"],
		18: ["print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))"],
		19: ["print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))", "print(dict_print(\"top 5 bases: \", top_5_base(data_dict), number=True))"],
		20: "A",
		21: [i for i in range(12)]
	}


	test_dict_print = {
		"set 1": {i: chr(i) for i in range(97, 107)},
		"set 2": {i: chr(i-32) for i in range(97, 107)},
		"set 3": {i-32: chr(i-32) for i in range(97, 107)},
		"set 4": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 5": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 6": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 7": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 8": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 9": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 10": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 11": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 12": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 13": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 14": {chr(i-32): chr(i-32) for i in range(97, 107)},
		"set 15": {"first name": "Avery", "last name": "Briggs", "fav number": 10001212154542115, "fav string": "qwertyuiopasdfghjklzxcvbnm"}
	}
	
	times = {'1:00 AM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0},
                        '2:00 AM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0},
                        '3:00 AM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0},
                        '4:00 AM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0},
                        '5:00 AM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0},
                        '6:00 AM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0},
                        '7:00 AM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '8:00 AM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '9:00 AM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '10:00 AM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '11:00 AM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '12:00 PM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '1:00 PM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '2:00 PM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '3:00 PM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '4:00 PM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '5:00 PM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '6:00 PM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '7:00 PM': {'Sunday': 2,
                                    'Monday': 2,
                                    'Tuesday': 2,
                                    'Wednesday': 2,
                                    'Thursday': 2,
                                    'Friday': 2,
                                    'Saturday': 2},
                        '8:00 PM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0},
                        '9:00 PM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0},
                        '10:00 PM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0},
                        '11:00 PM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0},
                        '12:00 AM': {'Sunday': 0,
                                    'Monday': 0,
                                    'Tuesday': 0,
                                    'Wednesday': 0,
                                    'Thursday': 0,
                                    'Friday': 0,
                                    'Saturday': 0}}
	
	fares = {  
		"Oromocto": {"fare": 15, "distance" : 21.5},
		"Base Gagetown": {"fare": 15, "distance": 25.8},
		"Keswick Ridge": {"fare": 19, "distance": 23.2},
		"Keswick Valley": {"fare": 22, "distance": 29.5},
		"Fredericton Junction": {"fare": 30, "distance": 36.6},
		"Harvey": {"fare": 35, "distance": 49.2},
		"Stanley": {"fare": 38, "distance": 42.6},
		"Minto": {"fare": 38, "distance": 65.3},
		"Gagetown": {"fare": 45, "distance": 58.2},
		"Nackawic": {"fare": 48, "distance": 63.9},
		"Cambridge Narrows": {"fare": 53, "distance": 68.8},
		"Chipman": {"fare": 57, "distance": 91.7},
		"Central NB Academy": {"fare": 60, "distance": 76.9}
	}
	
	digimon = {
		"Botamon": ["Wanyamon", "Koromon"],
		"Kuramon": ["Tsumemon", "Pagumon"],
		"Pabumon": ["Motimon", "Tanemon", "Yokomon"],
		"Poyomon": ["Bukamon", "Tokomon"],
		"Punimon": ["Nyaromon", "Tsunomon"],
		"Bukamon": ["Otamamon", "Gomamon", "Syakomon", "Betamon"],
		"Koromon": ["Agumon", "Hackmon", "Guilmon", "ToyAgumon", "Dracomon", "Shoutmon"],
		"Motimon": ["Gotsumon", "Hagurumon", "Tentomon",  "Solarmon"],
		"Nyaromon": ["Armadillomon", "Terriermon", "Salamon", "Lunamon"],
		"Pagumon": ["Gazimon", "Impmon", "Lopmon", "Chuumon"],
		"Tanemon": ["Palmon", "Lalamon", "Renamon", "FanBeemon"],
		"Tokomon": ["Falcomon", "Hawkmon", "Lucemon", "Patamon", "Sistermon_Blanc"],
		"Tsumemon": ["Keramon", "DemiDevimon", "Agumon_(Blk)", "Dracmon"],
		"Tsunomon": ["Gabumon", "Goblimon", "Veemon", "Gabumon_(Blk)", "Zubamon", "Monodramon"],
		"Wanyamon": ["Dorumon", "Gaomon", "Kudamon", "Ryudamon"],
		"Yokomon": ["Elecmon", "Wormmon", "Biyomon", "Mushroomon"],
		"Agumon": ["Sukamon", "Greymon", "GeoGreymon", "Meramon", "Tyrannomon", ""],
		"Agumon_(Blk)": ["Growlmon", "Cyclonemon", "Tankmon", "Tyrannomon", "Monochromon", "Greymon_(Blue)"],
		"Armadillomon": ["Ankylomon", "Cyclonemon", "GoldNumemon", "Tankmon", "Geremon", "Golemon"],
		"Betamon": ["Airdramon", "Gekomon", "Numemon", "Seadramon", "ShellNumemon", "Vegiemon"],
		"Biyomon": ["Kabuterimon", "Aquilamon", "Birdramon", "Kyubimon", "Airdramon"],
		"Chuumon": ["Nanimon", "BlackGatomon", "Raremon", ""],
		"DemiDevimon": ["Bakemon", "Devimon", "Kyubimon", "Kurisarimon", "IceDevimon"],
		"Dorumon": ["Cyclonemon", "Dorugamon", "Guardromon", "Waspmon", "Raptordramon"],
		"Dracmon": ["Sangloupmon", "Devimon", "Raremon", "", ""],
		"Dracomon": ["Coredramon_(Blue)", "Veedramon", "Ginryumon", ""],
		"Elecmon": ["Garurumon", "Leomon", "Nanimon", "Sukamon", "Garurumon_(Blk)", "Geremon"],
		"Falcomon": ["Stingmon", "ExVeemon", "Aquilamon", "Peckmon"],
		"FanBeemon": ["Guardromon_(Gold)", "Stingmon", "Raptordramon", "Waspmon", "Togemon"],
		"Gabumon": ["Dorugamon", "Garurumon", "Numemon", "Veedramon", "Frigimon", ""],
		"Gabumon_(Blk)": ["Garurumon_(Blk)", "Vegiemon", "Reppamon", "Frigimon", "Raremon"],
		"Gaomon": ["Gargomon", "GaoGamon", "Leomon", "Togemon", "Ogremon", "Sangloupmon"],
		"Gazimon": ["Dorugamon", "GaoGamon", "Leomon", "Kurisarimon", "Nanimon", "Garurumon_(Blk)"],
		"Goblimon": ["GaoGamon", "Growlmon", "Nanimon", "Ogremon", "", "Greymon_(Blue)"],
		"Gomamon": ["Ankylomon", "Ikkakumon", "Socerimon", "Frigimon", "Strikedramon", ""],
		"Gotsumon": ["Ankylomon", "Clockmon", "Starmon", "Tankmon", "Golemon", ""],
		"Guilmon": ["GeoGreymon", "Growlmon", "Meramon", "Tyrannomon", "", "Greymon_(Blue)"],
		"Hackmon": ["Jesmon", "Greymon", "GeoGreymon", "PlatinumSukamon"],
		"Hagurumon": ["Clockmon", "GoldNumemon", "Guardromon", "Starmon", "PlatinumSukamon"],
		"Hawkmon": ["Meramon", "Aquilamon", "Birdramon", "Peckmon", "Airdramon"],
		"Impmon": ["Bakemon", "Ogremon", "Socerimon", "BlackGatomon", "Wizardmon", "IceDevimon"],
		"Keramon": ["Bakemon", "Kurisarimon", "PlatinumSukamon", "Wizardmon", ""],
		"Kudamon": ["Angemon", "GoldNumemon", "Peckmon", "Reppamon", ""],
		"Lalamon": ["Sunflowmon", "Togemon", "Vegiemon", "Woodmon"],
		"Lopmon": ["Gargomon", "Devimon", "BlackGatomon", "Wizardmon", "MudFrigimon", "Turuiemon"],
		"Lucemon": ["Angemon", "Devimon", "Lucemon_FM"],
		"Lunamon": ["Sangloupmon", "Gatomon", "Lekismon", ""],
		"Mushroomon": ["Woodmon", "Sunflowmon", "MudFrigimon", "Vegiemon"],
		"Monodramon": ["Kurisarimon", "Coredramon_(Blue)", "Strikedramon", "Dorugamon", "Raptordramon"],
		"Otamamon": ["Gekomon", "Numemon", "Seadramon", "ShellNumemon", "Coelamon", "Raremon"],
		"Palmon": ["Kuwagamon", "Togemon", "Vegiemon", "Sunflowmon", "Woodmon", "MudFrigimon"],
		"Patamon": ["Angemon", "Birdramon", "Reppamon", "Gatomon", "ExVeemon", "Unimon"],
		"Renamon": ["BlackGatomon", "Garurumon", "Kyubimon", "Woodmon", "Turuiemon", "Lekismon"],
		"Salamon": ["Frigimon", "Reppamon", "Gatomon", "Veedramon", "Socerimon", ""],
		"Solarmon": ["Clockmon", "Geremon", "Starmon", "Meramon", "Guardromon_(Gold)", "Golemon"],
		"Syakomon": ["Ikkakumon", "ShellNumemon", "Gekomon", "Seadramon", "Coelamon"],
		"Tentomon": ["Kabuterimon", "Waspmon", "Kuwagamon", "Stingmon", "Sunflowmon"],
		"Terriermon": ["Gargomon", "Ikkakumon", "Gatomon", "Rapidmon_(Armor)", "Unimon"],
		"ToyAgumon": ["Clockmon", "Greymon", "Guardromon", "Sukamon", "Starmon", "Guardromon_(Gold)"],
		"Veemon": ["Flamedramon", "Magnamon", "Veedramon", "ExVeemon", "Strikedramon", ""],
		"Wormmon": ["Waspmon", "Kabuterimon", "Kuwagamon", "Stingmon", "IceDevimon", ""],
		"Zubamon": ["GoldNumemon", "Ginryumon", "", ""],
		"Airdramon": ["MegaSeadramon", "Megadramon", "MetalGreymon", ""],
		"Angemon": ["Garudamon", "MagnaAngemon", "Shakkoumon"],
		"Ankylomon": ["MagnaAngemon", "Meteormon", "Shakkoumon", "SkullGreymon", ""],
		"Aquilamon": ["AeroVeedramon", "Garudamon", "Silphymon", "Crowmon", ""],
		"Bakemon": ["BlueMeramon", "Pumpkinmon", "Myotismon", "LadyDevimon", "", ""],
		"Birdramon": ["AeroVeedramon", "Garudamon", "Chirinmon", "Crowmon", "", ""],
		"Clockmon": ["Andromon", "Knightmon", "Datamon", "Wisemon"],
		"Coelamon": ["Andromon", "MegaSeadramon", "Dragomon", ""],
		"Coredramon_(Blue)": ["AeroVeedramon", "", ""],
		"Coredramon_(Green)": ["WarGrowlmon", "", ""],
		"Cyclonemon": ["Megadramon", "DoruGreymon", "Datamon"],
		"Devimon": ["BlueMeramon", "Infermon", "MetalGreymon_(Blue)", "Myotismon"],
		"Dorugamon": ["RizeGreymon", "DoruGreymon", "Chirinmon", "Grademon"],
		"ExVeemon": ["MagnaAngemon", "RizeGreymon", "Paildramon", "", ""],
		"Frigimon": ["Zudomon", "Angewomon", "Monzaemon", ""],
		"GaoGamon": ["GrapLeomon", "MachGaogamon", "WereGarurumon"],
		"Gargomon": ["WarGrowlmon", "Antylamon", "Rapidmon"],
		"Garurumon": ["DoruGreymon", "Panjyamon", "WereGarurumon", "Zudomon"],
		"Garurumon_(Blk)": ["WereGarurumon_(Blk)", "BlueMeramon", "MachGaogamon", ""],
		"Gatomon": ["Angewomon", "Lillymon", "Silphymon", ""],
		"BlackGatomon": ["Cyberdramon", "Knightmon", "LadyDevimon", "WereGarurumon_(Blk)"],
		"Gekomon": ["MegaSeadramon", "ShogunGekomon", "Whamon"],
		"GeoGreymon": ["Gigadramon", "RizeGreymon", "SkullGreymon", ""],
		"Geremon": ["Etemon", "SuperStarmon", "MetalMamemon"],
		"GoldNumemon": ["Vademon", "PlatinumNumemon", "BlackKingNumemon"],
		"Greymon": ["MetalGreymon", "MetalGreymon_(Blue)", "Megadramon", "SkullGreymon"],
		"Greymon_(Blue)": ["MetalGreymon_(Blue)", "Knightmon", "DoruGreymon", "Triceramon"],
		"Growlmon": ["Gigadramon", "WarGrowlmon", "MetalGreymon", "MetalTyrannomon", ""],
		"Guardromon": ["Andromon", "GrapLeomon", "MetalMamemon", "Datamon"],
		"Guardromon_(Gold)": ["Andromon", "Grademon", "Rapidmon_(Armor)", "", ""],
		"IceDevimon": ["Myotismon", "Cherrymon", "LadyDevimon", "Dragomon", ""],
		"Ikkakumon": ["MachGaogamon", "Whamon", "Zudomon"],
		"Kabuterimon": ["MegaKabuterimon", "Cherrymon", "Lilamon"],
		"Kurisarimon": ["Cyberdramon", "Infermon", "Taomon", ""],
		"Kuwagamon": ["Cherrymon", "Okuwamon", "CannonBeemon"],
		"Kyubimon": ["LadyDevimon", "Monzaemon", "Taomon"],
		"Lekismon": ["MachGaogamon", "", ""],
		"Leomon": ["GrapLeomon", "MetalGreymon", "Meteormon", "Panjyamon", "Grademon"],
		"Meramon": ["BlueMeramon", "SkullMeramon", "Mamemon", "Panjyamon", "", ""],
		"MudFrigimon": ["Meteormon", "", ""],
		"Nanimon": ["Digitamamon", "SuperStarmon", "Meteormon"],
		"Numemon": ["BlackKingNumemon", "Etemon", "Monzaemon"],
		"Ogremon": ["SkullMeramon", "Digitamamon", "WereGarurumon"],
		"Peckmon": ["Antylamon", "Piximon", "Crowmon"],
		"PlatinumSukamon": ["Etemon", "MetalMamemon", "Vademon"],
		"Raptordramon": ["Grademon", "DoruGreymon", "", ""],
		"Raremon": ["BlackKingNumemon", "MetalGreymon_(Blue)", "Dragomon", "", ""],
		"Reppamon": ["Rapidmon", "Piximon", "Chirinmon"],
		"Sangloupmon": ["WereGarurumon_(Blk)", "", "", ""],
		"Seadramon": ["ShogunGekomon", "MegaSeadramon", "Whamon", ""],
		"ShellNumemon": ["BlackKingNumemon", "MegaSeadramon", "ShogunGekomon"],
		"Socerimon": ["Antylamon", "Piximon", "Wisemon"],
		"Starmon": ["Mamemon", "MetalMamemon", "SuperStarmon", "CatchMamemon", ""],
		"Stingmon": ["Infermon", "Okuwamon", "Paildramon", ""],
		"Strikedramon": ["Cyberdramon", "SaviorHuckmon", ""],
		"Sukamon": ["SuperStarmon", "Etemon", "Vademon"],
		"Sunflowmon": ["Angewomon", "Lilamon", "Lillymon"],
		"Tankmon": ["Andromon", "Gigadramon", "CannonBeemon", "Knightmon", ""],
		"Togemon": ["MachGaogamon", "Lillymon", "Pumpkinmon"],
		"Turuiemon": ["Cyberdramon", "Monzaemon", ""],
		"Tyrannomon": ["Mamemon", "Megadramon", "MetalGreymon_(Blue)", "MetalTyrannomon"],
		"Veedramon": ["AeroVeedramon", "Cyberdramon", "MetalTyrannomon", "WarGrowlmon"],
		"Vegiemon": ["Digitamamon", "Lilamon", "MegaKabuterimon"],
		"Waspmon": ["CannonBeemon", "Rapidmon", "MegaKabuterimon", "Okuwamon"],
		"Wizardmon": ["SkullMeramon", "Myotismon", "Wisemon", ""],
		"Woodmon": ["Cherrymon", "Pumpkinmon", "Taomon"],
		"AeroVeedramon": ["Ravemon", "Dynasmon", "UlforceVeedramon", ""],
		"Andromon": ["Craniamon", "HiAndromon", "TigerVespamon"],
		"Angewomon": ["Magnadramon", "Ophanimon", "Mastemon", ""],
		"Antylamon": ["Kerpymon_(Good)", "Diaboromon", "Dianamon", "Kerpymon_(Blk)"],
		"BlackKingNumemon": ["PlatinumNumemon", "MetalEtemon", "PrinceMamemon"],
		"BlueMeramon": ["Barbamon", "Boltmon", "Creepymon"],
		"CannonBeemon": ["MegaGargomon", "GroundLocomon", "TigerVespamon"],
		"CatchMamemon": ["PrinceMamemon", "", ""],
		"Cherrymon": ["GranKuwagamon", "Kuzuhamon", "Puppetmon"],
		"Chirinmon": ["MetalGarurumon", "Seraphimon", "Kentaurosmon"],
		"Crowmon": ["Minervamon", "Ravemon", "Kuzuhamon", "Ouryumon", ""],
		"Cyberdramon": ["Justimon", "Titamon", "Alphamon"],
		"Datamon": ["Machinedramon", "MetalGarurumon_(Blk)", "GroundLocomon"],
		"Digitamamon": ["Minervamon", "Belphemon_SM", "Titamon"],
		"DoruGreymon": ["Alphamon", "Examon", "Kentaurosmon", "breakdramon"],
		"Etemon": ["MetalEtemon", "Piedmon", "PlatinumNumemon", "", ""],
		"Garudamon": ["Hououmon", "Justimon", "Ravemon"],
		"Gigadramon": ["MetalSeadramon", "Machinedramon", "GroundLocomon"], 
		"Grademon": ["TigerVespamon", "Durandamon", "Ouryumon"],
		"GrapLeomon": ["BanchoLeomon", "Leopardmon", "SaberLeomon"],
		"Infermon": ["Beelzemon", "Diaboromon", "VenomMyotismon", ""],
		"Knightmon": ["Craniamon", "Leopardmon", "Crusadermon", "Durandamon"],
		"LadyDevimon": ["Lilithmon", "Lotosmon", "Mastemon"],
		"Lilamon": ["Lilithmon", "Lotosmon", "Rosemon"], 
		"Lillymon": ["Magnadramon", "Lotosmon", "Rosemon"],
		"Lucemon_FM": ["Lucemon_SM"],
		"MachGaogamon": ["BanchoLeomon", "MirageGaogamon", "MegaGargomon", ""],
		"MagnaAngemon": ["ShineGreymon", "Crusadermon", "Seraphimon", "", ""],
		"Mamemon": ["Puppetmon", "PrinceMamemon", "WarGreymon"],
		"Megadramon": ["BlackWarGreymon", "Machinedramon", "UlforceVeedramon", "", ""],
		"MegaKabuterimon": ["GranKuwagamon", "Magnadramon", "HerculesKabuterimon"],
		"MegaSeadramon": ["Leviamon", "MetalSeadramon", "Plesiomon", ""],
		"MetalGreymon": ["RustTyranomon", "Gaiomon", "WarGreymon"],
		"MetalGreymon_(Blue)": ["BlackWarGreymon", "Gaiomon", "WarGreymon", ""],
		"MetalMamemon": ["Ebemon", "HiAndromon", "PrinceMamemon"],
		"MetalTyrannomon": ["BlackWarGreymon", "Gallantmon", "RustTyranomon"],
		"Meteormon": ["Ebemon", "MetalEtemon", "Dianamon"],
		"Monzaemon": ["Minervamon", "Sakuyamon", "SaberLeomon"],
		"Myotismon": ["Barbamon", "Piedmon", "VenomMyotismon"],
		"Okuwamon": ["Diaboromon", "GranKuwagamon", "HerculesKabuterimon"],
		"Paildramon": ["Imperialdramon_DM"],
		"Panjyamon": ["Boltmon", "SaberLeomon", "MirageGaogamon"],
		"Piximon": ["Hououmon", "MarineAngemon", "Ophanimon"],
		"Pumpkinmon": ["Boltmon", "Puppetmon", "Rosemon"],
		"Rapidmon": ["MegaGargomon", "TigerVespamon", "MetalGarurumon_(Blk)"],
		"RizeGreymon": ["Examon", "Gaiomon", "ShineGreymon"],
		"SaviorHuckmon": ["", "", ""],
		"Shakkoumon": ["Kerpymon_(Good)", "Vikemon", "ChaosGallantmon"],
		"ShogunGekomon": ["Plesiomon", "Leviamon", "Vikemon", ""],
		"Silphymon": ["Dynasmon", "Hououmon", "Sakuyamon"],
		"SkullGreymon": ["Creepymon", "ShineGreymon", "Titamon"],
		"SkullMeramon": ["Gankoomon", "Beelzemon", "Boltmon"],
		"SuperStarmon": ["Justimon", "Gankoomon", "PlatinumNumemon"],
		"Taomon": ["Dianamon", "Kuzuhamon", "Sakuyamon"],
		"Triceramon": ["GranKuwagamon", "SaberLeomon", "breakdramon"],
		"Vademon": ["Ebemon", "HerculesKabuterimon", "HiAndromon"],
		"WarGrowlmon": ["Gallantmon", "ChaosGallantmon", "RustTyranomon", "", ""],
		"WereGarurumon": ["MetalGarurumon", "MetalGarurumon_(Blk)", "MirageGaogamon"],
		"WereGarurumon_(Blk)": ["MetalGarurumon_(Blk)", "Minervamon", "BanchoLeomon", ""],
		"Whamon": ["Plesiomon", "MarineAngemon", "MetalSeadramon"],
		"Wisemon": ["VenomMyotismon", "Belphemon_SM", "Piedmon"],
		"Zudomon": ["MetalGarurumon", "MarineAngemon", "Vikemon"],
		"Imperialdramon_DM": ["Imperialdramon_PM"],
		"WarGreymon + MetalGarurumon": ["Omnimon"],
		"BlackWarGreymon + MetalGarurumon_(Blk)": ["Omnimon_Zwart"],
		"Belphemon_SM": ["Belphemon_RM"],
		"Beelzemon": ["Beelzemon_BM"],
		"Gaiomon": [],
		"Kuzuhamon": [],
		"GranKuwagamon": [],
		"SaberLeomon": [],
		"MegaGargomon": [],
		"Diaboromon": [""],
		"Durandamon": [],
		"PrinceMamemon": [],
		"breakdramon": [""],
		"Minervamon": [],
		"MirageGaogamon": ["MirageGaogamon_BM"],
		"MirageGaogamon_BM": [],
		"Shoutmon": [""],
		"Ryudamon": ["Ginryumon", "Raptordramon", "Reppamon"],
		"Ginryumon": ["CannonBeemon", "MegaSeadramon", ""],
		"Ouryumon": [""],
		"Sistermon_Blanc": ["Gargomon", "Lekismon", "",""],
		"Alphamon_NX": [],
		"Crusadermon_NX": [],
		"Leopardmon_NX": [],
		"Omnimon_NX": [],
		"Gallantmon_NX": [],
		"Dragomon": ["", "", ""]
	}

	long_list = {
		'$ 0.00': [
					{
						'Quote': 25544,
						'Model': '30NTT'
					},
					{
						'Quote': 25545,
						'Model': '51LF4X5T V2018'
					},
					{
						'Quote': 25570,
						'Model': '35ADG2X48 AGULP'
					},
					{
						'Quote': 25571,
						'Model': '35ADG2X48 AGULP'
					},
					{
						'Quote': 25573,
						'Model': '35HDG2X48 AGULP'
					},
					{
						'Quote': 25631,
						'Model': '30ANR'
					},
					{
						'Quote': 25651,
						'Model': '35ADG2X51 AGNR'
					},
					{
						'Quote': 25665,
						'Model': '20ART'
					},
					{
						'Quote': 25687,
						'Model': '30ANR'
					},
					{
						'Quote': 25713,
						'Model': '48HF2X'
					},
					{
						'Quote': 25714,
						'Model': '53HD3X 2018'
					},
					{
						'Quote': 25715,
						'Model': '53ET2X'
					},
					{
						'Quote': 25772,
						'Model': '53ET3XP'
					},
					{
						'Quote': 25775,
						'Model': '53ET3X'
					}
				],
		'$ -134.00': {
			'Quote': 25668,
			'Model': '35FA'
			},
		'$ -302.00': {
			'Quote': 25672,
			'Model': '30ANR'
			},
		'$ -305.00': {
			'Quote': 25598,
			'Model': '25NTT'
			},
		'$ -311.00': {
			'Quote': 25674,
			'Model': '20ART'
		}
	}

#############################################################################################################################################################

	to_test = {
		"Break dict print:": (break_dict_print, {"number": True}),
		"test dict print:": (test_dict_print, {"number": True, "sort_header": True, "min_encapsulation": True}),
		"times": (times, {"min_encapsulation": True}),
		"fares": (fares, {"number": True, "min_encapsulation": True}),
		"digimon": (digimon, {"number": True, "min_encapsulation": True}),
		"long list": (long_list, {"number": True, "min_encapsulation": True})
	}
	
	for title, vals in to_test.items():
		print("vals: {}".format(vals))
		d, kwargs = vals
		print(dict_print(d, title, **kwargs))
		write(dict_print(d, title, **kwargs))