/****** Object:  Table [dbo].[INV_WarehouseLayout_Montana]    Script Date: 2026-01-20 09:23:24 ******/
USE [BWSdb]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<Avery Briggs>
-- Create today:	<2026-01-20 09:23:24>
-- Description:	<Create Table [BWSdb].[dbo].[INV_WarehouseLayout_Montana]>
-- =============================================
CREATE TABLE [dbo].[INV_WarehouseLayout_Montana] (
	[ID] [int] IDENTITY(0, 1) NOT NULL,

	[A] NVARCHAR(50) NULL,
	[B] NVARCHAR(50) NULL,
	[C] NVARCHAR(50) NULL,
	[D] NVARCHAR(50) NULL,
	[E] NVARCHAR(50) NULL,
	[F] NVARCHAR(50) NULL,
	[G] NVARCHAR(50) NULL,
	[H] NVARCHAR(50) NULL,
	[I] NVARCHAR(50) NULL,
	[J] NVARCHAR(50) NULL,
	[K] NVARCHAR(50) NULL,
	[L] NVARCHAR(50) NULL,
	[M] NVARCHAR(50) NULL,
	[N] NVARCHAR(50) NULL,
	[O] NVARCHAR(50) NULL,
	[P] NVARCHAR(50) NULL,
	[Q] NVARCHAR(50) NULL,
	[R] NVARCHAR(50) NULL,
	[S] NVARCHAR(50) NULL,
	[T] NVARCHAR(50) NULL,
	[U] NVARCHAR(50) NULL,
	[V] NVARCHAR(50) NULL,
	[W] NVARCHAR(50) NULL,
	[X] NVARCHAR(50) NULL,
	[Y] NVARCHAR(50) NULL,
	[Z] NVARCHAR(50) NULL,

	[AA] NVARCHAR(50) NULL,
	[AB] NVARCHAR(50) NULL,
	[AC] NVARCHAR(50) NULL,
	[AD] NVARCHAR(50) NULL,
	[AE] NVARCHAR(50) NULL,
	[AF] NVARCHAR(50) NULL,
	[AG] NVARCHAR(50) NULL,
	[AH] NVARCHAR(50) NULL,
	[AI] NVARCHAR(50) NULL,
	[AJ] NVARCHAR(50) NULL,
	[AK] NVARCHAR(50) NULL,
	[AL] NVARCHAR(50) NULL,
	[AM] NVARCHAR(50) NULL,
	[AN] NVARCHAR(50) NULL,
	[AO] NVARCHAR(50) NULL,
	[AP] NVARCHAR(50) NULL,
	[AQ] NVARCHAR(50) NULL,
	[AR] NVARCHAR(50) NULL,
	[AS] NVARCHAR(50) NULL,
	[AT] NVARCHAR(50) NULL,
	[AU] NVARCHAR(50) NULL,
	[AV] NVARCHAR(50) NULL,
	[AW] NVARCHAR(50) NULL,
	[AX] NVARCHAR(50) NULL,
	[AY] NVARCHAR(50) NULL,
	[AZ] NVARCHAR(50) NULL,

	[BA] NVARCHAR(50) NULL,
	[BB] NVARCHAR(50) NULL,
	[BC] NVARCHAR(50) NULL,
	[BD] NVARCHAR(50) NULL,
	[BE] NVARCHAR(50) NULL,
	[BF] NVARCHAR(50) NULL,
	[BG] NVARCHAR(50) NULL,
	[BH] NVARCHAR(50) NULL,
	[BI] NVARCHAR(50) NULL,
	[BJ] NVARCHAR(50) NULL,
	[BK] NVARCHAR(50) NULL,
	[BL] NVARCHAR(50) NULL,
	[BM] NVARCHAR(50) NULL,
	[BN] NVARCHAR(50) NULL,
	[BO] NVARCHAR(50) NULL,
	[BP] NVARCHAR(50) NULL,
	[BQ] NVARCHAR(50) NULL,
	[BR] NVARCHAR(50) NULL,
	[BS] NVARCHAR(50) NULL,
	[BT] NVARCHAR(50) NULL,
	[BU] NVARCHAR(50) NULL,
	[BV] NVARCHAR(50) NULL,
	[BW] NVARCHAR(50) NULL,
	[BX] NVARCHAR(50) NULL,
	[BY] NVARCHAR(50) NULL,
	[BZ] NVARCHAR(50) NULL,

	[CA] NVARCHAR(50) NULL,
	[CB] NVARCHAR(50) NULL,
	[CC] NVARCHAR(50) NULL,
	[CD] NVARCHAR(50) NULL,
	[CE] NVARCHAR(50) NULL,
	[CF] NVARCHAR(50) NULL,
	[CG] NVARCHAR(50) NULL,
	[CH] NVARCHAR(50) NULL,
	[CI] NVARCHAR(50) NULL,
	[CJ] NVARCHAR(50) NULL,
	[CK] NVARCHAR(50) NULL,
	[CL] NVARCHAR(50) NULL,
	[CM] NVARCHAR(50) NULL,
	[CN] NVARCHAR(50) NULL,
	[CO] NVARCHAR(50) NULL,
	[CP] NVARCHAR(50) NULL,
	[CQ] NVARCHAR(50) NULL,
	[CR] NVARCHAR(50) NULL,
	[CS] NVARCHAR(50) NULL,
	[CT] NVARCHAR(50) NULL,
	[CU] NVARCHAR(50) NULL,
	[CV] NVARCHAR(50) NULL,
	[CW] NVARCHAR(50) NULL,
	[CX] NVARCHAR(50) NULL,
	[CY] NVARCHAR(50) NULL,
	[CZ] NVARCHAR(50) NULL,

	[DA] NVARCHAR(50) NULL,
	[DB] NVARCHAR(50) NULL,
	[DC] NVARCHAR(50) NULL,
	[DD] NVARCHAR(50) NULL,
	[DE] NVARCHAR(50) NULL,
	[DF] NVARCHAR(50) NULL,
	[DG] NVARCHAR(50) NULL,
	[DH] NVARCHAR(50) NULL,
	[DI] NVARCHAR(50) NULL,
	[DJ] NVARCHAR(50) NULL,
	[DK] NVARCHAR(50) NULL,
	[DL] NVARCHAR(50) NULL,
	[DM] NVARCHAR(50) NULL,
	[DN] NVARCHAR(50) NULL,
	[DO] NVARCHAR(50) NULL,
	[DP] NVARCHAR(50) NULL,
	[DQ] NVARCHAR(50) NULL,
	[DR] NVARCHAR(50) NULL,
	[DS] NVARCHAR(50) NULL,
	[DT] NVARCHAR(50) NULL,
	[DU] NVARCHAR(50) NULL,
	[DV] NVARCHAR(50) NULL,
	[DW] NVARCHAR(50) NULL,
	[DX] NVARCHAR(50) NULL,
	[DY] NVARCHAR(50) NULL,
	[DZ] NVARCHAR(50) NULL

	CONSTRAINT [PK_INV_WarehouseLayout_Montana] PRIMARY KEY CLUSTERED (
        [ID] ASC
    )
    WITH (
        PAD_INDEX = OFF,
        STATISTICS_NORECOMPUTE = OFF,
        IGNORE_DUP_KEY = OFF,
        ALLOW_ROW_LOCKS = ON,
        ALLOW_PAGE_LOCKS = ON
        --, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
    ) ON [PRIMARY]
)
GO