/****** Object:  Table [dbo].[INV_WarehouseLayout_Hawkins]    Script Date: 2026-01-07 07:31:51 ******/
USE [BWSdb]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<Avery Briggs>
-- Create today:	<2026-01-07 07:31:51>
-- Description:	<Create Table [BWSdb].[dbo].[INV_WarehouseLayout_Hawkins]>
-- =============================================
CREATE TABLE [dbo].[INV_WarehouseLayout_Hawkins] (
	[ID] [int] IDENTITY(0, 1) NOT NULL,

	[A] NVARCHAR(50) NULL,
	[B] NVARCHAR(50) NULL,
	[C] NVARCHAR(50) NULL,
	[D] NVARCHAR(50) NULL,
	[E] NVARCHAR(50) NULL,
	[F] NVARCHAR(50) NULL,
	[G] NVARCHAR(50) NULL,
	[H] NVARCHAR(50) NULL,
	[I] NVARCHAR(50) NULL,
	[J] NVARCHAR(50) NULL,
	[K] NVARCHAR(50) NULL,
	[L] NVARCHAR(50) NULL,
	[M] NVARCHAR(50) NULL,
	[N] NVARCHAR(50) NULL,
	[O] NVARCHAR(50) NULL,
	[P] NVARCHAR(50) NULL,
	[Q] NVARCHAR(50) NULL,
	[R] NVARCHAR(50) NULL,
	[S] NVARCHAR(50) NULL,
	[T] NVARCHAR(50) NULL,
	[U] NVARCHAR(50) NULL,
	[V] NVARCHAR(50) NULL,
	[W] NVARCHAR(50) NULL,
	[X] NVARCHAR(50) NULL,
	[Y] NVARCHAR(50) NULL,
	[Z] NVARCHAR(50) NULL,

	[AA] NVARCHAR(50) NULL,
	[AB] NVARCHAR(50) NULL,
	[AC] NVARCHAR(50) NULL,
	[AD] NVARCHAR(50) NULL,
	[AE] NVARCHAR(50) NULL,
	[AF] NVARCHAR(50) NULL,
	[AG] NVARCHAR(50) NULL,
	[AH] NVARCHAR(50) NULL,
	[AI] NVARCHAR(50) NULL,
	[AJ] NVARCHAR(50) NULL,
	[AK] NVARCHAR(50) NULL,
	[AL] NVARCHAR(50) NULL,
	[AM] NVARCHAR(50) NULL,
	[AN] NVARCHAR(50) NULL,
	[AO] NVARCHAR(50) NULL,
	[AP] NVARCHAR(50) NULL,
	[AQ] NVARCHAR(50) NULL,
	[AR] NVARCHAR(50) NULL,
	[AS] NVARCHAR(50) NULL,
	[AT] NVARCHAR(50) NULL,
	[AU] NVARCHAR(50) NULL,
	[AV] NVARCHAR(50) NULL,
	[AW] NVARCHAR(50) NULL,
	[AX] NVARCHAR(50) NULL,
	[AY] NVARCHAR(50) NULL,
	[AZ] NVARCHAR(50) NULL,

	[BA] NVARCHAR(50) NULL,
	[BB] NVARCHAR(50) NULL,
	[BC] NVARCHAR(50) NULL,
	[BD] NVARCHAR(50) NULL,
	[BE] NVARCHAR(50) NULL,
	[BF] NVARCHAR(50) NULL,
	[BG] NVARCHAR(50) NULL,
	[BH] NVARCHAR(50) NULL,
	[BI] NVARCHAR(50) NULL,
	[BJ] NVARCHAR(50) NULL,
	[BK] NVARCHAR(50) NULL,
	[BL] NVARCHAR(50) NULL,
	[BM] NVARCHAR(50) NULL,
	[BN] NVARCHAR(50) NULL,
	[BO] NVARCHAR(50) NULL,
	[BP] NVARCHAR(50) NULL,
	[BQ] NVARCHAR(50) NULL,
	[BR] NVARCHAR(50) NULL,
	[BS] NVARCHAR(50) NULL,
	[BT] NVARCHAR(50) NULL,
	[BU] NVARCHAR(50) NULL,
	[BV] NVARCHAR(50) NULL,
	[BW] NVARCHAR(50) NULL,
	[BX] NVARCHAR(50) NULL,
	[BY] NVARCHAR(50) NULL,
	[BZ] NVARCHAR(50) NULL

	CONSTRAINT [PK_INV_WarehouseLayout_Hawkins] PRIMARY KEY CLUSTERED (
        [ID] ASC
    )
    WITH (
        PAD_INDEX = OFF,
        STATISTICS_NORECOMPUTE = OFF,
        IGNORE_DUP_KEY = OFF,
        ALLOW_ROW_LOCKS = ON,
        ALLOW_PAGE_LOCKS = ON
        --, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
    ) ON [PRIMARY]
)
GO