SELECT 
	[B_CW].[ID],
    [B_CW].[Quote Date],
    CAST([B_CW].[Quote#] AS NVARCHAR(255)) AS [Quote],
    [B_CW].[Order Date],
    [B_CW].[WO#] AS [WO],
    [B_CW].[Section],
    [B_CW].[SortSe],
    [B_CW].[Description],
    [B_CW].[Qty],
    [B_CW].[Price],
    [B_CW].[Cost],
    [B_CW].[Material Cost],
    [B_CW].[Labour Cost],
    [B_CW].[Made In Material],
    [B_CW].[Bought Out Material],
    [B_CW].[Weight],
    [B_CW].[Machine Shop],
    [B_CW].[Steel Kit],
    [B_CW].[Axles],
    [B_CW].[Stakes/Bunks],
    [B_CW].[Beam],
    [B_CW].[GNK],
    [B_CW].[Parts],
    [B_CW].[Line],
    [B_CW].[Step 1],
    [B_CW].[Step 2],
    [B_CW].[Blast],
    [B_CW].[Paint],
    [B_CW].[Finish],
    [B_CW].[Finish - GNK],
    [B_CW].[Final Assembly],
    [B_CW].[Tire Assembly],
    [B_CW].[Shipping],
    [B_CW].[Eng Hours],
    [B_CW].[Option Date],
    [B_CW].[Draw/Part#],
    [B_CW].[NPOInfo],
    [B_CW].[NPOPromptFlag],
    [B_CW].[NPOPrompt],
    [B_CW].[NPOConfigInfo],
    [B_CW].[NPOExpirationDate],
    [B_CW].[cw_timestamp],
    [B_CW].[US Price],
    [B_CW].[Are WO Specs Different?],
    [B_CW].[Galvanized]
FROM
	[BWSdb].[dbo].[Custom Work] [B_CW] WITH (NOLOCK)
WHERE
	CAST([B_CW].[Quote#] AS NVARCHAR(255)) = '31455'
UNION ALL (
	SELECT 
		[S_CW].[ID],
		[S_CW].[Quote Date],
		[S_CW].[SGQuote],
		[S_CW].[Order Date],
		[S_CW].[WO#],
		[S_CW].[Section],
		[S_CW].[SortSe],
		[S_CW].[Description],
		[S_CW].[Qty],
		[S_CW].[Price],
		[S_CW].[Cost],
		[S_CW].[Material Cost],
		[S_CW].[Labour Cost],
		[S_CW].[Made In Material],
		[S_CW].[Bought Out Material],
		[S_CW].[Weight],
		[S_CW].[Machine Shop],
		[S_CW].[Steel Kit],
		[S_CW].[Axles],
		[S_CW].[Stakes/Bunks],
		[S_CW].[Beam],
		[S_CW].[GNK],
		[S_CW].[Parts],
		[S_CW].[Line],
		[S_CW].[Step 1],
		[S_CW].[Step 2],
		[S_CW].[Blast],
		[S_CW].[Paint],
		[S_CW].[Finish],
		[S_CW].[Finish - GNK],
		[S_CW].[Final Assembly],
		[S_CW].[Tire Assembly],
		[S_CW].[Shipping],
		[S_CW].[Eng Hours],
		[S_CW].[Option Date],
		[S_CW].[Draw/Part#],
		[S_CW].[NPOInfo],
		[S_CW].[NPOPromptFlag],
		[S_CW].[NPOPrompt],
		[S_CW].[NPOConfigInfo],
		[S_CW].[NPOExpirationDate],
		[S_CW].[cw_timestamp],
		[S_CW].[US Price],
		[S_CW].[Are WO Specs Different?],
		NULL AS [Galvanized]
	FROM
		[BWSdb].[dbo].[Custom WorkV2] [S_CW] WITH (NOLOCK)	
	WHERE
		CAST([S_CW].[SGQuote] AS NVARCHAR(255)) = '31455'
)
