SELECT 
	'BWS' AS [Company],
	[B_OO].[ID],
    [B_OO].[Quote Date],
    [B_OO].[Order Date],
    [B_OO].[WO#],
    CAST([B_OO].[Quote#] AS NVARCHAR(255)) AS [Quote],
    [B_OO].[Option No],
    [B_OO].[Price],
    [B_OO].[Qty],
    [B_OO].[Sections],
    [B_OO].[Description],
    [B_OO].[Comments],
    [B_OO].[Weight],
    [B_OO].[Cost],
    [B_OO].[Material Cost],
    [B_OO].[Machine Shop],
    [B_OO].[Steel Kit],
    [B_OO].[Axles],
    [B_OO].[Stakes/Bunks],
    [B_OO].[Beam],
    [B_OO].[GNK],
    [B_OO].[Parts],
    [B_OO].[Line],
    [B_OO].[Step 1],
    [B_OO].[Step 2],
    [B_OO].[Blast],
    [B_OO].[Paint],
    [B_OO].[Finish],
    [B_OO].[Finish - GNK],
    [B_OO].[Final Assembly],
    [B_OO].[Tire Assembly],
    [B_OO].[Shipping],
    [B_OO].[Start Date],
    [B_OO].[End Date],
    [B_OO].[SortSe],
    [B_OO].[Width],
    [B_OO].[Spread],
    [B_OO].[Draw/Part#],
    [B_OO].[OptionInfo],
    [B_OO].[OptionPromptFlag],
    [B_OO].[OptionPrompt],
    [B_OO].[OptionConfigInfo],
    [B_OO].[ordopt_timestamp],
    [B_OO].[Are WO Specs Different?],
    [B_OO].[Comments V2],
    [B_OO].[Galvanized],
    [B_OO].[Sections_French],
    [B_OO].[Description_French],
    [B_OO].[OptionInfo_French],
    [B_OO].[OptionPrompt_French]
FROM
	[BWSdb].[dbo].[Order Options] [B_OO] WITH (NOLOCK)
WHERE
    CAST([B_OO].[Quote#] AS NVARCHAR(255)) = '31455'

UNION ALL (
	SELECT 
		'STG' AS [Company],
		[S_OO].[ID],
		[S_OO].[Quote Date],
		[S_OO].[Order Date],
		[S_OO].[WO#],
		[S_OO].[SGQuote],
		[S_OO].[Option No],
		[S_OO].[Price],
		[S_OO].[Qty],
		[S_OO].[Sections],
		[S_OO].[Description],
		[S_OO].[Comments],
		[S_OO].[Weight],
		[S_OO].[Cost],
		[S_OO].[Material Cost],
		[S_OO].[Machine Shop],
		[S_OO].[Steel Kit],
		[S_OO].[Axles],
		[S_OO].[Stakes/Bunks],
		[S_OO].[Beam],
		[S_OO].[GNK],
		[S_OO].[Parts],
		[S_OO].[Line],
		[S_OO].[Step 1],
		[S_OO].[Step 2],
		[S_OO].[Blast],
		[S_OO].[Paint],
		[S_OO].[Finish],
		[S_OO].[Finish - GNK],
		[S_OO].[Final Assembly],
		[S_OO].[Tire Assembly],
		[S_OO].[Shipping],
		[S_OO].[Start Date],
		[S_OO].[End Date],
		[S_OO].[SortSe],
		[S_OO].[Width],
		[S_OO].[Spread],
		[S_OO].[Draw/Part#],
		[S_OO].[OptionInfo],
		[S_OO].[OptionPromptFlag],
		[S_OO].[OptionPrompt],
		[S_OO].[OptionConfigInfo],
		[S_OO].[ordopt_timestamp],
		[S_OO].[Are WO Specs Different?],
		[S_OO].[Comments V2],
		[S_OO].[Galvanized],
		NULL AS [Sections_French],
		NULL AS [Description_French],
		NULL AS [OptionInfo_French],
		NULL AS [OptionPrompt_French]
	FROM
		[BWSdb].[dbo].[Order OptionsV2] [S_OO] WITH (NOLOCK)
	WHERE
		CAST([S_OO].[SGQuote] AS NVARCHAR(255)) = '31455'

)