USE [BWSdb]
GO

-- ================================================
-- Template generated from Template Explorer using:
-- Create Trigger (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- See additional Create Trigger templates for more
-- examples of different Trigger statements.
--
-- This block of comments will not be included in
-- the definition of the function.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE TRIGGER  [dbo].[tr_UpdateOrdersHistory]
   ON [OrdersV2]
   --BEFORE
   AFTER
   --INSTEAD OF
   INSERT
   , DELETE
   , UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	IF TRIGGER_NESTLEVEL() < 2 BEGIN
	
		DECLARE @user NVARCHAR(20);
		DECLARE @activity NVARCHAR(20);

		-- Insert statements for trigger here
		IF EXISTS (SELECT * FROM inserted) AND EXISTS (SELECT * FROM deleted) BEGIN
			SET @activity = 'UPDATE';
			SET @user = SYSTEM_USER;

			
		INSERT INTO 
			[dbo].[OrdersV2 History] (
				[OrderID]
           ,[Action]
           ,[When]
           ,[User]
           ,[SGQuote]
           ,[Quote Date]
           ,[Order Date]
           ,[WO#]
           ,[Sales Order#]
           ,[Model No]
           ,[Width]
           ,[Spread]
           ,[DealerID]
           ,[Sale PersonID]
           ,[Price]
           ,[Prom Drawing]
           ,[Special Instructions]
           ,[Date Declined]
           ,[Decline/Rejected]
           ,[Serial Number]
           ,[Available Date]
           ,[Delivery Date]
           ,[Requested Delivery Date]
           ,[Finish Date]
           ,[Purchase Order]
           ,[PO Date]
           ,[PayID]
           ,[Volume Discount]
           ,[Program Discount]
           ,[Discount1_Name]
           ,[Discount1_Type]
           ,[Discount1]
           ,[Discount2_Name]
           ,[Discount2_Type]
           ,[Discount2]
           ,[Discount3_Name]
           ,[Discount3_Type]
           ,[Discount3]
           ,[Est Pro Date]
           ,[Notes]
           --,[EngNotes]
           ,[CarrierID]
           ,[CustID]
           ,[US Sale]
           ,[Shipped Date]
           ,[GL Override Date]
           ,[FE Rate]
           ,[PDD]
           ,[Deck Length]
           ,[Invoice #]
           ,[Date Registered]
           ,[Date In Service]
           ,[Invoice Date]
           ,[Date Requested]
           ,[GVWR]
           ,[Tare]
           ,[Selection]
           ,[Warranty]
           ,[BWSPaid]
           ,[BWSPaidDate]
           ,[CommPaid]
           ,[CommPaidDate]
           ,[ModifiedBy]
           ,[Lead Date]
           ,[Lead Source]
           ,[LeadID]
           ,[DealerBranchID]
           ,[DealerSalesPersonID]
           ,[DataEntryCheck]
           ,[DataEntryUser]
           ,[FinishedGoodsDealerLocID]
           ,[WO Reviewed]
           ,[WO Review Date]
           ,[Follow Up Date]
           ,[MSOIsDifferent]
           ,[MSOLocID]
           ,[EstInvDateOverride]
           ,[Estimated Invoice Date]
           ,[AdditionalPricingInfo]
           ,[Slot#]
           ,[TempModel?]
           ,[HighRiskUnit]
           --,[EngNotes V2]
           ,[CompanyID]
           ,[Customer WO#]
           ,[PriceSecured]
           ,[DateSecured]
           ,[SecuredBy]
           ,[InternalSalesComments]
           ,[InternalSalesCommentDate]
           ,[InternalSalesCommenter]
           ,[DiscountSetDate]
           ,[DiscountSetBy]
           ,[ProductID]
           ,[DiscountID]
           ,[DateLastQuoteReport]
           ,[JobAvailableLine]
           ,[JobAvailableScheduled]
           ,[JobAvailableScheduledBy]
			   )
     SELECT
			[OrderID]
			,@activity
			,GETDATE()
			,@user
			,[SGQuote]
		  ,[Quote Date]
		  ,[Order Date]
		  ,[WO#]
		  ,[Sales Order#]
		  ,[Model No]
		  ,[Width]
		  ,[Spread]
		  ,[DealerID]
		  ,[Sale PersonID]
		  ,[Price]
		  ,[Prom Drawing]
		  ,[Special Instructions]
		  ,[Date Declined]
		  ,[Decline/Rejected]
		  ,[Serial Number]
		  ,[Available Date]
		  ,[Delivery Date]
		  ,[Requested Delivery Date]
		  ,[Finish Date]
		  ,[Purchase Order]
		  ,[PO Date]
		  ,[PayID]
		  ,[Volume Discount]
		  ,[Program Discount]
		  ,[Discount1_Name]
		  ,[Discount1_Type]
		  ,[Discount1]
		  ,[Discount2_Name]
		  ,[Discount2_Type]
		  ,[Discount2]
		  ,[Discount3_Name]
		  ,[Discount3_Type]
		  ,[Discount3]
		  ,[Est Pro Date]
		  ,[Notes]
		  --,[EngNotes]
		  ,[CarrierID]
		  ,[CustID]
		  ,[US Sale]
		  ,[Shipped Date]
		  ,[GL Override Date]
		  ,[FE Rate]
		  ,[PDD]
		  ,[Deck Length]
		  ,[Invoice #]
		  ,[Date Registered]
		  ,[Date In Service]
		  ,[Invoice Date]
		  ,[Date Requested]
		  ,[GVWR]
		  ,[Tare]
		  ,[Selection]
		  ,[Warranty]
		  ,[BWSPaid]
		  ,[BWSPaidDate]
		  ,[CommPaid]
		  ,[CommPaidDate]
		  ,[ModifiedBy]
		  ,[Lead Date]
		  ,[Lead Source]
		  ,[LeadID]
		  ,[DealerBranchID]
		  ,[DealerSalesPersonID]
		  ,[DataEntryCheck]
		  ,[DataEntryUser]
		  ,[FinishedGoodsDealerLocID]
		  ,[WO Reviewed]
		  ,[WO Review Date]
		  ,[Follow Up Date]
		  ,[MSOIsDifferent]
		  ,[MSOLocID]
		  ,[EstInvDateOverride]
		  ,[Estimated Invoice Date]
		  ,[AdditionalPricingInfo]
		  ,[Slot#]
		  ,[TempModel?]
		  ,[HighRiskUnit]
		  --,[EngNotes V2]
		  ,[CompanyID]
		  ,[Customer WO#]
		  ,[PriceSecured]
		  ,[DateSecured]
		  ,[SecuredBy]
		  ,[InternalSalesComments]
		  ,[InternalSalesCommentDate]
		  ,[InternalSalesCommenter]
		  ,[DiscountSetDate]
		  ,[DiscountSetBy]
		  ,[ProductID]
		  ,[DiscountID]
		  ,[DateLastQuoteReport]
		  ,[JobAvailableLine]
		  ,[JobAvailableScheduled]
		  ,[JobAvailableScheduledBy]
	  FROM 
		INSERTED [I]

		END
		IF EXISTS (SELECT * FROM inserted) AND NOT EXISTS (SELECT * FROM deleted) BEGIN
			SET @activity = 'INSERT';
			SET @user = SYSTEM_USER;

			
		INSERT INTO 
			[dbo].[OrdersV2 History] (
				[OrderID]
           ,[Action]
           ,[When]
           ,[User]
           ,[SGQuote]
           ,[Quote Date]
           ,[Order Date]
           ,[WO#]
           ,[Sales Order#]
           ,[Model No]
           ,[Width]
           ,[Spread]
           ,[DealerID]
           ,[Sale PersonID]
           ,[Price]
           ,[Prom Drawing]
           ,[Special Instructions]
           ,[Date Declined]
           ,[Decline/Rejected]
           ,[Serial Number]
           ,[Available Date]
           ,[Delivery Date]
           ,[Requested Delivery Date]
           ,[Finish Date]
           ,[Purchase Order]
           ,[PO Date]
           ,[PayID]
           ,[Volume Discount]
           ,[Program Discount]
           ,[Discount1_Name]
           ,[Discount1_Type]
           ,[Discount1]
           ,[Discount2_Name]
           ,[Discount2_Type]
           ,[Discount2]
           ,[Discount3_Name]
           ,[Discount3_Type]
           ,[Discount3]
           ,[Est Pro Date]
           ,[Notes]
           --,[EngNotes]
           ,[CarrierID]
           ,[CustID]
           ,[US Sale]
           ,[Shipped Date]
           ,[GL Override Date]
           ,[FE Rate]
           ,[PDD]
           ,[Deck Length]
           ,[Invoice #]
           ,[Date Registered]
           ,[Date In Service]
           ,[Invoice Date]
           ,[Date Requested]
           ,[GVWR]
           ,[Tare]
           ,[Selection]
           ,[Warranty]
           ,[BWSPaid]
           ,[BWSPaidDate]
           ,[CommPaid]
           ,[CommPaidDate]
           ,[ModifiedBy]
           ,[Lead Date]
           ,[Lead Source]
           ,[LeadID]
           ,[DealerBranchID]
           ,[DealerSalesPersonID]
           ,[DataEntryCheck]
           ,[DataEntryUser]
           ,[FinishedGoodsDealerLocID]
           ,[WO Reviewed]
           ,[WO Review Date]
           ,[Follow Up Date]
           ,[MSOIsDifferent]
           ,[MSOLocID]
           ,[EstInvDateOverride]
           ,[Estimated Invoice Date]
           ,[AdditionalPricingInfo]
           ,[Slot#]
           ,[TempModel?]
           ,[HighRiskUnit]
           --,[EngNotes V2]
           ,[CompanyID]
           ,[Customer WO#]
           ,[PriceSecured]
           ,[DateSecured]
           ,[SecuredBy]
           ,[InternalSalesComments]
           ,[InternalSalesCommentDate]
           ,[InternalSalesCommenter]
           ,[DiscountSetDate]
           ,[DiscountSetBy]
           ,[ProductID]
           ,[DiscountID]
           ,[DateLastQuoteReport]
           ,[JobAvailableLine]
           ,[JobAvailableScheduled]
           ,[JobAvailableScheduledBy])
     SELECT
			[OrderID]
			,@activity
			,GETDATE()
			,@user
			,[SGQuote]
		  ,[Quote Date]
		  ,[Order Date]
		  ,[WO#]
		  ,[Sales Order#]
		  ,[Model No]
		  ,[Width]
		  ,[Spread]
		  ,[DealerID]
		  ,[Sale PersonID]
		  ,[Price]
		  ,[Prom Drawing]
		  ,[Special Instructions]
		  ,[Date Declined]
		  ,[Decline/Rejected]
		  ,[Serial Number]
		  ,[Available Date]
		  ,[Delivery Date]
		  ,[Requested Delivery Date]
		  ,[Finish Date]
		  ,[Purchase Order]
		  ,[PO Date]
		  ,[PayID]
		  ,[Volume Discount]
		  ,[Program Discount]
		  ,[Discount1_Name]
		  ,[Discount1_Type]
		  ,[Discount1]
		  ,[Discount2_Name]
		  ,[Discount2_Type]
		  ,[Discount2]
		  ,[Discount3_Name]
		  ,[Discount3_Type]
		  ,[Discount3]
		  ,[Est Pro Date]
		  ,[Notes]
		  --,[EngNotes]
		  ,[CarrierID]
		  ,[CustID]
		  ,[US Sale]
		  ,[Shipped Date]
		  ,[GL Override Date]
		  ,[FE Rate]
		  ,[PDD]
		  ,[Deck Length]
		  ,[Invoice #]
		  ,[Date Registered]
		  ,[Date In Service]
		  ,[Invoice Date]
		  ,[Date Requested]
		  ,[GVWR]
		  ,[Tare]
		  ,[Selection]
		  ,[Warranty]
		  ,[BWSPaid]
		  ,[BWSPaidDate]
		  ,[CommPaid]
		  ,[CommPaidDate]
		  ,[ModifiedBy]
		  ,[Lead Date]
		  ,[Lead Source]
		  ,[LeadID]
		  ,[DealerBranchID]
		  ,[DealerSalesPersonID]
		  ,[DataEntryCheck]
		  ,[DataEntryUser]
		  ,[FinishedGoodsDealerLocID]
		  ,[WO Reviewed]
		  ,[WO Review Date]
		  ,[Follow Up Date]
		  ,[MSOIsDifferent]
		  ,[MSOLocID]
		  ,[EstInvDateOverride]
		  ,[Estimated Invoice Date]
		  ,[AdditionalPricingInfo]
		  ,[Slot#]
		  ,[TempModel?]
		  ,[HighRiskUnit]
		  --,[EngNotes V2]
		  ,[CompanyID]
		  ,[Customer WO#]
		  ,[PriceSecured]
		  ,[DateSecured]
		  ,[SecuredBy]
		  ,[InternalSalesComments]
		  ,[InternalSalesCommentDate]
		  ,[InternalSalesCommenter]
		  ,[DiscountSetDate]
		  ,[DiscountSetBy]
		  ,[ProductID]
		  ,[DiscountID]
		  ,[DateLastQuoteReport]
		  ,[JobAvailableLine]
		  ,[JobAvailableScheduled]
		  ,[JobAvailableScheduledBy]
	  FROM 
		INSERTED [I]

		END
		IF EXISTS (SELECT * FROM deleted) AND NOT EXISTS (SELECT * FROM inserted) BEGIN 
			SET @activity = 'DELETE';
			SET @user = SYSTEM_USER;
		END

		
		INSERT INTO 
			[dbo].[OrdersV2 History] (
				[OrderID]
           ,[Action]
           ,[When]
           ,[User]
           ,[SGQuote]
           ,[Quote Date]
           ,[Order Date]
           ,[WO#]
           ,[Sales Order#]
           ,[Model No]
           ,[Width]
           ,[Spread]
           ,[DealerID]
           ,[Sale PersonID]
           ,[Price]
           ,[Prom Drawing]
           ,[Special Instructions]
           ,[Date Declined]
           ,[Decline/Rejected]
           ,[Serial Number]
           ,[Available Date]
           ,[Delivery Date]
           ,[Requested Delivery Date]
           ,[Finish Date]
           ,[Purchase Order]
           ,[PO Date]
           ,[PayID]
           ,[Volume Discount]
           ,[Program Discount]
           ,[Discount1_Name]
           ,[Discount1_Type]
           ,[Discount1]
           ,[Discount2_Name]
           ,[Discount2_Type]
           ,[Discount2]
           ,[Discount3_Name]
           ,[Discount3_Type]
           ,[Discount3]
           ,[Est Pro Date]
           ,[Notes]
           --,[EngNotes]
           ,[CarrierID]
           ,[CustID]
           ,[US Sale]
           ,[Shipped Date]
           ,[GL Override Date]
           ,[FE Rate]
           ,[PDD]
           ,[Deck Length]
           ,[Invoice #]
           ,[Date Registered]
           ,[Date In Service]
           ,[Invoice Date]
           ,[Date Requested]
           ,[GVWR]
           ,[Tare]
           ,[Selection]
           ,[Warranty]
           ,[BWSPaid]
           ,[BWSPaidDate]
           ,[CommPaid]
           ,[CommPaidDate]
           ,[ModifiedBy]
           ,[Lead Date]
           ,[Lead Source]
           ,[LeadID]
           ,[DealerBranchID]
           ,[DealerSalesPersonID]
           ,[DataEntryCheck]
           ,[DataEntryUser]
           ,[FinishedGoodsDealerLocID]
           ,[WO Reviewed]
           ,[WO Review Date]
           ,[Follow Up Date]
           ,[MSOIsDifferent]
           ,[MSOLocID]
           ,[EstInvDateOverride]
           ,[Estimated Invoice Date]
           ,[AdditionalPricingInfo]
           ,[Slot#]
           ,[TempModel?]
           ,[HighRiskUnit]
           --,[EngNotes V2]
           ,[CompanyID]
           ,[Customer WO#]
           ,[PriceSecured]
           ,[DateSecured]
           ,[SecuredBy]
           ,[InternalSalesComments]
           ,[InternalSalesCommentDate]
           ,[InternalSalesCommenter]
           ,[DiscountSetDate]
           ,[DiscountSetBy]
           ,[ProductID]
           ,[DiscountID]
           ,[DateLastQuoteReport]
           ,[JobAvailableLine]
           ,[JobAvailableScheduled]
           ,[JobAvailableScheduledBy])
     SELECT
			[OrderID]
			,@activity
			,GETDATE()
			,@user
			,[SGQuote]
		  ,[Quote Date]
		  ,[Order Date]
		  ,[WO#]
		  ,[Sales Order#]
		  ,[Model No]
		  ,[Width]
		  ,[Spread]
		  ,[DealerID]
		  ,[Sale PersonID]
		  ,[Price]
		  ,[Prom Drawing]
		  ,[Special Instructions]
		  ,[Date Declined]
		  ,[Decline/Rejected]
		  ,[Serial Number]
		  ,[Available Date]
		  ,[Delivery Date]
		  ,[Requested Delivery Date]
		  ,[Finish Date]
		  ,[Purchase Order]
		  ,[PO Date]
		  ,[PayID]
		  ,[Volume Discount]
		  ,[Program Discount]
		  ,[Discount1_Name]
		  ,[Discount1_Type]
		  ,[Discount1]
		  ,[Discount2_Name]
		  ,[Discount2_Type]
		  ,[Discount2]
		  ,[Discount3_Name]
		  ,[Discount3_Type]
		  ,[Discount3]
		  ,[Est Pro Date]
		  ,[Notes]
		  --,[EngNotes]
		  ,[CarrierID]
		  ,[CustID]
		  ,[US Sale]
		  ,[Shipped Date]
		  ,[GL Override Date]
		  ,[FE Rate]
		  ,[PDD]
		  ,[Deck Length]
		  ,[Invoice #]
		  ,[Date Registered]
		  ,[Date In Service]
		  ,[Invoice Date]
		  ,[Date Requested]
		  ,[GVWR]
		  ,[Tare]
		  ,[Selection]
		  ,[Warranty]
		  ,[BWSPaid]
		  ,[BWSPaidDate]
		  ,[CommPaid]
		  ,[CommPaidDate]
		  ,[ModifiedBy]
		  ,[Lead Date]
		  ,[Lead Source]
		  ,[LeadID]
		  ,[DealerBranchID]
		  ,[DealerSalesPersonID]
		  ,[DataEntryCheck]
		  ,[DataEntryUser]
		  ,[FinishedGoodsDealerLocID]
		  ,[WO Reviewed]
		  ,[WO Review Date]
		  ,[Follow Up Date]
		  ,[MSOIsDifferent]
		  ,[MSOLocID]
		  ,[EstInvDateOverride]
		  ,[Estimated Invoice Date]
		  ,[AdditionalPricingInfo]
		  ,[Slot#]
		  ,[TempModel?]
		  ,[HighRiskUnit]
		  --,[EngNotes V2]
		  ,[CompanyID]
		  ,[Customer WO#]
		  ,[PriceSecured]
		  ,[DateSecured]
		  ,[SecuredBy]
		  ,[InternalSalesComments]
		  ,[InternalSalesCommentDate]
		  ,[InternalSalesCommenter]
		  ,[DiscountSetDate]
		  ,[DiscountSetBy]
		  ,[ProductID]
		  ,[DiscountID]
		  ,[DateLastQuoteReport]
		  ,[JobAvailableLine]
		  ,[JobAvailableScheduled]
		  ,[JobAvailableScheduledBy]
	  FROM 
		DELETED [D]

	END
END
GO