USE [BWSdb]
GO

/****** Object:  View [dbo].[v_SAL_OrdersPricingV2]    Script Date: 2024-10-23 12:54:09 PM ******/

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- 2024-10-22 2100 - Avery Briggs - View of all Stargate WOs with the steps for quote cost calculations broken down. [NetCost] will be the total on the quote. Works for both US and CDN sales.
-- 2024-10-23 1329 - Avery Briggs - Added considerations for US pricing to be converted to CDN


ALTER VIEW [dbo].[v_SAL_OrdersPricingV2]
AS


SELECT
	[SGQuote]
	,[WO#]
	,[US Sale]
	,[BasePrice]
	,[SumOfOptionPrice]
	,[SumOfNPOPrice]
	,[Discount1]
	,[Discount1_Name]
	,[Discount1_Type]
	,[Discount2]
	,[Discount2_Name]
	,[Discount2_Type]
	,[Discount3]
	,[Discount3_Name]
	,[Discount3_Type]
	,[Volume Discount]
	,[Program Discount]
	,[Total]
	,[TotalCDN]
	,[D3]
	,[VolDis]
	,[VolDisCDN]
	,[D3SubTtl]
	,[D3SubTtlCDN]
	,[SubTtl]
	,[SubTtlCDN]
	,[ProDis]
	,[ProDisCDN]
	,[PDSubTtl]
	,[PDSubTtlCDN]
	,[D1]
	,[D1CDN]
	,[PDSubTtl] + [D1] AS [NetCost]
	,[PDSubTtlCDN] + [D1CDN] AS [NetCostCDN]
FROM (
	SELECT
		[SGQuote]
		,[WO#]
		,[US Sale]
		,[BasePrice]
		,[SumOfOptionPrice]
		,[SumOfNPOPrice]
		,[Discount1]
		,[Discount1_Name]
		,[Discount1_Type]
		,[Discount2]
		,[Discount2_Name]
		,[Discount2_Type]
		,[Discount3]
		,[Discount3_Name]
		,[Discount3_Type]
		,[Volume Discount]
		,[Program Discount]
		,[Total]
		,[TotalCDN]
		,[D3]
		,[VolDis]
		,[VolDisCDN]
		,[D3SubTtl]
		,[D3SubTtlCDN]
		,[SubTtl]
		,[SubTtlCDN]
		,[ProDis]
		,[ProDisCDN]
		,[PDSubTtl]
		,[PDSubTtlCDN]
		,(CASE WHEN [Discount1_Type] = 'Fixed' THEN [Discount1] ELSE (CASE WHEN [Discount1_Type] = 'Percent' THEN ([SubTtl] + [ProDis]) * ([Discount1] * -1) ELSE 0 END) END) AS [D1]
		,(CASE WHEN [Discount1_Type] = 'Fixed' THEN [Discount1] ELSE (CASE WHEN [Discount1_Type] = 'Percent' THEN ([SubTtlCDN] + [ProDisCDN]) * ([Discount1] * -1) ELSE 0 END) END) AS [D1CDN]
	FROM (
		SELECT
			[SGQuote]
			,[WO#]
			,[US Sale]
			,[BasePrice]
			,[SumOfOptionPrice]
			,[SumOfNPOPrice]
			,[Discount1]
			,[Discount1_Name]
			,[Discount1_Type]
			,[Discount2]
			,[Discount2_Name]
			,[Discount2_Type]
			,[Discount3]
			,[Discount3_Name]
			,[Discount3_Type]
			,[Volume Discount]
			,[Program Discount]
			,[Total]
			,[TotalCDN]
			,[D3]
			,[VolDis]
			,[VolDisCDN]
			,[D3SubTtl]
			,[D3SubTtlCDN]
			,[SubTtl]
			,[SubTtlCDN]
			,[ProDis]
			,[ProDisCDN]
			,[SubTtl] + [ProDis] AS [PDSubTtl]
			,[SubTtlCDN] + [ProDisCDN] AS [PDSubTtlCDN]
		FROM (
			SELECT
				[SGQuote]
				,[WO#]
				,[US Sale]
				,[BasePrice]
				,[SumOfOptionPrice]
				,[SumOfNPOPrice]
				,[Discount1]
				,[Discount1_Name]
				,[Discount1_Type]
				,[Discount2]
				,[Discount2_Name]
				,[Discount2_Type]
				,[Discount3]
				,[Discount3_Name]
				,[Discount3_Type]
				,[Volume Discount]
				,[Program Discount]
				,[Total]
				,[TotalCDN]
				,[D3]
				,[VolDis]
				,[VolDisCDN]
				,[D3SubTtl]
				,[D3SubTtlCDN]
				,[SubTtl]
				,[SubTtlCDN]
				,[SubTtl] * ([Program Discount] * -1) AS [ProDis]
				,[SubTtlCDN] * ([Program Discount] * -1) AS [ProDisCDN]
			FROM (
				SELECT
					[SGQuote]
					,[WO#]
					,[US Sale]
					,[BasePrice]
					,[SumOfOptionPrice]
					,[SumOfNPOPrice]
					,[Discount1]
					,[Discount1_Name]
					,[Discount1_Type]
					,[Discount2]
					,[Discount2_Name]
					,[Discount2_Type]
					,[Discount3]
					,[Discount3_Name]
					,[Discount3_Type]
					,[Volume Discount]
					,[Program Discount]
					,[Total]
					,[TotalCDN]
					,[D3]
					,[VolDis]
					,[VolDisCDN]
					,[D3SubTtl]
					,[D3SubTtlCDN]
					,[D3SubTtl] + [VolDis] AS [SubTtl]
					,[D3SubTtlCDN] + [VolDisCDN] AS [SubTtlCDN]
				FROM (
					SELECT
						[SGQuote]
						,[WO#]
						,[US Sale]
						,[BasePrice]
						,[SumOfOptionPrice]
						,[SumOfNPOPrice]
						,[Discount1]
						,[Discount1_Name]
						,[Discount1_Type]
						,[Discount2]
						,[Discount2_Name]
						,[Discount2_Type]
						,[Discount3]
						,[Discount3_Name]
						,[Discount3_Type]
						,[Volume Discount]
						,[Program Discount]
						,[Total]
						,[TotalCDN]
						,[D3]
						,(CASE WHEN [D3] IS NULL THEN [Total] ELSE [Total] + [D3] END) * ([Volume Discount] * -1) AS [VolDis]
						,[Total] + [D3] AS [D3SubTtl]
						,(CASE WHEN [D3] IS NULL THEN [TotalCDN] ELSE [TotalCDN] + [D3] END) * ([Volume Discount] * -1) AS [VolDisCDN]
						,[TotalCDN] + [D3] AS [D3SubTtlCDN]
					FROM (
						SELECT
							[SGQuote]
							,[WO#]
							,[US Sale]
							,[BasePrice]
							,[SumOfOptionPrice]
							,[SumOfNPOPrice]
							,[Discount1]
							,[Discount1_Name]
							,[Discount1_Type]
							,[Discount2]
							,[Discount2_Name]
							,[Discount2_Type]
							,[Discount3]
							,[Discount3_Name]
							,[Discount3_Type]
							,[Volume Discount]
							,[Program Discount]
							,[Total]
							,[TotalCDN]
							,(CASE WHEN [Discount3_Type] = 'Fixed' THEN [Discount3] ELSE (CASE WHEN [Discount3_Type] = 'Percent' THEN [Total] * [Discount3] * -1 ELSE 0 END) END) AS [D3]
						FROM (
							SELECT
								[O2].[SGQuote]
								,[O2].[WO#]
								,[O2].[US Sale]
								,[O2].[Price] AS [BasePrice]
								,SUM([OO2].[Price]) AS [SumOfOptionPrice]
								,SUM([CW2].[Price]) AS [SumOfNPOPrice]
								,ISNULL([O2].[Discount1], 0) AS [Discount1]
								,[O2].[Discount1_Name]
								,[O2].[Discount1_Type]
								,ISNULL([O2].[Discount2], 0) AS [Discount2]
								,[O2].[Discount2_Name]
								,[O2].[Discount2_Type]
								,ISNULL([O2].[Discount3], 0) AS [Discount3]
								,[O2].[Discount3_Name]
								,[O2].[Discount3_Type]
								,ISNULL([O2].[Volume Discount], 0) AS [Volume Discount]
								,ISNULL([O2].[Program Discount], 0) AS [Program Discount]
								,[O2].[Price] + [OO2].[Price] + (CASE WHEN [O2].[US Sale] = 1 THEN [CW2].[US Price] ELSE [CW2].[Price] END) AS [Total]
								,[SM].[ExchangeRate] * ([O2].[Price] + [OO2].[Price] + (CASE WHEN [O2].[US Sale] = 1 THEN [CW2].[US Price] ELSE [CW2].[Price] END)) AS [TotalCDN]
							FROM
								[BWSdb].[dbo].[OrdersV2] [O2]
							INNER JOIN
								[BWSdb].[dbo].[ProductsV2] [P2]
							ON
								[O2].[ProductID] = [P2].[IDTrailer]
							INNER JOIN
								[SysproCompanyS].[dbo].[SorMaster] [SM]
							ON
								[O2].[Sales Order#] = [SM].[SalesOrder]
							INNER JOIN (
								SELECT
									[Order OptionsV2].[SGQuote]
									,[Order OptionsV2].[WO#]
									,SUM([Order OptionsV2].[Qty] * [Order OptionsV2].[Price]) AS [Price]
								FROM
									[BWSdb].[dbo].[Order OptionsV2]
								GROUP BY
									[Order OptionsV2].[SGQuote]
									,[Order OptionsV2].[WO#]
							) AS [OO2]
							ON
								[O2].[SGQuote] = [OO2].[SGQuote]
							INNER JOIN(
								SELECT
									[Custom WorkV2].[SGQuote]
									,[Custom WorkV2].[WO#]
									,SUM(CASE WHEN [OrdersV2].[US Sale] = 1 THEN 0 ELSE [Custom WorkV2].[Price] END) AS [Price]
									,SUM(CASE WHEN [OrdersV2].[US Sale] = 1 THEN [Custom WorkV2].[US Price] ELSE 0 END) AS [US Price]
								FROM
									[BWSdb].[dbo].[Custom WorkV2]
								INNER JOIN
									[BWSdb].[dbo].[OrdersV2]
								ON
									[Custom WorkV2].[SGQuote] = [OrdersV2].[SGQuote]
								GROUP BY
									[Custom WorkV2].[SGQuote]
									,[Custom WorkV2].[WO#]
							) AS [CW2]
							ON
								[O2].[SGQuote] = [CW2].[SGQuote]
							GROUP BY
								[O2].[SGQuote]
								,[O2].[WO#]
								,[O2].[US Sale]
								,[O2].[Price]
								,[O2].[US Sale]
								,[OO2].[Price]
								,[CW2].[Price]
								,[CW2].[US Price]
								,[O2].[Discount1]
								,[O2].[Discount1_Name]
								,[O2].[Discount1_Type]
								,[O2].[Discount2]
								,[O2].[Discount2_Name]
								,[O2].[Discount2_Type]
								,[O2].[Discount3]
								,[O2].[Discount3_Name]
								,[O2].[Discount3_Type]
								,[O2].[Volume Discount]
								,[O2].[Program Discount]
								,[SM].[ExchangeRate]
						) AS [BaseOptNPO]
					) AS [Step1]
				) AS [Step2]
			) AS [Step3]
		) AS [Step4]
	) AS [Step5]
) AS [Step6]
;

GO


