USE BWSdb
GO

-- SELECTING PRIMARY KEY FROM TABLE

SELECT TOP 1 [COLUMN_NAME] AS [PK]
FROM INFORMATION_SCHEMA.COLUMNS
WHERE
	TABLE_NAME = 'OrdersV2'
	AND [IS_NULLABLE] = 'NO'
	AND [DATA_TYPE] = 'int'
	