EXEC [dbo].[sp_TopLevelWOReportJamieMulti] @WO='10014747', @INCOMPLETEONLY=0, @PARTCATEGORY='M;B;S', @OPERATION='1;4;5', @WAREHOUSE='04;06', @WORKCENTRE=NULL, @MACHINE='10';
EXEC [dbo].[sp_TopLevelWOReportJamieMulti] @WO='10014747', @INCOMPLETEONLY=0, @PARTCATEGORY='M;B;S', @OPERATION=NULL, @WAREHOUSE='04;06', @WORKCENTRE=NULL, @MACHINE=NULL;
EXEC [dbo].[sp_TopLevelWOReportJamieMulti] @WO='10014747', @INCOMPLETEONLY=0, @PARTCATEGORY='M;B;S', @OPERATION='10', @WAREHOUSE='04;06', @WORKCENTRE='A;T;P', @MACHINE='04;05';

EXEC [dbo].[sp_TopLevelWOReportJamieMulti] @WO='10014747', @INCOMPLETEONLY=0, @PARTCATEGORY='M;B;S', @OPERATION=NULL, @WAREHOUSE='04;06', @WORKCENTRE=NULL, @MACHINE=NULL;
EXEC [dbo].[sp_TopLevelWOReportJamieMulti] @WO='10014747', @INCOMPLETEONLY=0, @PARTCATEGORY='M;B;S', @OPERATION=NULL, @WAREHOUSE='00;06', @WORKCENTRE=NULL, @MACHINE=NULL;