USE BWSdb
GO

SELECT
	[UO].[TableOrderID] AS [OrdersTableOrderID]
	,[UO].[OriginTable] AS [OrdersOriginTable]
	,[UO].[QuoteNum] AS [OrdersQuoteNum]
	,[UO].[DateQuote] AS [OrdersDateQuote]
	,[UO].[DateOrder] AS [OrdersDateOrder]
	,[UO].[WONum] AS [OrdersWONum]
	,[UO].[SaledOrderNum] AS [OrdersSaledOrderNum]
	,[UO].[ModelNo] AS [OrdersModelNo]
	,[UO].[Width] AS [OrdersWidth]
	,[UO].[Spread] AS [OrdersSpread]
	,[UO].[DealerID] AS [OrdersDealerID]
	,[UO].[IDSalesPerson] AS [OrdersIDSalesPerson]
	,[UO].[Price] AS [OrdersPrice]
	,[UO].[PromoDrawing] AS [OrdersPromoDrawing]
	,[UO].[SpecialInstructions] AS [OrdersSpecialInstructions]
	,[UO].[DateDeclined] AS [OrdersDateDeclined]
	,[UO].[Decline_Rejected] AS [OrdersDecline_Rejected]
	,[UO].[SerialNumber] AS [OrdersSerialNumber]
	,[UO].[DateAvailable] AS [OrdersDateAvailable]
	,[UO].[DateDelivery] AS [OrdersDateDelivery]
	,[UO].[DateRequestedDelivery] AS [OrdersDateRequestedDelivery]
	,[UO].[DateFinish] AS [OrdersDateFinish]
	,[UO].[PurchaseOrder] AS [OrdersPurchaseOrder]
	,[UO].[DatePO] AS [OrdersDatePO]
	,[UO].[PayID] AS [OrdersPayID]
	,[UO].[VolumeDiscount] AS [OrdersVolumeDiscount]
	,[UO].[ProgramDiscount] AS [OrdersProgramDiscount]
	,[UO].[Discount1_Name] AS [OrdersDiscount1_Name]
	,[UO].[Discount1_Type] AS [OrdersDiscount1_Type]
	,[UO].[Discount1] AS [OrdersDiscount1]
	,[UO].[Discount2_Name] AS [OrdersDiscount2_Name]
	,[UO].[Discount2_Type] AS [OrdersDiscount2_Type]
	,[UO].[Discount2] AS [OrdersDiscount2]
	,[UO].[Discount3_Name] AS [OrdersDiscount3_Name]
	,[UO].[Discount3_Type] AS [OrdersDiscount3_Type]
	,[UO].[Discount3] AS [OrdersDiscount3]
	,[UO].[DateEstPro] AS [OrdersDateEstPro]
	,[UO].[Notes] AS [OrdersNotes]
	,[UO].[EngNotes] AS [OrdersEngNotes]
	,[UO].[CarrierID] AS [OrdersCarrierID]
	,[UO].[CustID] AS [OrdersCustID]
	,[UO].[USSale] AS [OrdersUSSale]
	,[UO].[DateShipped] AS [OrdersDateShipped]
	,[UO].[DateGLOverride] AS [OrdersDateGLOverride]
	,[UO].[FERate] AS [OrdersFERate]
	,[UO].[PDD] AS [OrdersPDD]
	,[UO].[DeckLength] AS [OrdersDeckLength]
	,[UO].[InvoiceNum] AS [OrdersInvoiceNum]
	,[UO].[DateRegistered] AS [OrdersDateRegistered]
	,[UO].[DateInService] AS [OrdersDateInService]
	,[UO].[DateInvoice] AS [OrdersDateInvoice]
	,[UO].[DateRequested] AS [OrdersDateRequested]
	,[UO].[GVWR] AS [OrdersGVWR]
	,[UO].[Tare] AS [OrdersTare]
	,[UO].[Selection] AS [OrdersSelection]
	,[UO].[Warranty] AS [OrdersWarranty]
	,[UO].[BWSPaid] AS [OrdersBWSPaid]
	,[UO].[BWSPaidDate] AS [OrdersBWSPaidDate]
	,[UO].[CommPaid] AS [OrdersCommPaid]
	,[UO].[CommPaidDate] AS [OrdersCommPaidDate]
	,[UO].[ts_timestamp] AS [Ordersts_timestamp]
	,[UO].[ModifiedBy] AS [OrdersModifiedBy]
	,[UO].[DateLead] AS [OrdersDateLead]
	,[UO].[LeadSource] AS [OrdersLeadSource]
	,[UO].[LeadID] AS [OrdersLeadID]
	,[UO].[DealerBranchID] AS [OrdersDealerBranchID]
	,[UO].[DealerSalesPersonID] AS [OrdersDealerSalesPersonID]
	,[UO].[DataEntryCheck] AS [OrdersDataEntryCheck]
	,[UO].[DataEntryUser] AS [OrdersDataEntryUser]
	,[UO].[FinishedGoodsDealerLocID] AS [OrdersFinishedGoodsDealerLocID]
	,[UO].[WOReviewed] AS [OrdersWOReviewed]
	,[UO].[DateWOReview] AS [OrdersDateWOReview]
	,[UO].[DateFollowUp] AS [OrdersDateFollowUp]
	,[UO].[MSOIsDifferent] AS [OrdersMSOIsDifferent]
	,[UO].[MSOLocID] AS [OrdersMSOLocID]
	,[UO].[EstInvDateOverride] AS [OrdersEstInvDateOverride]
	,[UO].[DateInvoiceEstimated] AS [OrdersDateInvoiceEstimated]
	,[UO].[AdditionalPricingInfo] AS [OrdersAdditionalPricingInfo]
	,[UO].[SlotNum] AS [OrdersSlotNum]
	,[UO].[TempModel] AS [OrdersTempModel]
	,[UO].[HighRiskUnit] AS [OrdersHighRiskUnit]
	,[UO].[EngNotesV2] AS [OrdersEngNotesV2]
	,[UO].[CompanyID] AS [OrdersCompanyID]
	,[UO].[CustomerWONum] AS [OrdersCustomerWONum]
	,[UO].[PriceSecured] AS [OrdersPriceSecured]
	,[UO].[DateSecured] AS [OrdersDateSecured]
	,[UO].[SecuredBy] AS [OrdersSecuredBy]
	,[UO].[InternalSalesComments] AS [OrdersInternalSalesComments]
	,[UO].[InternalSalesCommentDate] AS [OrdersInternalSalesCommentDate]
	,[UO].[InternalSalesCommenter] AS [OrdersInternalSalesCommenter]
	,[UO].[DateDiscountSet] AS [OrdersDateDiscountSet]
	,[UO].[DiscountSetBy] AS [OrdersDiscountSetBy]
	,[UO].[ProductID] AS [OrdersProductID]
	,[UO].[DiscountID] AS [OrdersDiscountID]

	,[AS].[
FROM
	[v_SFC_BWSUnionSTGOrders] AS [UO]
LEFT JOIN
	[SysproCompanyA].[dbo].[SorMaster] AS [AS]
ON
	[UO].[SaledOrderNum] = [AS].[SalesOrder]
	AND [UO].[OriginTable] = 'Orders'
LEFT JOIN
	[SysproCompanyS].[dbo].[SorMaster] AS [SS]
ON
	[UO].[SaledOrderNum] = [SS].[SalesOrder]
	AND [UO].[OriginTable] = 'OrdersV2'