
/****** Object:  View [dbo].[v_SFC_BWSUnionSTGOrders]    Script Date: 2023-11-21 1856 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/****** Script for SelectTopNRows command from SSMS  ******/

ALTER VIEW [dbo].[v_SFC_BWSUnionSTGOrders] AS
	SELECT
		'BWS' AS [OriginTable]
		,ROW_NUMBER() OVER(
			ORDER BY [Quote#]
		) AS [Orders_OrderID]
		,CAST([O].[Quote#] AS NVARCHAR(MAX)) AS [Orders_Quote]
		,[O].[Quote Date] AS [Orders_DateQuote]
		,[O].[Order Date] AS [Orders_DateOrder]
		,[O].[WO#] AS [Orders_WO]
		,[O].[Sales Order#] AS [Orders_SalesOrder]
		,[O].[Model No] AS [Orders_ModelNo]
		,[O].[Width] AS [Orders_Width]
		,[O].[Spread] AS [Orders_Spread]
		,[O].[DealerID] AS [Orders_DealerID]
		,[O].[Sale PersonID] AS [Orders_SalePersonID]
		,[O].[Price] AS [Orders_Price]
		,[O].[Prom Drawing] AS [Orders_PromDrawing]
		,[O].[Special Instructions] AS [Orders_SpecialInstructions]
		,[O].[Date Declined] AS [Orders_DateDeclined]
		,[O].[Decline/Rejected] AS [Orders_DeclineRejected]
		,[O].[Serial Number] AS [Orders_SerialNumber]
		,[O].[Available Date] AS [Orders_DateAvailable]
		,[O].[Delivery Date] AS [Orders_DateDelivery]
		,[O].[Requested Delivery Date] AS [Orders_DateRequestedDelivery]
		,[O].[Finish Date] AS [Orders_DateFinish]
		,[O].[Purchase Order] AS [Orders_PurchaseOrder]
		,[O].[PO Date] AS [Orders_DatePO]
		,[O].[PayID] AS [Orders_PayID]
		,[O].[Volume Discount] AS [Orders_VolumeDiscount]
		,[O].[Program Discount] AS [Orders_ProgramDiscount]
		,[O].[Discount1_Name] AS [Orders_Discount1_Name]
		,[O].[Discount1_Type] AS [Orders_Discount1_Type]
		,[O].[Discount1] AS [Orders_Discount1]
		,[O].[Discount2_Name] AS [Orders_Discount2_Name]
		,[O].[Discount2_Type] AS [Orders_Discount2_Type]
		,[O].[Discount2] AS [Orders_Discount2]
		,[O].[Discount3_Name] AS [Orders_Discount3_Name]
		,[O].[Discount3_Type] AS [Orders_Discount3_Type]
		,[O].[Discount3] AS [Orders_Discount3]
		,[O].[Est Pro Date] AS [Orders_DateEstPro]
		,[O].[Notes] AS [Orders_Notes]
		,[O].[EngNotes] AS [Orders_EngNotes]
		,[O].[CarrierID] AS [Orders_CarrierID]
		,[O].[CustID] AS [Orders_CustID]
		,[O].[US Sale] AS [Orders_USSale]
		,[O].[Shipped Date] AS [Orders_DateShipped]
		,[O].[GL Override Date] AS [Orders_DateGLOverride]
		,[O].[FE Rate] AS [Orders_FERate]
		,[O].[PDD] AS [Orders_PDD]
		,[O].[Deck Length] AS [Orders_DeckLength]
		,[O].[Invoice #] AS [Orders_Invoice]
		,[O].[Date Registered] AS [Orders_DateRegistered]
		,[O].[Date In Service] AS [Orders_DateInService]
		,[O].[Invoice Date] AS [Orders_DateInvoice]
		,[O].[Date Requested] AS [Orders_DateRequested]
		,[O].[GVWR] AS [Orders_GVWR]
		,[O].[Tare] AS [Orders_Tare]
		,[O].[Selection] AS [Orders_Selection]
		,[O].[Warranty] AS [Orders_Warranty]
		,[O].[BWSPaid] AS [Orders_BWSPaid]
		,[O].[BWSPaidDate] AS [Orders_DateBWSPaid]
		,[O].[CommPaid] AS [Orders_CommPaid]
		,[O].[CommPaidDate] AS [Orders_DateCommPaid]
		,[O].[ts_timestamp] AS [Orders_ts_timestamp]
		,[O].[ModifiedBy] AS [Orders_ModifiedBy]
		,[O].[Lead Date] AS [Orders_DateLead]
		,[O].[Lead Source] AS [Orders_LeadSource]
		,[O].[LeadID] AS [Orders_LeadID]
		,[O].[DealerBranchID] AS [Orders_DealerBranchID]
		,[O].[DealerSalesPersonID] AS [Orders_DealerSalesPersonID]
		,[O].[DataEntryCheck] AS [Orders_DataEntryCheck]
		,[O].[DataEntryUser] AS [Orders_DataEntryUser]
		,[O].[FinishedGoodsDealerLocID] AS [Orders_FinishedGoodsDealerLocID]
		,[O].[WO Reviewed] AS [Orders_WOReviewed]
		,[O].[WO Review Date] AS [Orders_DateWOReview]
		,[O].[Follow Up Date] AS [Orders_DateFollowUp]
		,[O].[MSOIsDifferent] AS [Orders_MSOIsDifferent]
		,[O].[MSOLocID] AS [Orders_MSOLocID]
		,[O].[EstInvDateOverride] AS [Orders_DateEstInvOverride]
		,[O].[Estimated Invoice Date] AS [Orders_DateEstimatedInvoice]
		,[O].[AdditionalPricingInfo] AS [Orders_AdditionalPricingInfo]
		,[O].[Slot#] AS [Orders_Slot]
		,[O].[TempModel?] AS [Orders_TempModel]
		,[O].[HighRiskUnit] AS [Orders_HighRiskUnit]
		,NULL AS [Orders_EngNotesV2]
		,[O].[CompanyID] AS [Orders_CompanyID]
		,[O].[Customer WO#] AS [Orders_CustomerWO]
		,[O].[PriceSecured] AS [Orders_PriceSecured]
		,[O].[DateSecured] AS [Orders_DateSecured]
		,[O].[SecuredBy] AS [Orders_SecuredBy]
		,[O].[InternalSalesComment] AS [Orders_InternalSalesComments]
		,[O].[InternalSalesCommentDate] AS [Orders_DateInternalSalesComment]
		,[O].[InternalSalesCommenter] AS [Orders_InternalSalesCommenter]
		,[O].[DiscountSetDate] AS [Orders_DateDiscountSet]
		,[O].[DiscountSetBy] AS [Orders_DiscountSetBy]
		,[O].[ProductID] AS [Orders_ProductID]
		,[O].[DiscountID] AS [Orders_DiscountID]
		,[D].[ID] AS [Dealers_ID]
		,[D].[COMPANY NAME] AS [Dealers_COMPANYNAME]
		,[D].[ADDRESS] AS [Dealers_ADDRESS]
		,[D].[CITY] AS [Dealers_CITY]
		,[D].[PROVINCE] AS [Dealers_PROVINCE]
		,[D].[POSTAL CODE] AS [Dealers_POSTALCODE]
		,[D].[PHONE] AS [Dealers_PHONE]
		,[D].[TOLL FREE] AS [Dealers_TOLLFREE]
		,[D].[FAX] AS [Dealers_FAX]
		,[D].[CONTACT] AS [Dealers_CONTACT]
		,[D].[CELL] AS [Dealers_CELL]
		,[D].[EMAIL] AS [Dealers_EMAIL]
		,[D].[DEALER NUMBER] AS [Dealers_DEALERNUMBER]
		,[D].[CURRENT DEALER] AS [Dealers_CURRENTDEALER]
		,[D].[CURRENT DEALER CDN] AS [Dealers_CURRENTDEALERCDN]
		,[D].[CURRENT DEALER US] AS [Dealers_CURRENTDEALERUS]
		,[D].[Invoice] AS [Dealers_Invoice]
		,[D].[Eastern Canada] AS [Dealers_EasternCanada]
		,[D].[Eastern US] AS [Dealers_EasternUS]
		,[D].[Central Canada] AS [Dealers_CentralCanada]
		,[D].[Central US] AS [Dealers_CentralUS]
		,[D].[Western Canada] AS [Dealers_WesternCanada]
		,[D].[Western US] AS [Dealers_WesternUS]
		,[D].[American] AS [Dealers_American]
		,[D].[Proprietary/Direct/Other] AS [Dealers_ProprietaryDirectOther]
		,[D].[Initials] AS [Dealers_Initials]
		,[D].[dealers_timestamp] AS [Dealers_dealers_timestamp]
		,[D].[DataEntryCheck] AS [Dealers_DataEntryCheck]
		,[D].[DataEntryUser] AS [Dealers_DataEntryUser]
		,[D].[DefaultPayID] AS [Dealers_DefaultPayID]
		,[D].[SendDealerStatusEmail?] AS [Dealers_SendDealerStatusEmail]
		,[D].[CompanyID] AS [Dealers_CompanyID]
		,[D].[SlotsRequestedPerMonth] AS [Dealers_SlotsRequestedPerMonth]
		,[P].[IDTrailer] AS [Products_IDTrailer]
		,[P].[Class] AS [Products_Class]
		,[P].[Proposed] AS [Products_Proposed]
		,[P].[Non-Current] AS [Products_Non-Current]
		,[P].[Model] AS [Products_Model]
		,[P].[Model No] AS [Products_ModelNo]
		,[P].[Top Level Part# (SYSPRO)] AS [Products_TopLevelPart(SYSPRO)]
		,[P].[Grouping] AS [Products_Grouping]
		,[P].[Start Date] AS [Products_DateStart]
		,[P].[End Date] AS [Products_DateEnd]
		,[P].[Price] AS [Products_Price]
		,[P].[Weight] AS [Products_Weight]
		,[P].[Make] AS [Products_Make]
		,[P].[NVIS] AS [Products_NVIS]
		,[P].[Promo Drawing] AS [Products_PromoDrawing]
		,[P].[Width] AS [Products_Width]
		,[P].[Spread] AS [Products_Spread]
		,[P].[Deck Length] AS [Products_DeckLength]
		,[P].[Days] AS [Products_Days]
		,[P].[GN] AS [Products_GN]
		,[P].[Paint] AS [Products_Paint]
		,[P].[Finish] AS [Products_Finish]
		,[P].[S/NL1] AS [Products_SNL1]
		,[P].[S/NL2] AS [Products_SNL2]
		,[P].[S/NT1] AS [Products_SNT1]
		,[P].[S/NT2] AS [Products_SNT2]
		,[P].[S/NAxles] AS [Products_SNAxles]
		,[P].[Selection] AS [Products_Selection]
		,[P].[EffComDate] AS [Products_DateEffCom]
		,[P].[ComRate] AS [Products_ComRate]
		,[P].[LastCostUpdate] AS [Products_LastCostUpdate]
		,[P].[LCUInitials] AS [Products_LCUInitials]
		,[P].[QR_Discount1] AS [Products_QR_Discount1]
		,[P].[QR_Discount2] AS [Products_QR_Discount2]
		,[P].[QR_Discount3] AS [Products_QR_Discount3]
		,[P].[product_timestamp] AS [Products_product_timestamp]
		,[P].[QR_ExpectedMargin] AS [Products_QR_ExpectedMargin]
		,[P].[tmpProductsClassesID] AS [Products_tmpProductsClassesID]
		,[P].[QRUS_Discount1] AS [Products_QRUS_Discount1]
		,[P].[QRUS_Discount2] AS [Products_QRUS_Discount2]
		,[P].[QRUS_Discount3] AS [Products_QRUS_Discount3]
		,[P].[QRUS_ExpectedMargin] AS [Products_QRUS_ExpectedMargin]
		,[P].[US Price] AS [Products_USPrice]
		,[P].[Customer] AS [Products_Customer]
		,[P].[Top Level Part# (SYSPRO 8)] AS [Products_TopLevelPart(SYSPRO8)]
		,[P].[Promo Drawing V2] AS [Products_PromoDrawingV2]
		,[P].[CompanyID] AS [Products_CompanyID]
	FROM
		[Orders] AS [O]
	LEFT JOIN
		[Dealers] AS [D]
	ON
		[O].[DealerID] = [D].[ID]
	LEFT JOIN
		[Products] AS [P]
	ON
		[O].[ProductID] = [P].[IDTrailer]

	UNION ALL

	SELECT
		'STG' AS [OriginTable]
		,[O2].[OrderID] AS [OrdersV2_OrderID]
		,[O2].[SGQuote] AS [OrdersV2_SGQuote]
		,[O2].[Quote Date] AS [OrdersV2_DateQuote]
		,[O2].[Order Date] AS [OrdersV2_DateOrder]
		,[O2].[WO#] AS [OrdersV2_WO]
		,[O2].[Sales Order#] AS [OrdersV2_SalesOrder]
		,[O2].[Model No] AS [OrdersV2_ModelNo]
		,[O2].[Width] AS [OrdersV2_Width]
		,[O2].[Spread] AS [OrdersV2_Spread]
		,[O2].[DealerID] AS [OrdersV2_DealerID]
		,[O2].[Sale PersonID] AS [OrdersV2_SalePersonID]
		,[O2].[Price] AS [OrdersV2_Price]
		,[O2].[Prom Drawing] AS [OrdersV2_PromDrawing]
		,[O2].[Special Instructions] AS [OrdersV2_SpecialInstructions]
		,[O2].[Date Declined] AS [OrdersV2_DateDeclined]
		,[O2].[Decline/Rejected] AS [OrdersV2_DeclineRejected]
		,[O2].[Serial Number] AS [OrdersV2_SerialNumber]
		,[O2].[Available Date] AS [OrdersV2_DateAvailable]
		,[O2].[Delivery Date] AS [OrdersV2_DateDelivery]
		,[O2].[Requested Delivery Date] AS [OrdersV2_DateRequestedDelivery]
		,[O2].[Finish Date] AS [OrdersV2_DateFinish]
		,[O2].[Purchase Order] AS [OrdersV2_PurchaseOrder]
		,[O2].[PO Date] AS [OrdersV2_DatePO]
		,[O2].[PayID] AS [OrdersV2_PayID]
		,[O2].[Volume Discount] AS [OrdersV2_VolumeDiscount]
		,[O2].[Program Discount] AS [OrdersV2_ProgramDiscount]
		,[O2].[Discount1_Name] AS [OrdersV2_Discount1_Name]
		,[O2].[Discount1_Type] AS [OrdersV2_Discount1_Type]
		,[O2].[Discount1] AS [OrdersV2_Discount1]
		,[O2].[Discount2_Name] AS [OrdersV2_Discount2_Name]
		,[O2].[Discount2_Type] AS [OrdersV2_Discount2_Type]
		,[O2].[Discount2] AS [OrdersV2_Discount2]
		,[O2].[Discount3_Name] AS [OrdersV2_Discount3_Name]
		,[O2].[Discount3_Type] AS [OrdersV2_Discount3_Type]
		,[O2].[Discount3] AS [OrdersV2_Discount3]
		,[O2].[Est Pro Date] AS [OrdersV2_DateEstPro]
		,[O2].[Notes] AS [OrdersV2_Notes]
		,[O2].[EngNotes] AS [OrdersV2_EngNotes]
		,[O2].[CarrierID] AS [OrdersV2_CarrierID]
		,[O2].[CustID] AS [OrdersV2_CustID]
		,[O2].[US Sale] AS [OrdersV2_USSale]
		,[O2].[Shipped Date] AS [OrdersV2_DateShipped]
		,[O2].[GL Override Date] AS [OrdersV2_DateGLOverride]
		,[O2].[FE Rate] AS [OrdersV2_FERate]
		,[O2].[PDD] AS [OrdersV2_PDD]
		,[O2].[Deck Length] AS [OrdersV2_DeckLength]
		,[O2].[Invoice #] AS [OrdersV2_Invoice]
		,[O2].[Date Registered] AS [OrdersV2_DateRegistered]
		,[O2].[Date In Service] AS [OrdersV2_DateInService]
		,[O2].[Invoice Date] AS [OrdersV2_DateInvoice]
		,[O2].[Date Requested] AS [OrdersV2_DateRequested]
		,[O2].[GVWR] AS [OrdersV2_GVWR]
		,[O2].[Tare] AS [OrdersV2_Tare]
		,[O2].[Selection] AS [OrdersV2_Selection]
		,[O2].[Warranty] AS [OrdersV2_Warranty]
		,[O2].[BWSPaid] AS [OrdersV2_BWSPaid]
		,[O2].[BWSPaidDate] AS [OrdersV2_DateBWSPaid]
		,[O2].[CommPaid] AS [OrdersV2_CommPaid]
		,[O2].[CommPaidDate] AS [OrdersV2_DateCommPaid]
		,[O2].[ts_timestamp] AS [OrdersV2_ts_timestamp]
		,[O2].[ModifiedBy] AS [OrdersV2_ModifiedBy]
		,[O2].[Lead Date] AS [OrdersV2_DateLead]
		,[O2].[Lead Source] AS [OrdersV2_LeadSource]
		,[O2].[LeadID] AS [OrdersV2_LeadID]
		,[O2].[DealerBranchID] AS [OrdersV2_DealerBranchID]
		,[O2].[DealerSalesPersonID] AS [OrdersV2_DealerSalesPersonID]
		,[O2].[DataEntryCheck] AS [OrdersV2_DataEntryCheck]
		,[O2].[DataEntryUser] AS [OrdersV2_DataEntryUser]
		,[O2].[FinishedGoodsDealerLocID] AS [OrdersV2_FinishedGoodsDealerLocID]
		,[O2].[WO Reviewed] AS [OrdersV2_WOReviewed]
		,[O2].[WO Review Date] AS [OrdersV2_DateWOReview]
		,[O2].[Follow Up Date] AS [OrdersV2_DateFollowUp]
		,[O2].[MSOIsDifferent] AS [OrdersV2_MSOIsDifferent]
		,[O2].[MSOLocID] AS [OrdersV2_MSOLocID]
		,[O2].[EstInvDateOverride] AS [OrdersV2_DateEstInvOverride]
		,[O2].[Estimated Invoice Date] AS [OrdersV2_DateEstimatedInvoice]
		,[O2].[AdditionalPricingInfo] AS [OrdersV2_AdditionalPricingInfo]
		,[O2].[Slot#] AS [OrdersV2_Slot]
		,[O2].[TempModel?] AS [OrdersV2_TempModel]
		,[O2].[HighRiskUnit] AS [OrdersV2_HighRiskUnit]
		,[O2].[EngNotes V2] AS [OrdersV2_EngNotesV2]
		,[O2].[CompanyID] AS [OrdersV2_CompanyID]
		,[O2].[Customer WO#] AS [OrdersV2_CustomerWO]
		,[O2].[PriceSecured] AS [OrdersV2_PriceSecured]
		,[O2].[DateSecured] AS [OrdersV2_DateSecured]
		,[O2].[SecuredBy] AS [OrdersV2_SecuredBy]
		,[O2].[InternalSalesComments] AS [OrdersV2_InternalSalesComments]
		,[O2].[InternalSalesCommentDate] AS [OrdersV2_DateInternalSalesComment]
		,[O2].[InternalSalesCommenter] AS [OrdersV2_InternalSalesCommenter]
		,[O2].[DiscountSetDate] AS [OrdersV2_DateDiscountSet]
		,[O2].[DiscountSetBy] AS [OrdersV2_DiscountSetBy]
		,[O2].[ProductID] AS [OrdersV2_ProductID]
		,[O2].[DiscountID] AS [OrdersV2_DiscountID]
		,[D2].[ID] AS [DealersV2_ID]
		,[D2].[COMPANY NAME] AS [DealersV2_COMPANYNAME]
		,[D2].[ADDRESS] AS [DealersV2_ADDRESS]
		,[D2].[CITY] AS [DealersV2_CITY]
		,[D2].[PROVINCE] AS [DealersV2_PROVINCE]
		,[D2].[POSTAL CODE] AS [DealersV2_POSTALCODE]
		,[D2].[PHONE] AS [DealersV2_PHONE]
		,[D2].[TOLL FREE] AS [DealersV2_TOLLFREE]
		,[D2].[FAX] AS [DealersV2_FAX]
		,[D2].[CONTACT] AS [DealersV2_CONTACT]
		,[D2].[CELL] AS [DealersV2_CELL]
		,[D2].[EMAIL] AS [DealersV2_EMAIL]
		,[D2].[DEALER NUMBER] AS [DealersV2_DEALERNUMBER]
		,[D2].[CURRENT DEALER] AS [DealersV2_CURRENTDEALER]
		,[D2].[CURRENT DEALER CDN] AS [DealersV2_CURRENTDEALERCDN]
		,[D2].[CURRENT DEALER US] AS [DealersV2_CURRENTDEALERUS]
		,[D2].[Invoice] AS [DealersV2_Invoice]
		,[D2].[Eastern Canada] AS [DealersV2_EasternCanada]
		,[D2].[Eastern US] AS [DealersV2_EasternUS]
		,[D2].[Central Canada] AS [DealersV2_CentralCanada]
		,[D2].[Central US] AS [DealersV2_CentralUS]
		,[D2].[Western Canada] AS [DealersV2_WesternCanada]
		,[D2].[Western US] AS [DealersV2_WesternUS]
		,[D2].[American] AS [DealersV2_American]
		,[D2].[Proprietary/Direct/Other] AS [DealersV2_ProprietaryDirectOther]
		,[D2].[Initials] AS [DealersV2_Initials]
		,[D2].[dealers_timestamp] AS [DealersV2_dealers_timestamp]
		,[D2].[DataEntryCheck] AS [DealersV2_DataEntryCheck]
		,[D2].[DataEntryUser] AS [DealersV2_DataEntryUser]
		,[D2].[DefaultPayID] AS [DealersV2_DefaultPayID]
		,[D2].[SendDealerStatusEmail?] AS [DealersV2_SendDealerStatusEmail]
		,[D2].[CompanyID] AS [DealersV2_CompanyID]
		,[D2].[SlotsRequestedPerMonth] AS [DealersV2_SlotsRequestedPerMonth]
		,[P2].[IDTrailer] AS [ProductsV2_IDTrailer]
		,[P2].[Class] AS [ProductsV2_Class]
		,[P2].[Proposed] AS [ProductsV2_Proposed]
		,[P2].[Non-Current] AS [ProductsV2_Non-Current]
		,[P2].[Model] AS [ProductsV2_Model]
		,[P2].[Model No] AS [ProductsV2_ModelNo]
		,[P2].[Top Level Part# (SYSPRO)] AS [ProductsV2_TopLevelPart(SYSPRO)]
		,[P2].[Grouping] AS [ProductsV2_Grouping]
		,[P2].[Start Date] AS [ProductsV2_DateStart]
		,[P2].[End Date] AS [ProductsV2_DateEnd]
		,[P2].[Price] AS [ProductsV2_Price]
		,[P2].[Weight] AS [ProductsV2_Weight]
		,[P2].[Make] AS [ProductsV2_Make]
		,[P2].[NVIS] AS [ProductsV2_NVIS]
		,[P2].[Promo Drawing] AS [ProductsV2_PromoDrawing]
		,[P2].[Width] AS [ProductsV2_Width]
		,[P2].[Spread] AS [ProductsV2_Spread]
		,[P2].[Deck Length] AS [ProductsV2_DeckLength]
		,[P2].[Days] AS [ProductsV2_Days]
		,[P2].[GN] AS [ProductsV2_GN]
		,[P2].[Paint] AS [ProductsV2_Paint]
		,[P2].[Finish] AS [ProductsV2_Finish]
		,[P2].[S/NL1] AS [ProductsV2_SNL1]
		,[P2].[S/NL2] AS [ProductsV2_SNL2]
		,[P2].[S/NT1] AS [ProductsV2_SNT1]
		,[P2].[S/NT2] AS [ProductsV2_SNT2]
		,[P2].[S/NAxles] AS [ProductsV2_SNAxles]
		,[P2].[Selection] AS [ProductsV2_Selection]
		,[P2].[EffComDate] AS [ProductsV2_DateEffCom]
		,[P2].[ComRate] AS [ProductsV2_ComRate]
		,[P2].[LastCostUpdate] AS [ProductsV2_LastCostUpdate]
		,[P2].[LCUInitials] AS [ProductsV2_LCUInitials]
		,[P2].[QR_Discount1] AS [ProductsV2_QR_Discount1]
		,[P2].[QR_Discount2] AS [ProductsV2_QR_Discount2]
		,[P2].[QR_Discount3] AS [ProductsV2_QR_Discount3]
		,[P2].[product_timestamp] AS [ProductsV2_product_timestamp]
		,[P2].[QR_ExpectedMargin] AS [ProductsV2_QR_ExpectedMargin]
		,[P2].[tmpProductsV2ClassesID] AS [ProductsV2_tmpProductsV2ClassesID]
		,[P2].[QRUS_Discount1] AS [ProductsV2_QRUS_Discount1]
		,[P2].[QRUS_Discount2] AS [ProductsV2_QRUS_Discount2]
		,[P2].[QRUS_Discount3] AS [ProductsV2_QRUS_Discount3]
		,[P2].[QRUS_ExpectedMargin] AS [ProductsV2_QRUS_ExpectedMargin]
		,[P2].[US Price] AS [ProductsV2_USPrice]
		,[P2].[Customer] AS [ProductsV2_Customer]
		,[P2].[Top Level Part# (SYSPRO 8)] AS [ProductsV2_TopLevelPart(SYSPRO8)]
		,[P2].[Promo Drawing V2] AS [ProductsV2_PromoDrawingV2]
		,[P2].[CompanyID] AS [ProductsV2_CompanyID]
	FROM
		[OrdersV2] AS [O2]
	LEFT JOIN
		[DealersV2] AS [D2]
	ON
		[O2].[DealerID] = [D2].[ID]
	LEFT JOIN
		[ProductsV2] AS [P2]
	ON
		[O2].[ProductID] = [P2].[IDTrailer]
;

GO