USE [BWSdb]
GO

/****** Object:  View [dbo].[v_SFC_BWSUnionSTGOrders]    Script Date: 2024-01-15 2:56:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO









--/****** Script for SelectTopNRows command from SSMS  ******/

ALTER VIEW [dbo].[v_SFC_BWSUnionSTGOrders] AS
--SELECT
--	*
--FROM (
	SELECT
		'BWS' AS [OriginTable]
		,ROW_NUMBER() OVER(
			ORDER BY [O].[Quote#]
		) AS [Orders_OrderID]
		,CAST([O].[Quote#] AS NVARCHAR(MAX)) AS [Orders_Quote]
		,[O].[Quote Date] AS [Orders_DateQuote]
		,[O].[Order Date] AS [Orders_DateOrder]
		,[O].[WO#] AS [Orders_WO]
		,[O].[Sales Order#] AS [Orders_SalesOrder]
		,[O].[Model No] AS [Orders_ModelNo]
		,[O].[Width] AS [Orders_Width]
		,[O].[Spread] AS [Orders_Spread]
		,[O].[DealerID] AS [Orders_DealerID]
		,[O].[Sale PersonID] AS [Orders_SalePersonID]
		,[O].[Price] AS [Orders_Price]
		,[O].[Prom Drawing] AS [Orders_PromDrawing]
		,[O].[Special Instructions] AS [Orders_SpecialInstructions]
		,[O].[Date Declined] AS [Orders_DateDeclined]
		,[O].[Decline/Rejected] AS [Orders_DeclineRejected]
		,[O].[Serial Number] AS [Orders_SerialNumber]
		,[O].[Available Date] AS [Orders_DateAvailable]
		,[O].[Delivery Date] AS [Orders_DateDelivery]
		,[O].[Requested Delivery Date] AS [Orders_DateRequestedDelivery]
		,[O].[Finish Date] AS [Orders_DateFinish]
		,[O].[Purchase Order] AS [Orders_PurchaseOrder]
		,[O].[PO Date] AS [Orders_DatePO]
		,[O].[PayID] AS [Orders_PayID]
		,[O].[Volume Discount] AS [Orders_VolumeDiscount]
		,[O].[Program Discount] AS [Orders_ProgramDiscount]
		,[O].[Discount1_Name] AS [Orders_Discount1_Name]
		,[O].[Discount1_Type] AS [Orders_Discount1_Type]
		,[O].[Discount1] AS [Orders_Discount1]
		,[O].[Discount2_Name] AS [Orders_Discount2_Name]
		,[O].[Discount2_Type] AS [Orders_Discount2_Type]
		,[O].[Discount2] AS [Orders_Discount2]
		,[O].[Discount3_Name] AS [Orders_Discount3_Name]
		,[O].[Discount3_Type] AS [Orders_Discount3_Type]
		,[O].[Discount3] AS [Orders_Discount3]
		,[O].[Est Pro Date] AS [Orders_DateEstPro]
		,[O].[Notes] AS [Orders_Notes]
		,CAST([O].[EngNotes] AS NVARCHAR(MAX)) AS [Orders_EngNotes]
		,[O].[CarrierID] AS [Orders_CarrierID]
		,[O].[CustID] AS [Orders_CustID]
		,[O].[US Sale] AS [Orders_USSale]
		,[O].[Shipped Date] AS [Orders_DateShipped]
		,[O].[GL Override Date] AS [Orders_DateGLOverride]
		,[O].[FE Rate] AS [Orders_FERate]
		,[O].[PDD] AS [Orders_PDD]
		,[O].[Deck Length] AS [Orders_DeckLength]
		,[O].[Invoice #] AS [Orders_Invoice]
		,[O].[Date Registered] AS [Orders_DateRegistered]
		,[O].[Date In Service] AS [Orders_DateInService]
		,[O].[Invoice Date] AS [Orders_DateInvoice]
		,[O].[Date Requested] AS [Orders_DateRequested]
		,[O].[GVWR] AS [Orders_GVWR]
		,[O].[Tare] AS [Orders_Tare]
		,[O].[Selection] AS [Orders_Selection]
		,[O].[Warranty] AS [Orders_Warranty]
		,[O].[BWSPaid] AS [Orders_BWSPaid]
		,[O].[BWSPaidDate] AS [Orders_DateBWSPaid]
		,[O].[CommPaid] AS [Orders_CommPaid]
		,[O].[CommPaidDate] AS [Orders_DateCommPaid]
		,[O].[ts_timestamp] AS [Orders_ts_timestamp]
		,[O].[ModifiedBy] AS [Orders_ModifiedBy]
		,[O].[Lead Date] AS [Orders_DateLead]
		,[O].[Lead Source] AS [Orders_LeadSource]
		,[O].[LeadID] AS [Orders_LeadID]
		,[O].[DealerBranchID] AS [Orders_DealerBranchID]
		,[O].[DealerSalesPersonID] AS [Orders_DealerSalesPersonID]
		,[O].[DataEntryCheck] AS [Orders_DataEntryCheck]
		,[O].[DataEntryUser] AS [Orders_DataEntryUser]
		,[O].[FinishedGoodsDealerLocID] AS [Orders_FinishedGoodsDealerLocID]
		,[O].[WO Reviewed] AS [Orders_WOReviewed]
		,[O].[WO Review Date] AS [Orders_DateWOReview]
		,[O].[Follow Up Date] AS [Orders_DateFollowUp]
		,[O].[MSOIsDifferent] AS [Orders_MSOIsDifferent]
		,[O].[MSOLocID] AS [Orders_MSOLocID]
		,[O].[EstInvDateOverride] AS [Orders_DateEstInvOverride]
		,[O].[Estimated Invoice Date] AS [Orders_DateEstimatedInvoice]
		,[O].[AdditionalPricingInfo] AS [Orders_AdditionalPricingInfo]
		,[O].[Slot#] AS [Orders_Slot]
		,[O].[TempModel?] AS [Orders_TempModel]
		,[O].[HighRiskUnit] AS [Orders_HighRiskUnit]
		,NULL AS [Orders_EngNotesV2]
		,[O].[CompanyID] AS [Orders_CompanyID]
		,[O].[Customer WO#] AS [Orders_CustomerWO]
		,[O].[PriceSecured] AS [Orders_PriceSecured]
		,[O].[DateSecured] AS [Orders_DateSecured]
		,[O].[SecuredBy] AS [Orders_SecuredBy]
		,[O].[InternalSalesComment] AS [Orders_InternalSalesComments]
		,[O].[InternalSalesCommentDate] AS [Orders_DateInternalSalesComment]
		,[O].[InternalSalesCommenter] AS [Orders_InternalSalesCommenter]
		,[O].[DiscountSetDate] AS [Orders_DateDiscountSet]
		,[O].[DiscountSetBy] AS [Orders_DiscountSetBy]
		,[O].[ProductID] AS [Orders_ProductID]
		,[O].[DiscountID] AS [Orders_DiscountID]
		,[O].[DateLastQuoteReport] AS [Orders_DateLastQuoteReport]
		,[O].[JobAvailableLine] AS [Orders_JobAvailableLine]
		,[O].[JobAvailableScheduled] AS [Orders_JobAvailableScheduled]
		,[O].[JobAvailableScheduledBy] AS [Orders_JobAvailableScheduledBy]

		,[D].[ID] AS [Dealers_ID]
		,[D].[COMPANY NAME] AS [Dealers_COMPANYNAME]
		,[D].[ADDRESS] AS [Dealers_ADDRESS]
		,[D].[CITY] AS [Dealers_CITY]
		,[D].[PROVINCE] AS [Dealers_PROVINCE]
		,[D].[POSTAL CODE] AS [Dealers_POSTALCODE]
		,[D].[PHONE] AS [Dealers_PHONE]
		,[D].[TOLL FREE] AS [Dealers_TOLLFREE]
		,[D].[FAX] AS [Dealers_FAX]
		,[D].[CONTACT] AS [Dealers_CONTACT]
		,[D].[CELL] AS [Dealers_CELL]
		,[D].[EMAIL] AS [Dealers_EMAIL]
		,[D].[DEALER NUMBER] AS [Dealers_DEALERNUMBER]
		,[D].[CURRENT DEALER] AS [Dealers_CURRENTDEALER]
		,[D].[CURRENT DEALER CDN] AS [Dealers_CURRENTDEALERCDN]
		,[D].[CURRENT DEALER US] AS [Dealers_CURRENTDEALERUS]
		,[D].[Invoice] AS [Dealers_Invoice]
		,[D].[Eastern Canada] AS [Dealers_EasternCanada]
		,[D].[Eastern US] AS [Dealers_EasternUS]
		,[D].[Central Canada] AS [Dealers_CentralCanada]
		,[D].[Central US] AS [Dealers_CentralUS]
		,[D].[Western Canada] AS [Dealers_WesternCanada]
		,[D].[Western US] AS [Dealers_WesternUS]
		,[D].[American] AS [Dealers_American]
		,[D].[Proprietary/Direct/Other] AS [Dealers_ProprietaryDirectOther]
		,[D].[Initials] AS [Dealers_Initials]
		,[D].[dealers_timestamp] AS [Dealers_dealers_timestamp]
		,[D].[DataEntryCheck] AS [Dealers_DataEntryCheck]
		,[D].[DataEntryUser] AS [Dealers_DataEntryUser]
		,[D].[DefaultPayID] AS [Dealers_DefaultPayID]
		,[D].[SendDealerStatusEmail?] AS [Dealers_SendDealerStatusEmail]
		,[D].[CompanyID] AS [Dealers_CompanyID]
		,[D].[SlotsRequestedPerMonth] AS [Dealers_SlotsRequestedPerMonth]

		,[P].[IDTrailer] AS [Products_IDTrailer]
		,[P].[Class] AS [Products_Class]
		,[P].[Proposed] AS [Products_Proposed]
		,[P].[Non-Current] AS [Products_Non-Current]
		,[P].[Model] AS [Products_Model]
		,[P].[Model No] AS [Products_ModelNo]
		,[P].[Top Level Part# (SYSPRO)] AS [Products_TopLevelPart(SYSPRO)]
		,[P].[Grouping] AS [Products_Grouping]
		,[P].[Start Date] AS [Products_DateStart]
		,[P].[End Date] AS [Products_DateEnd]
		,[P].[Price] AS [Products_Price]
		,[P].[Weight] AS [Products_Weight]
		,[P].[Make] AS [Products_Make]
		,[P].[NVIS] AS [Products_NVIS]
		,CAST([P].[Promo Drawing] AS NVARCHAR(MAX)) AS [Products_PromoDrawing]
		,[P].[Width] AS [Products_Width]
		,[P].[Spread] AS [Products_Spread]
		,[P].[Deck Length] AS [Products_DeckLength]
		,[P].[Days] AS [Products_Days]
		,[P].[GN] AS [Products_GN]
		,[P].[Paint] AS [Products_Paint]
		,[P].[Finish] AS [Products_Finish]
		,[P].[S/NL1] AS [Products_SNL1]
		,[P].[S/NL2] AS [Products_SNL2]
		,[P].[S/NT1] AS [Products_SNT1]
		,[P].[S/NT2] AS [Products_SNT2]
		,[P].[S/NAxles] AS [Products_SNAxles]
		,[P].[Selection] AS [Products_Selection]
		,[P].[EffComDate] AS [Products_DateEffCom]
		,[P].[ComRate] AS [Products_ComRate]
		,[P].[LastCostUpdate] AS [Products_LastCostUpdate]
		,[P].[LCUInitials] AS [Products_LCUInitials]
		,[P].[QR_Discount1] AS [Products_QR_Discount1]
		,[P].[QR_Discount2] AS [Products_QR_Discount2]
		,[P].[QR_Discount3] AS [Products_QR_Discount3]
		,[P].[product_timestamp] AS [Products_product_timestamp]
		,[P].[QR_ExpectedMargin] AS [Products_QR_ExpectedMargin]
		,[P].[tmpProductsClassesID] AS [Products_tmpProductsClassesID]
		,[P].[QRUS_Discount1] AS [Products_QRUS_Discount1]
		,[P].[QRUS_Discount2] AS [Products_QRUS_Discount2]
		,[P].[QRUS_Discount3] AS [Products_QRUS_Discount3]
		,[P].[QRUS_ExpectedMargin] AS [Products_QRUS_ExpectedMargin]
		,[P].[US Price] AS [Products_USPrice]
		,[P].[Customer] AS [Products_Customer]
		,[P].[Top Level Part# (SYSPRO 8)] AS [Products_TopLevelPart(SYSPRO8)]
		,[P].[Promo Drawing V2] AS [Products_PromoDrawingV2]
		,[P].[CompanyID] AS [Products_CompanyID]

		,[SS].[ID-SaleStaff] AS [SalesStaff_ID-SaleStaff]
		,[SS].[Initials] AS [SalesStaff_Initials]
		,[SS].[Sales Person] AS [SalesStaff_SalesPerson]
		,[SS].[Company] AS [SalesStaff_Company]
		,[SS].[DateCreated] AS [SalesStaff_DateCreated]
		,[SS].[Active] AS [SalesStaff_Active]
		,[SS].[DateActive] AS [SalesStaff_DateActive]
		,[SS].[DateInactive] AS [SalesStaff_DateInactive]
		,[SS].[Notes] AS [SalesStaff_Notes]

		,[SO].[SalesOrder] AS [SorMaster_SalesOrder]
		,[SO].[NextDetailLine] AS [SorMaster_NextDetailLine]
		,[SO].[OrderStatus] AS [SorMaster_OrderStatus]
		,[SO].[ActiveFlag] AS [SorMaster_ActiveFlag]
		,[SO].[CancelledFlag] AS [SorMaster_CancelledFlag]
		,[SO].[DocumentType] AS [SorMaster_DocumentType]
		,[SO].[Customer] AS [SorMaster_Customer]
		,[SO].[Salesperson] AS [SorMaster_Salesperson]
		,[SO].[CustomerPoNumber] AS [SorMaster_CustomerPoNumber]
		,[SO].[OrderDate] AS [SorMaster_DateOrder]
		,[SO].[EntrySystemDate] AS [SorMaster_DateEntrySystem]
		,[SO].[ReqShipDate] AS [SorMaster_DateReqShip]
		,[SO].[DateLastDocPrt] AS [SorMaster_DateLastDocPrt]
		,[SO].[ShippingInstrs] AS [SorMaster_ShippingInstrs]
		,[SO].[ShippingInstrsCod] AS [SorMaster_ShippingInstrsCod]
		,[SO].[AltShipAddrFlag] AS [SorMaster_AltShipAddrFlag]
		,[SO].[InvoiceCount] AS [SorMaster_InvoiceCount]
		,[SO].[InvTermsOverride] AS [SorMaster_InvTermsOverride]
		,[SO].[CreditAuthority] AS [SorMaster_CreditAuthority]
		,[SO].[Branch] AS [SorMaster_Branch]
		,[SO].[SpecialInstrs] AS [SorMaster_SpecialInstrs]
		,[SO].[EntInvoice] AS [SorMaster_EntInvoice]
		,[SO].[EntInvoiceDate] AS [SorMaster_DateEntInvoice]
		,[SO].[DiscPct1] AS [SorMaster_DiscPct1]
		,[SO].[DiscPct2] AS [SorMaster_DiscPct2]
		,[SO].[DiscPct3] AS [SorMaster_DiscPct3]
		,[SO].[OrderType] AS [SorMaster_OrderType]
		,[SO].[TaxExemptFlag] AS [SorMaster_TaxExemptFlag]
		,[SO].[Area] AS [SorMaster_Area]
		,[SO].[TaxExemptNumber] AS [SorMaster_TaxExemptNumber]
		,[SO].[TaxExemptOverride] AS [SorMaster_TaxExemptOverride]
		,[SO].[CashCredit] AS [SorMaster_CashCredit]
		,[SO].[Warehouse] AS [SorMaster_Warehouse]
		,[SO].[LastInvoice] AS [SorMaster_LastInvoice]
		,[SO].[ScheduledOrdFlag] AS [SorMaster_ScheduledOrdFlag]
		,[SO].[GstExemptFlag] AS [SorMaster_GstExemptFlag]
		,[SO].[GstExemptNum] AS [SorMaster_GstExemptNum]
		,[SO].[GstExemptORide] AS [SorMaster_GstExemptORide]
		,[SO].[IbtFlag] AS [SorMaster_IbtFlag]
		,[SO].[OrdAcknwPrinted] AS [SorMaster_OrdAcknwPrinted]
		,[SO].[DetCustMvmtReqd] AS [SorMaster_DetCustMvmtReqd]
		,[SO].[DocumentFormat] AS [SorMaster_DocumentFormat]
		,[SO].[FixExchangeRate] AS [SorMaster_FixExchangeRate]
		,[SO].[ExchangeRate] AS [SorMaster_ExchangeRate]
		,[SO].[MulDiv] AS [SorMaster_MulDiv]
		,[SO].[Currency] AS [SorMaster_Currency]
		,[SO].[GstDeduction] AS [SorMaster_GstDeduction]
		,[SO].[OrderStatusFail] AS [SorMaster_OrderStatusFail]
		,[SO].[ConsolidatedOrder] AS [SorMaster_DateConsolidOrder]
		,[SO].[CreditedInvDate] AS [SorMaster_DateCreditedInv]
		,[SO].[Job] AS [SorMaster_Job]
		,[SO].[SerialisedFlag] AS [SorMaster_SerialisedFlag]
		,[SO].[CounterSalesFlag] AS [SorMaster_CounterSalesFlag]
		,[SO].[Nationality] AS [SorMaster_Nationality]
		,[SO].[DeliveryTerms] AS [SorMaster_DeliveryTerms]
		,[SO].[TransactionNature] AS [SorMaster_TransactionNature]
		,[SO].[TransportMode] AS [SorMaster_TransportMode]
		,[SO].[ProcessFlag] AS [SorMaster_ProcessFlag]
		,[SO].[JobsExistFlag] AS [SorMaster_JobsExistFlag]
		,[SO].[AlternateKey] AS [SorMaster_AlternateKey]
		,[SO].[LastOperator] AS [SorMaster_LastOperator]
		,[SO].[HierarchyFlag] AS [SorMaster_HierarchyFlag]
		,[SO].[DepositFlag] AS [SorMaster_DepositFlag]
		,[SO].[EdiSource] AS [SorMaster_EdiSource]
		,[SO].[DeliveryNote] AS [SorMaster_DeliveryNote]
		,[SO].[Operator] AS [SorMaster_Operator]
		,[SO].[LineComp] AS [SorMaster_LineComp]
		,[SO].[CaptureHh] AS [SorMaster_CaptureHh]
		,[SO].[CaptureMm] AS [SorMaster_CaptureMm]
		,[SO].[LastDelNote] AS [SorMaster_LastDelNote]
		,[SO].[TimeDelPrtedHh] AS [SorMaster_TimeDelPrtedHh]
		,[SO].[TimeDelPrtedMm] AS [SorMaster_TimeDelPrtedMm]
		,[SO].[TimeInvPrtedHh] AS [SorMaster_TimeInvPrtedHh]
		,[SO].[TimeInvPrtedMm] AS [SorMaster_TimeInvPrtedMm]
		,[SO].[DateLastInvPrt] AS [SorMaster_DateLastInvPrt]
		,[SO].[Salesperson2] AS [SorMaster_Salesperson2]
		,[SO].[Salesperson3] AS [SorMaster_Salesperson3]
		,[SO].[Salesperson4] AS [SorMaster_Salesperson4]
		,[SO].[CommissionSales1] AS [SorMaster_CommissionSales1]
		,[SO].[CommissionSales2] AS [SorMaster_CommissionSales2]
		,[SO].[CommissionSales3] AS [SorMaster_CommissionSales3]
		,[SO].[CommissionSales4] AS [SorMaster_CommissionSales4]
		,[SO].[TimeTakenToAdd] AS [SorMaster_TimeTakenToAdd]
		,[SO].[TimeTakenToChg] AS [SorMaster_TimeTakenToChg]
		,[SO].[FaxInvInBatch] AS [SorMaster_FaxInvInBatch]
		,[SO].[InterWhSale] AS [SorMaster_InterWhSale]
		,[SO].[SourceWarehouse] AS [SorMaster_SourceWarehouse]
		,[SO].[TargetWarehouse] AS [SorMaster_TargetWarehouse]
		,[SO].[DispatchesMade] AS [SorMaster_DispatchesMade]
		,[SO].[LiveDispExist] AS [SorMaster_LiveDispExist]
		,[SO].[NumDispatches] AS [SorMaster_NumDispatches]
		,[SO].[CustomerName] AS [SorMaster_CustomerName]
		,[SO].[ShipAddress1] AS [SorMaster_ShipAddress1]
		,[SO].[ShipAddress2] AS [SorMaster_ShipAddress2]
		,[SO].[ShipAddress3] AS [SorMaster_ShipAddress3]
		,[SO].[ShipAddress3Loc] AS [SorMaster_ShipAddress3Loc]
		,[SO].[ShipAddress4] AS [SorMaster_ShipAddress4]
		,[SO].[ShipAddress5] AS [SorMaster_ShipAddress5]
		,[SO].[ShipPostalCode] AS [SorMaster_ShipPostalCode]
		,[SO].[ShipToGpsLat] AS [SorMaster_ShipToGpsLat]
		,[SO].[ShipToGpsLong] AS [SorMaster_ShipToGpsLong]
		,[SO].[State] AS [SorMaster_State]
		,[SO].[CountyZip] AS [SorMaster_CountyZip]
		,[SO].[ExtendedTaxCode] AS [SorMaster_ExtendedTaxCode]
		,[SO].[MultiShipCode] AS [SorMaster_MultiShipCode]
		,[SO].[WebCreated] AS [SorMaster_WebCreated]
		,[SO].[Quote] AS [SorMaster_Quote]
		,[SO].[QuoteVersion] AS [SorMaster_QuoteVersion]
		,[SO].[GtrReference] AS [SorMaster_GtrReference]
		,[SO].[NonMerchFlag] AS [SorMaster_NonMerchFlag]
		,[SO].[Email] AS [SorMaster_Email]
		,[SO].[User1] AS [SorMaster_User1]
		,[SO].[CompanyTaxNo] AS [SorMaster_CompanyTaxNo]
		,[SO].[TpmPickupFlag] AS [SorMaster_TpmPickupFlag]
		,[SO].[TpmEvaluatedFlag] AS [SorMaster_TpmEvaluatedFlag]
		,[SO].[StandardComment] AS [SorMaster_StandardComment]
		,[SO].[DetailStatus] AS [SorMaster_DetailStatus]
		,[SO].[SalesOrderSource] AS [SorMaster_SalesOrderSource]
		,[SO].[SalesOrderSrcDesc] AS [SorMaster_SalesOrderSrcDesc]
		,[SO].[LanguageCode] AS [SorMaster_LanguageCode]
		,[SO].[ShippingLocation] AS [SorMaster_ShippingLocation]
		,[SO].[IncludeInMrp] AS [SorMaster_IncludeInMrp]
		,[SO].[TimeStamp] AS [SorMaster_TimeStamp]

		,[W].[Job] AS [WipMaster_Job]
        ,[W].[JobDescription] AS [WipMaster_JobDescription]
        ,[W].[JobClassification] AS [WipMaster_JobClassification]
        ,[W].[JobType] AS [WipMaster_JobType]
        ,[W].[MasterJob] AS [WipMaster_MasterJob]
        ,[W].[Priority] AS [WipMaster_Priority]
        ,[W].[StockCode] AS [WipMaster_StockCode]
        ,[W].[StockDescription] AS [WipMaster_StockDescription]
        ,[W].[Warehouse] AS [WipMaster_Warehouse]
        ,[W].[Customer] AS [WipMaster_Customer]
        ,[W].[CustomerName] AS [WipMaster_CustomerName]
        ,[W].[JobTenderDate] AS [WipMaster_DateJobTender]
        ,[W].[JobDeliveryDate] AS [WipMaster_DateJobDelivery]
        ,[W].[JobStartDate] AS [WipMaster_DateJobStart]
        ,[W].[ActCompleteDate] AS [WipMaster_DateActComplete]
        ,[W].[Complete] AS [WipMaster_Complete]
        ,[W].[SeqCheckReq] AS [WipMaster_SeqCheckReq]
        ,[W].[DateCalcMethod] AS [WipMaster_DateCalcMethod]
        ,[W].[ExpLabour] AS [WipMaster_ExpLabour]
        ,[W].[ExpMaterial] AS [WipMaster_ExpMaterial]
        ,[W].[QtyToMake] AS [WipMaster_QtyToMake]
        ,[W].[QtyManufactured] AS [WipMaster_QtyManufactured]
        ,[W].[Source] AS [WipMaster_Source]
        ,[W].[EstSourceNum] AS [WipMaster_EstSourceNum]
        ,[W].[NextDetailLine] AS [WipMaster_NextDetailLine]
        ,[W].[PctCompleteFlag] AS [WipMaster_PctCompleteFlag]
        ,[W].[PrtFactDoc1] AS [WipMaster_PrtFactDoc1]
        ,[W].[PrtFactDoc2] AS [WipMaster_PrtFactDoc2]
        ,[W].[PrtFactDoc3] AS [WipMaster_PrtFactDoc3]
        ,[W].[PrtFactDoc4] AS [WipMaster_PrtFactDoc4]
        ,[W].[SellingPrice] AS [WipMaster_SellingPrice]
        ,[W].[AddLabPct] AS [WipMaster_AddLabPct]
        ,[W].[AddMatPct] AS [WipMaster_AddMatPct]
        ,[W].[ProfitPct] AS [WipMaster_ProfitPct]
        ,[W].[SalesOrder] AS [WipMaster_SalesOrder]
        ,[W].[MaterialBilled] AS [WipMaster_MaterialBilled]
        ,[W].[LabourBilled] AS [WipMaster_LabourBilled]
        ,[W].[NextOpForAll] AS [WipMaster_NextOpForAll]
        ,[W].[HighestOpPosted] AS [WipMaster_HighestOpPosted]
        ,[W].[TotalQtyScrapped] AS [WipMaster_TotalQtyScrapped]
        ,[W].[ConfirmedFlag] AS [WipMaster_ConfirmedFlag]
        ,[W].[HoldFlag] AS [WipMaster_HoldFlag]
        ,[W].[JobCreatedStruc] AS [WipMaster_JobCreatedStruc]
        ,[W].[LstOrderCreated] AS [WipMaster_LstOrderCreated]
        ,[W].[TraceableType] AS [WipMaster_TraceableType]
        ,[W].[NxtLinePartBook] AS [WipMaster_NxtLinePartBook]
        ,[W].[Route] AS [WipMaster_Route]
        ,[W].[WipCtlGlCode] AS [WipMaster_WipCtlGlCode]
        ,[W].[Decimals] AS [WipMaster_Decimals]
        ,[W].[SalesOrderLine] AS [WipMaster_SalesOrderLine]
        ,[W].[MatCostToDate1] AS [WipMaster_DateMatCostTo1]
        ,[W].[MatCostToDate2] AS [WipMaster_DateMatCostTo2]
        ,[W].[MatCostToDate3] AS [WipMaster_DateMatCostTo3]
        ,[W].[LabCostToDate1] AS [WipMaster_DateLabCostTo1]
        ,[W].[LabCostToDate2] AS [WipMaster_DateLabCostTo2]
        ,[W].[LabCostToDate3] AS [WipMaster_DateLabCostTo3]
        ,[W].[HrsBookToDate1] AS [WipMaster_DateHrsBookTo1]
        ,[W].[HrsBookToDate2] AS [WipMaster_DateHrsBookTo2]
        ,[W].[HrsBookToDate3] AS [WipMaster_DateHrsBookTo3]
        ,[W].[MatValueIssues1] AS [WipMaster_MatValueIssues1]
        ,[W].[MatValueIssues2] AS [WipMaster_MatValueIssues2]
        ,[W].[MatValueIssues3] AS [WipMaster_MatValueIssues3]
        ,[W].[LabValueIssues1] AS [WipMaster_LabValueIssues1]
        ,[W].[LabValueIssues2] AS [WipMaster_LabValueIssues2]
        ,[W].[LabValueIssues3] AS [WipMaster_LabValueIssues3]
        ,[W].[NarrationNum] AS [WipMaster_NarrationNum]
        ,[W].[ReqPlnFlag] AS [WipMaster_ReqPlnFlag]
        ,[W].[DateJobLstUpd] AS [WipMaster_DateJobLstUpd]
        ,[W].[TimeJobLstUpd] AS [WipMaster_TimeJobLstUpd]
        ,[W].[HierarchyFlag] AS [WipMaster_HierarchyFlag]
        ,[W].[NextLineHier] AS [WipMaster_NextLineHier]
        ,[W].[EstTrailLoad] AS [WipMaster_EstTrailLoad]
        ,[W].[OrdEntSource] AS [WipMaster_OrdEntSource]
        ,[W].[Version] AS [WipMaster_Version]
        ,[W].[Release] AS [WipMaster_Release]
        ,[W].[AllocationLine] AS [WipMaster_AllocationLine]
        ,[W].[PurgeJob] AS [WipMaster_PurgeJob]
        ,[W].[HierarchyJob] AS [WipMaster_HierarchyJob]
        ,[W].[MrpFromJob] AS [WipMaster_MrpFromJob]
        ,[W].[MrpToJob] AS [WipMaster_MrpToJob]
        ,[W].[OrigDueDate] AS [WipMaster_DateOrigDue]
        ,[W].[GrossFlg] AS [WipMaster_GrossFlg]
        ,[W].[GrossQty] AS [WipMaster_GrossQty]
        ,[W].[ExpLabCurrent] AS [WipMaster_ExpLabCurrent]
        ,[W].[ExpMatCurrent] AS [WipMaster_ExpMatCurrent]
        ,[W].[ReservedLotSerFlag] AS [WipMaster_ReservedLotSerFlag]
        ,[W].[NotionalPart] AS [WipMaster_NotionalPart]
        ,[W].[CoProductCostMet] AS [WipMaster_CoProductCostMet]
        ,[W].[CoProductCostVal] AS [WipMaster_CoProductCostVal]
        ,[W].[CoProductType] AS [WipMaster_CoProductType]
        ,[W].[CapexCode] AS [WipMaster_CapexCode]
        ,[W].[CapexLine] AS [WipMaster_CapexLine]
        ,[W].[UomFlag] AS [WipMaster_UomFlag]
        ,[W].[ConvFactUom] AS [WipMaster_ConvFactUom]
        ,[W].[ConvMulDiv] AS [WipMaster_ConvMulDiv]
        ,[W].[ScheduleFlag] AS [WipMaster_ScheduleFlag]
        ,[W].[SchStartDate] AS [WipMaster_DateSchStart]
        ,[W].[SchStartTime] AS [WipMaster_SchStartTime]
        ,[W].[SchEndDate] AS [WipMaster_DateSchEnd]
        ,[W].[SchEndTime] AS [WipMaster_SchEndTime]
        ,[W].[QtyToMakeEnt] AS [WipMaster_QtyToMakeEnt]
        ,[W].[QtyManufacturedEnt] AS [WipMaster_QtyManufacturedEnt]
        ,[W].[TotQtyScrappedEnt] AS [WipMaster_TotQtyScrappedEnt]
        ,[W].[GrossQtyEnt] AS [WipMaster_GrossQtyEnt]
        ,[W].[ProductCode] AS [WipMaster_ProductCode]
        ,[W].[LibraryCode] AS [WipMaster_LibraryCode]
        ,[W].[TimeStamp] AS [WipMaster_TimeStamp]
        ,[W].[NestAllocs] AS [WipMaster_NestAllocs]
        ,[W].[CreatedForNest] AS [WipMaster_CreatedForNest]

		,[dt].[ProdSchedID#] AS [dtProdSched_ProdSchedID]
        ,[dt].[Quote#] AS [dtProdSched_Quote]
        ,[dt].[WO#] AS [dtProdSched_WO]
        ,[dt].[InputField1] AS [dtProdSched_InputField1]
        ,[dt].[InputField2] AS [dtProdSched_InputField2]
        ,[dt].[Beam Line] AS [dtProdSched_BeamLine]
        ,[dt].[Beam Date] AS [dtProdSched_DateBeam]
        ,[dt].[GN Line] AS [dtProdSched_GNLine]
        ,[dt].[GN Date] AS [dtProdSched_DateGN]
        ,[dt].[WO Line 1] AS [dtProdSched_WOLine1]
        ,[dt].[Prod Date 1] AS [dtProdSched_DateProd1]
        ,[dt].[WO Line 2] AS [dtProdSched_WOLine2]
        ,[dt].[Prod Date 2] AS [dtProdSched_DateProd2]
        ,[dt].[Other] AS [dtProdSched_Other]
        ,[dt].[Other Line] AS [dtProdSched_OtherLine]
        ,[dt].[Other Date] AS [dtProdSched_DateOther]
        ,[dt].[HideFromProdInput] AS [dtProdSched_HideFromProdInput]
        ,[dt].[Step1SYSPROBudget] AS [dtProdSched_Step1SYSPROBudget]
        ,[dt].[Step2SYSPROBudget] AS [dtProdSched_Step2SYSPROBudget]
        ,[dt].[dtprodschedts] AS [dtProdSched_dtprodschedts]
        ,[dt].[ApplyUpdate] AS [dtProdSched_ApplyUpdate]
        ,[dt].[ApplyUpdateUser] AS [dtProdSched_ApplyUpdateUser]
        ,[dt].[Slot#] AS [dtProdSched_Slot]
        ,[dt].[Slot/Quote] AS [dtProdSched_SlotQuote]
        ,[dt].[Slot Approved] AS [dtProdSched_SlotApproved]
        ,[dt].[Prod On] AS [dtProdSched_ProdOn]
        ,[dt].[Prod On Time] AS [dtProdSched_ProdOnTime]
        ,[dt].[Prod Off] AS [dtProdSched_ProdOff]
        ,[dt].[Prod Off Time] AS [dtProdSched_ProdOffTime]
        ,[dt].[Prod PM] AS [dtProdSched_ProdPM]
        ,[dt].[Prod Complete] AS [dtProdSched_ProdComplete]
        ,[dt].[Prod2 On] AS [dtProdSched_Prod2On]
        ,[dt].[Prod2 On Time] AS [dtProdSched_Prod2OnTime]
        ,[dt].[Prod2 Off] AS [dtProdSched_Prod2Off]
        ,[dt].[Prod2 Off Time] AS [dtProdSched_Prod2OffTime]
        ,[dt].[Prod2 PM] AS [dtProdSched_Prod2PM]
        ,[dt].[Prod2 Complete] AS [dtProdSched_Prod2Complete]
        ,[dt].[Prod Instructions] AS [dtProdSched_ProdInstructions]
        ,[dt].[Beam On] AS [dtProdSched_BeamOn]
        ,[dt].[Beam Off] AS [dtProdSched_BeamOff]
        ,[dt].[Beam Complete] AS [dtProdSched_BeamComplete]
        ,[dt].[Beam PM] AS [dtProdSched_BeamPM]
        ,[dt].[Beam Instructions] AS [dtProdSched_BeamInstructions]
        ,[dt].[GN On] AS [dtProdSched_GNOn]
        ,[dt].[GN Off] AS [dtProdSched_GNOff]
        ,[dt].[GN Complete] AS [dtProdSched_GNComplete]
        ,[dt].[GN PM] AS [dtProdSched_GNPM]
        ,[dt].[GN Instructions] AS [dtProdSched_GNInstructions]
        ,[dt].[Axle] AS [dtProdSched_Axle]
        ,[dt].[Axle On] AS [dtProdSched_AxleOn]
        ,[dt].[Axle Off] AS [dtProdSched_AxleOff]
        ,[dt].[Axle Complete] AS [dtProdSched_AxleComplete]
        ,[dt].[Axle PM] AS [dtProdSched_AxlePM]
        ,[dt].[Axle Instructions] AS [dtProdSched_AxleInstructions]
        ,[dt].[Other On] AS [dtProdSched_OtherOn]
        ,[dt].[Other On Time] AS [dtProdSched_OtherOnTime]
        ,[dt].[Other Off] AS [dtProdSched_OtherOff]
        ,[dt].[Other Off Time] AS [dtProdSched_OtherOffTime]
        ,[dt].[Other Complete] AS [dtProdSched_OtherComplete]
        ,[dt].[Other PM] AS [dtProdSched_OtherPM]
        ,[dt].[Other Instructions] AS [dtProdSched_OtherInstructions]
        ,[dt].[Stargate WO#] AS [dtProdSched_StargateWO]

		,(CASE 
			WHEN [O].[Quote Date] IS NULL THEN NULL
			ELSE DATEDIFF(YEAR, [O].[Quote Date], GETDATE())
		END) AS [YearGroup]
		,(CASE 
			WHEN [O].[Quote Date] IS NULL THEN NULL
			ELSE DATEDIFF(MONTH, [O].[Quote Date], GETDATE())
		END) AS [MonthGroup]
		,DATEPART(WEEKDAY, [O].[Quote Date]) AS [QuoteWeekday]
		,DATEDIFF(DAY, [O].[Quote Date], [O].[Order Date]) AS [DaysQuoteToOrder]
		,DATEDIFF(DAY, [O].[Quote Date], [O].[Delivery Date]) AS [DaysQuoteToDelivery]
		,DATEDIFF(DAY, [O].[Order Date], [O].[Delivery Date]) AS [DaysOrderToDelivery]
		,DATEDIFF(DAY, [O].[Quote Date], [O].[Date Declined]) AS [DaysQuoteToDecline]

	FROM
		[Orders] AS [O] WITH (NOLOCK)
	LEFT JOIN
		[Dealers] AS [D] WITH (NOLOCK)
	ON
		[O].[DealerID] = [D].[ID]
	LEFT JOIN
		[Products] AS [P] WITH (NOLOCK)
	ON
		[O].[ProductID] = [P].[IDTrailer]
	LEFT JOIN
		[Sales Staff] AS [SS] WITH (NOLOCK)
	ON
		[O].[Sale PersonID] = [SS].[ID-SaleStaff]
	LEFT JOIN
		[SysproCompanyA].[dbo].[SorMaster] AS [SO] WITH (NOLOCK)
	ON
		[O].[Sales Order#] = [SO].[SalesOrder]
	LEFT JOIN
		[SysproCompanyA].[dbo].[WipMaster] AS [W] WITH (NOLOCK)
	ON
		CAST([O].[WO#] AS NVARCHAR(MAX)) = [W].[Job]
	LEFT JOIN
		[dtProductionSchedule] AS [dt]
	ON
		[O].[Quote#] = [dt].[Quote#]
		AND [O].[CompanyID] = 0

	UNION ALL

	SELECT
		'STG' AS [OriginTable]
		,[O2].[OrderID] AS [OrdersV2_OrderID]
		,[O2].[SGQuote] AS [OrdersV2_SGQuote]
		,[O2].[Quote Date] AS [OrdersV2_DateQuote]
		,[O2].[Order Date] AS [OrdersV2_DateOrder]
		,[O2].[WO#] AS [OrdersV2_WO]
		,[O2].[Sales Order#] AS [OrdersV2_SalesOrder]
		,[O2].[Model No] AS [OrdersV2_ModelNo]
		,[O2].[Width] AS [OrdersV2_Width]
		,[O2].[Spread] AS [OrdersV2_Spread]
		,[O2].[DealerID] AS [OrdersV2_DealerID]
		,[O2].[Sale PersonID] AS [OrdersV2_SalePersonID]
		,[O2].[Price] AS [OrdersV2_Price]
		,[O2].[Prom Drawing] AS [OrdersV2_PromDrawing]
		,[O2].[Special Instructions] AS [OrdersV2_SpecialInstructions]
		,[O2].[Date Declined] AS [OrdersV2_DateDeclined]
		,[O2].[Decline/Rejected] AS [OrdersV2_DeclineRejected]
		,[O2].[Serial Number] AS [OrdersV2_SerialNumber]
		,[O2].[Available Date] AS [OrdersV2_DateAvailable]
		,[O2].[Delivery Date] AS [OrdersV2_DateDelivery]
		,[O2].[Requested Delivery Date] AS [OrdersV2_DateRequestedDelivery]
		,[O2].[Finish Date] AS [OrdersV2_DateFinish]
		,[O2].[Purchase Order] AS [OrdersV2_PurchaseOrder]
		,[O2].[PO Date] AS [OrdersV2_DatePO]
		,[O2].[PayID] AS [OrdersV2_PayID]
		,[O2].[Volume Discount] AS [OrdersV2_VolumeDiscount]
		,[O2].[Program Discount] AS [OrdersV2_ProgramDiscount]
		,[O2].[Discount1_Name] AS [OrdersV2_Discount1_Name]
		,[O2].[Discount1_Type] AS [OrdersV2_Discount1_Type]
		,[O2].[Discount1] AS [OrdersV2_Discount1]
		,[O2].[Discount2_Name] AS [OrdersV2_Discount2_Name]
		,[O2].[Discount2_Type] AS [OrdersV2_Discount2_Type]
		,[O2].[Discount2] AS [OrdersV2_Discount2]
		,[O2].[Discount3_Name] AS [OrdersV2_Discount3_Name]
		,[O2].[Discount3_Type] AS [OrdersV2_Discount3_Type]
		,[O2].[Discount3] AS [OrdersV2_Discount3]
		,[O2].[Est Pro Date] AS [OrdersV2_DateEstPro]
		,[O2].[Notes] AS [OrdersV2_Notes]
		,CAST([O2].[EngNotes] AS NVARCHAR(MAX)) AS [OrdersV2_EngNotes]
		,[O2].[CarrierID] AS [OrdersV2_CarrierID]
		,[O2].[CustID] AS [OrdersV2_CustID]
		,[O2].[US Sale] AS [OrdersV2_USSale]
		,[O2].[Shipped Date] AS [OrdersV2_DateShipped]
		,[O2].[GL Override Date] AS [OrdersV2_DateGLOverride]
		,[O2].[FE Rate] AS [OrdersV2_FERate]
		,[O2].[PDD] AS [OrdersV2_PDD]
		,[O2].[Deck Length] AS [OrdersV2_DeckLength]
		,[O2].[Invoice #] AS [OrdersV2_Invoice]
		,[O2].[Date Registered] AS [OrdersV2_DateRegistered]
		,[O2].[Date In Service] AS [OrdersV2_DateInService]
		,[O2].[Invoice Date] AS [OrdersV2_DateInvoice]
		,[O2].[Date Requested] AS [OrdersV2_DateRequested]
		,[O2].[GVWR] AS [OrdersV2_GVWR]
		,[O2].[Tare] AS [OrdersV2_Tare]
		,[O2].[Selection] AS [OrdersV2_Selection]
		,[O2].[Warranty] AS [OrdersV2_Warranty]
		,[O2].[BWSPaid] AS [OrdersV2_BWSPaid]
		,[O2].[BWSPaidDate] AS [OrdersV2_DateBWSPaid]
		,[O2].[CommPaid] AS [OrdersV2_CommPaid]
		,[O2].[CommPaidDate] AS [OrdersV2_DateCommPaid]
		,[O2].[ts_timestamp] AS [OrdersV2_ts_timestamp]
		,[O2].[ModifiedBy] AS [OrdersV2_ModifiedBy]
		,[O2].[Lead Date] AS [OrdersV2_DateLead]
		,[O2].[Lead Source] AS [OrdersV2_LeadSource]
		,[O2].[LeadID] AS [OrdersV2_LeadID]
		,[O2].[DealerBranchID] AS [OrdersV2_DealerBranchID]
		,[O2].[DealerSalesPersonID] AS [OrdersV2_DealerSalesPersonID]
		,[O2].[DataEntryCheck] AS [OrdersV2_DataEntryCheck]
		,[O2].[DataEntryUser] AS [OrdersV2_DataEntryUser]
		,[O2].[FinishedGoodsDealerLocID] AS [OrdersV2_FinishedGoodsDealerLocID]
		,[O2].[WO Reviewed] AS [OrdersV2_WOReviewed]
		,[O2].[WO Review Date] AS [OrdersV2_DateWOReview]
		,[O2].[Follow Up Date] AS [OrdersV2_DateFollowUp]
		,[O2].[MSOIsDifferent] AS [OrdersV2_MSOIsDifferent]
		,[O2].[MSOLocID] AS [OrdersV2_MSOLocID]
		,[O2].[EstInvDateOverride] AS [OrdersV2_DateEstInvOverride]
		,[O2].[Estimated Invoice Date] AS [OrdersV2_DateEstimatedInvoice]
		,[O2].[AdditionalPricingInfo] AS [OrdersV2_AdditionalPricingInfo]
		,[O2].[Slot#] AS [OrdersV2_Slot]
		,[O2].[TempModel?] AS [OrdersV2_TempModel]
		,[O2].[HighRiskUnit] AS [OrdersV2_HighRiskUnit]
		,[O2].[EngNotes V2] AS [OrdersV2_EngNotesV2]
		,[O2].[CompanyID] AS [OrdersV2_CompanyID]
		,[O2].[Customer WO#] AS [OrdersV2_CustomerWO]
		,[O2].[PriceSecured] AS [OrdersV2_PriceSecured]
		,[O2].[DateSecured] AS [OrdersV2_DateSecured]
		,[O2].[SecuredBy] AS [OrdersV2_SecuredBy]
		,[O2].[InternalSalesComments] AS [OrdersV2_InternalSalesComments]
		,[O2].[InternalSalesCommentDate] AS [OrdersV2_DateInternalSalesComment]
		,[O2].[InternalSalesCommenter] AS [OrdersV2_InternalSalesCommenter]
		,[O2].[DiscountSetDate] AS [OrdersV2_DateDiscountSet]
		,[O2].[DiscountSetBy] AS [OrdersV2_DiscountSetBy]
		,[O2].[ProductID] AS [OrdersV2_ProductID]
		,[O2].[DiscountID] AS [OrdersV2_DiscountID]
		,[O2].[DateLastQuoteReport] AS [OrdersV2_DateLastQuoteReport]
		,[O2].[JobAvailableLine] AS [OrdersV2_JobAvailableLine]
		,[O2].[JobAvailableScheduled] AS [OrdersV2_JobAvailableScheduled]
		,[O2].[JobAvailableScheduledBy] AS [OrdersV2_JobAvailableScheduledBy]

		,[D2].[ID] AS [DealersV2_ID]
		,[D2].[COMPANY NAME] AS [DealersV2_COMPANYNAME]
		,[D2].[ADDRESS] AS [DealersV2_ADDRESS]
		,[D2].[CITY] AS [DealersV2_CITY]
		,[D2].[PROVINCE] AS [DealersV2_PROVINCE]
		,[D2].[POSTAL CODE] AS [DealersV2_POSTALCODE]
		,[D2].[PHONE] AS [DealersV2_PHONE]
		,[D2].[TOLL FREE] AS [DealersV2_TOLLFREE]
		,[D2].[FAX] AS [DealersV2_FAX]
		,[D2].[CONTACT] AS [DealersV2_CONTACT]
		,[D2].[CELL] AS [DealersV2_CELL]
		,[D2].[EMAIL] AS [DealersV2_EMAIL]
		,[D2].[DEALER NUMBER] AS [DealersV2_DEALERNUMBER]
		,[D2].[CURRENT DEALER] AS [DealersV2_CURRENTDEALER]
		,[D2].[CURRENT DEALER CDN] AS [DealersV2_CURRENTDEALERCDN]
		,[D2].[CURRENT DEALER US] AS [DealersV2_CURRENTDEALERUS]
		,[D2].[Invoice] AS [DealersV2_Invoice]
		,[D2].[Eastern Canada] AS [DealersV2_EasternCanada]
		,[D2].[Eastern US] AS [DealersV2_EasternUS]
		,[D2].[Central Canada] AS [DealersV2_CentralCanada]
		,[D2].[Central US] AS [DealersV2_CentralUS]
		,[D2].[Western Canada] AS [DealersV2_WesternCanada]
		,[D2].[Western US] AS [DealersV2_WesternUS]
		,[D2].[American] AS [DealersV2_American]
		,[D2].[Proprietary/Direct/Other] AS [DealersV2_ProprietaryDirectOther]
		,[D2].[Initials] AS [DealersV2_Initials]
		,[D2].[dealers_timestamp] AS [DealersV2_dealers_timestamp]
		,[D2].[DataEntryCheck] AS [DealersV2_DataEntryCheck]
		,[D2].[DataEntryUser] AS [DealersV2_DataEntryUser]
		,[D2].[DefaultPayID] AS [DealersV2_DefaultPayID]
		,[D2].[SendDealerStatusEmail?] AS [DealersV2_SendDealerStatusEmail]
		,[D2].[CompanyID] AS [DealersV2_CompanyID]
		,[D2].[SlotsRequestedPerMonth] AS [DealersV2_SlotsRequestedPerMonth]

		,[P2].[IDTrailer] AS [ProductsV2_IDTrailer]
		,[P2].[Class] AS [ProductsV2_Class]
		,[P2].[Proposed] AS [ProductsV2_Proposed]
		,[P2].[Non-Current] AS [ProductsV2_Non-Current]
		,[P2].[Model] AS [ProductsV2_Model]
		,[P2].[Model No] AS [ProductsV2_ModelNo]
		,[P2].[Top Level Part# (SYSPRO)] AS [ProductsV2_TopLevelPart(SYSPRO)]
		,[P2].[Grouping] AS [ProductsV2_Grouping]
		,[P2].[Start Date] AS [ProductsV2_DateStart]
		,[P2].[End Date] AS [ProductsV2_DateEnd]
		,[P2].[Price] AS [ProductsV2_Price]
		,[P2].[Weight] AS [ProductsV2_Weight]
		,[P2].[Make] AS [ProductsV2_Make]
		,[P2].[NVIS] AS [ProductsV2_NVIS]
		,CAST([P2].[Promo Drawing] AS NVARCHAR(MAX)) AS [ProductsV2_PromoDrawing]
		,[P2].[Width] AS [ProductsV2_Width]
		,[P2].[Spread] AS [ProductsV2_Spread]
		,[P2].[Deck Length] AS [ProductsV2_DeckLength]
		,[P2].[Days] AS [ProductsV2_Days]
		,[P2].[GN] AS [ProductsV2_GN]
		,[P2].[Paint] AS [ProductsV2_Paint]
		,[P2].[Finish] AS [ProductsV2_Finish]
		,[P2].[S/NL1] AS [ProductsV2_SNL1]
		,[P2].[S/NL2] AS [ProductsV2_SNL2]
		,[P2].[S/NT1] AS [ProductsV2_SNT1]
		,[P2].[S/NT2] AS [ProductsV2_SNT2]
		,[P2].[S/NAxles] AS [ProductsV2_SNAxles]
		,[P2].[Selection] AS [ProductsV2_Selection]
		,[P2].[EffComDate] AS [ProductsV2_DateEffCom]
		,[P2].[ComRate] AS [ProductsV2_ComRate]
		,[P2].[LastCostUpdate] AS [ProductsV2_LastCostUpdate]
		,[P2].[LCUInitials] AS [ProductsV2_LCUInitials]
		,[P2].[QR_Discount1] AS [ProductsV2_QR_Discount1]
		,[P2].[QR_Discount2] AS [ProductsV2_QR_Discount2]
		,[P2].[QR_Discount3] AS [ProductsV2_QR_Discount3]
		,[P2].[product_timestamp] AS [ProductsV2_product_timestamp]
		,[P2].[QR_ExpectedMargin] AS [ProductsV2_QR_ExpectedMargin]
		,[P2].[tmpProductsV2ClassesID] AS [ProductsV2_tmpProductsV2ClassesID]
		,[P2].[QRUS_Discount1] AS [ProductsV2_QRUS_Discount1]
		,[P2].[QRUS_Discount2] AS [ProductsV2_QRUS_Discount2]
		,[P2].[QRUS_Discount3] AS [ProductsV2_QRUS_Discount3]
		,[P2].[QRUS_ExpectedMargin] AS [ProductsV2_QRUS_ExpectedMargin]
		,[P2].[US Price] AS [ProductsV2_USPrice]
		,[P2].[Customer] AS [ProductsV2_Customer]
		,[P2].[Top Level Part# (SYSPRO 8)] AS [ProductsV2_TopLevelPart(SYSPRO8)]
		,[P2].[Promo Drawing V2] AS [ProductsV2_PromoDrawingV2]
		,[P2].[CompanyID] AS [ProductsV2_CompanyID]

		,[SS].[ID-SaleStaff] AS [SalesStaff_ID-SaleStaff]
		,[SS].[Initials] AS [SalesStaff_Initials]
		,[SS].[Sales Person] AS [SalesStaff_SalesPerson]
		,[SS].[Company] AS [SalesStaff_Company]
		,[SS].[DateCreated] AS [SalesStaff_DateCreated]
		,[SS].[Active] AS [SalesStaff_Active]
		,[SS].[DateActive] AS [SalesStaff_DateActive]
		,[SS].[DateInactive] AS [SalesStaff_DateInactive]
		,[SS].[Notes] AS [SalesStaff_Notes]
		
		,[SO].[SalesOrder] AS [SorMaster_SalesOrder]
		,[SO].[NextDetailLine] AS [SorMaster_NextDetailLine]
		,[SO].[OrderStatus] AS [SorMaster_OrderStatus]
		,[SO].[ActiveFlag] AS [SorMaster_ActiveFlag]
		,[SO].[CancelledFlag] AS [SorMaster_CancelledFlag]
		,[SO].[DocumentType] AS [SorMaster_DocumentType]
		,[SO].[Customer] AS [SorMaster_Customer]
		,[SO].[Salesperson] AS [SorMaster_Salesperson]
		,[SO].[CustomerPoNumber] AS [SorMaster_CustomerPoNumber]
		,[SO].[OrderDate] AS [SorMaster_DateOrder]
		,[SO].[EntrySystemDate] AS [SorMaster_DateEntrySystem]
		,[SO].[ReqShipDate] AS [SorMaster_DateReqShip]
		,[SO].[DateLastDocPrt] AS [SorMaster_DateLastDocPrt]
		,[SO].[ShippingInstrs] AS [SorMaster_ShippingInstrs]
		,[SO].[ShippingInstrsCod] AS [SorMaster_ShippingInstrsCod]
		,[SO].[AltShipAddrFlag] AS [SorMaster_AltShipAddrFlag]
		,[SO].[InvoiceCount] AS [SorMaster_InvoiceCount]
		,[SO].[InvTermsOverride] AS [SorMaster_InvTermsOverride]
		,[SO].[CreditAuthority] AS [SorMaster_CreditAuthority]
		,[SO].[Branch] AS [SorMaster_Branch]
		,[SO].[SpecialInstrs] AS [SorMaster_SpecialInstrs]
		,[SO].[EntInvoice] AS [SorMaster_EntInvoice]
		,[SO].[EntInvoiceDate] AS [SorMaster_DateEntInvoice]
		,[SO].[DiscPct1] AS [SorMaster_DiscPct1]
		,[SO].[DiscPct2] AS [SorMaster_DiscPct2]
		,[SO].[DiscPct3] AS [SorMaster_DiscPct3]
		,[SO].[OrderType] AS [SorMaster_OrderType]
		,[SO].[TaxExemptFlag] AS [SorMaster_TaxExemptFlag]
		,[SO].[Area] AS [SorMaster_Area]
		,[SO].[TaxExemptNumber] AS [SorMaster_TaxExemptNumber]
		,[SO].[TaxExemptOverride] AS [SorMaster_TaxExemptOverride]
		,[SO].[CashCredit] AS [SorMaster_CashCredit]
		,[SO].[Warehouse] AS [SorMaster_Warehouse]
		,[SO].[LastInvoice] AS [SorMaster_LastInvoice]
		,[SO].[ScheduledOrdFlag] AS [SorMaster_ScheduledOrdFlag]
		,[SO].[GstExemptFlag] AS [SorMaster_GstExemptFlag]
		,[SO].[GstExemptNum] AS [SorMaster_GstExemptNum]
		,[SO].[GstExemptORide] AS [SorMaster_GstExemptORide]
		,[SO].[IbtFlag] AS [SorMaster_IbtFlag]
		,[SO].[OrdAcknwPrinted] AS [SorMaster_OrdAcknwPrinted]
		,[SO].[DetCustMvmtReqd] AS [SorMaster_DetCustMvmtReqd]
		,[SO].[DocumentFormat] AS [SorMaster_DocumentFormat]
		,[SO].[FixExchangeRate] AS [SorMaster_FixExchangeRate]
		,[SO].[ExchangeRate] AS [SorMaster_ExchangeRate]
		,[SO].[MulDiv] AS [SorMaster_MulDiv]
		,[SO].[Currency] AS [SorMaster_Currency]
		,[SO].[GstDeduction] AS [SorMaster_GstDeduction]
		,[SO].[OrderStatusFail] AS [SorMaster_OrderStatusFail]
		,[SO].[ConsolidatedOrder] AS [SorMaster_DateConsolidOrder]
		,[SO].[CreditedInvDate] AS [SorMaster_DateCreditedInv]
		,[SO].[Job] AS [SorMaster_Job]
		,[SO].[SerialisedFlag] AS [SorMaster_SerialisedFlag]
		,[SO].[CounterSalesFlag] AS [SorMaster_CounterSalesFlag]
		,[SO].[Nationality] AS [SorMaster_Nationality]
		,[SO].[DeliveryTerms] AS [SorMaster_DeliveryTerms]
		,[SO].[TransactionNature] AS [SorMaster_TransactionNature]
		,[SO].[TransportMode] AS [SorMaster_TransportMode]
		,[SO].[ProcessFlag] AS [SorMaster_ProcessFlag]
		,[SO].[JobsExistFlag] AS [SorMaster_JobsExistFlag]
		,[SO].[AlternateKey] AS [SorMaster_AlternateKey]
		,[SO].[LastOperator] AS [SorMaster_LastOperator]
		,[SO].[HierarchyFlag] AS [SorMaster_HierarchyFlag]
		,[SO].[DepositFlag] AS [SorMaster_DepositFlag]
		,[SO].[EdiSource] AS [SorMaster_EdiSource]
		,[SO].[DeliveryNote] AS [SorMaster_DeliveryNote]
		,[SO].[Operator] AS [SorMaster_Operator]
		,[SO].[LineComp] AS [SorMaster_LineComp]
		,[SO].[CaptureHh] AS [SorMaster_CaptureHh]
		,[SO].[CaptureMm] AS [SorMaster_CaptureMm]
		,[SO].[LastDelNote] AS [SorMaster_LastDelNote]
		,[SO].[TimeDelPrtedHh] AS [SorMaster_TimeDelPrtedHh]
		,[SO].[TimeDelPrtedMm] AS [SorMaster_TimeDelPrtedMm]
		,[SO].[TimeInvPrtedHh] AS [SorMaster_TimeInvPrtedHh]
		,[SO].[TimeInvPrtedMm] AS [SorMaster_TimeInvPrtedMm]
		,[SO].[DateLastInvPrt] AS [SorMaster_DateLastInvPrt]
		,[SO].[Salesperson2] AS [SorMaster_Salesperson2]
		,[SO].[Salesperson3] AS [SorMaster_Salesperson3]
		,[SO].[Salesperson4] AS [SorMaster_Salesperson4]
		,[SO].[CommissionSales1] AS [SorMaster_CommissionSales1]
		,[SO].[CommissionSales2] AS [SorMaster_CommissionSales2]
		,[SO].[CommissionSales3] AS [SorMaster_CommissionSales3]
		,[SO].[CommissionSales4] AS [SorMaster_CommissionSales4]
		,[SO].[TimeTakenToAdd] AS [SorMaster_TimeTakenToAdd]
		,[SO].[TimeTakenToChg] AS [SorMaster_TimeTakenToChg]
		,[SO].[FaxInvInBatch] AS [SorMaster_FaxInvInBatch]
		,[SO].[InterWhSale] AS [SorMaster_InterWhSale]
		,[SO].[SourceWarehouse] AS [SorMaster_SourceWarehouse]
		,[SO].[TargetWarehouse] AS [SorMaster_TargetWarehouse]
		,[SO].[DispatchesMade] AS [SorMaster_DispatchesMade]
		,[SO].[LiveDispExist] AS [SorMaster_LiveDispExist]
		,[SO].[NumDispatches] AS [SorMaster_NumDispatches]
		,[SO].[CustomerName] AS [SorMaster_CustomerName]
		,[SO].[ShipAddress1] AS [SorMaster_ShipAddress1]
		,[SO].[ShipAddress2] AS [SorMaster_ShipAddress2]
		,[SO].[ShipAddress3] AS [SorMaster_ShipAddress3]
		,[SO].[ShipAddress3Loc] AS [SorMaster_ShipAddress3Loc]
		,[SO].[ShipAddress4] AS [SorMaster_ShipAddress4]
		,[SO].[ShipAddress5] AS [SorMaster_ShipAddress5]
		,[SO].[ShipPostalCode] AS [SorMaster_ShipPostalCode]
		,[SO].[ShipToGpsLat] AS [SorMaster_ShipToGpsLat]
		,[SO].[ShipToGpsLong] AS [SorMaster_ShipToGpsLong]
		,[SO].[State] AS [SorMaster_State]
		,[SO].[CountyZip] AS [SorMaster_CountyZip]
		,[SO].[ExtendedTaxCode] AS [SorMaster_ExtendedTaxCode]
		,[SO].[MultiShipCode] AS [SorMaster_MultiShipCode]
		,[SO].[WebCreated] AS [SorMaster_WebCreated]
		,[SO].[Quote] AS [SorMaster_Quote]
		,[SO].[QuoteVersion] AS [SorMaster_QuoteVersion]
		,[SO].[GtrReference] AS [SorMaster_GtrReference]
		,[SO].[NonMerchFlag] AS [SorMaster_NonMerchFlag]
		,[SO].[Email] AS [SorMaster_Email]
		,[SO].[User1] AS [SorMaster_User1]
		,[SO].[CompanyTaxNo] AS [SorMaster_CompanyTaxNo]
		,[SO].[TpmPickupFlag] AS [SorMaster_TpmPickupFlag]
		,[SO].[TpmEvaluatedFlag] AS [SorMaster_TpmEvaluatedFlag]
		,[SO].[StandardComment] AS [SorMaster_StandardComment]
		,[SO].[DetailStatus] AS [SorMaster_DetailStatus]
		,[SO].[SalesOrderSource] AS [SorMaster_SalesOrderSource]
		,[SO].[SalesOrderSrcDesc] AS [SorMaster_SalesOrderSrcDesc]
		,[SO].[LanguageCode] AS [SorMaster_LanguageCode]
		,[SO].[ShippingLocation] AS [SorMaster_ShippingLocation]
		,[SO].[IncludeInMrp] AS [SorMaster_IncludeInMrp]
		,[SO].[TimeStamp] AS [SorMaster_TimeStamp]

		,[W].[Job] AS [WipMaster_Job]
        ,[W].[JobDescription] AS [WipMaster_JobDescription]
        ,[W].[JobClassification] AS [WipMaster_JobClassification]
        ,[W].[JobType] AS [WipMaster_JobType]
        ,[W].[MasterJob] AS [WipMaster_MasterJob]
        ,[W].[Priority] AS [WipMaster_Priority]
        ,[W].[StockCode] AS [WipMaster_StockCode]
        ,[W].[StockDescription] AS [WipMaster_StockDescription]
        ,[W].[Warehouse] AS [WipMaster_Warehouse]
        ,[W].[Customer] AS [WipMaster_Customer]
        ,[W].[CustomerName] AS [WipMaster_CustomerName]
        ,[W].[JobTenderDate] AS [WipMaster_DateJobTender]
        ,[W].[JobDeliveryDate] AS [WipMaster_DateJobDelivery]
        ,[W].[JobStartDate] AS [WipMaster_DateJobStart]
        ,[W].[ActCompleteDate] AS [WipMaster_DateActComplete]
        ,[W].[Complete] AS [WipMaster_Complete]
        ,[W].[SeqCheckReq] AS [WipMaster_SeqCheckReq]
        ,[W].[DateCalcMethod] AS [WipMaster_DateCalcMethod]
        ,[W].[ExpLabour] AS [WipMaster_ExpLabour]
        ,[W].[ExpMaterial] AS [WipMaster_ExpMaterial]
        ,[W].[QtyToMake] AS [WipMaster_QtyToMake]
        ,[W].[QtyManufactured] AS [WipMaster_QtyManufactured]
        ,[W].[Source] AS [WipMaster_Source]
        ,[W].[EstSourceNum] AS [WipMaster_EstSourceNum]
        ,[W].[NextDetailLine] AS [WipMaster_NextDetailLine]
        ,[W].[PctCompleteFlag] AS [WipMaster_PctCompleteFlag]
        ,[W].[PrtFactDoc1] AS [WipMaster_PrtFactDoc1]
        ,[W].[PrtFactDoc2] AS [WipMaster_PrtFactDoc2]
        ,[W].[PrtFactDoc3] AS [WipMaster_PrtFactDoc3]
        ,[W].[PrtFactDoc4] AS [WipMaster_PrtFactDoc4]
        ,[W].[SellingPrice] AS [WipMaster_SellingPrice]
        ,[W].[AddLabPct] AS [WipMaster_AddLabPct]
        ,[W].[AddMatPct] AS [WipMaster_AddMatPct]
        ,[W].[ProfitPct] AS [WipMaster_ProfitPct]
        ,[W].[SalesOrder] AS [WipMaster_SalesOrder]
        ,[W].[MaterialBilled] AS [WipMaster_MaterialBilled]
        ,[W].[LabourBilled] AS [WipMaster_LabourBilled]
        ,[W].[NextOpForAll] AS [WipMaster_NextOpForAll]
        ,[W].[HighestOpPosted] AS [WipMaster_HighestOpPosted]
        ,[W].[TotalQtyScrapped] AS [WipMaster_TotalQtyScrapped]
        ,[W].[ConfirmedFlag] AS [WipMaster_ConfirmedFlag]
        ,[W].[HoldFlag] AS [WipMaster_HoldFlag]
        ,[W].[JobCreatedStruc] AS [WipMaster_JobCreatedStruc]
        ,[W].[LstOrderCreated] AS [WipMaster_LstOrderCreated]
        ,[W].[TraceableType] AS [WipMaster_TraceableType]
        ,[W].[NxtLinePartBook] AS [WipMaster_NxtLinePartBook]
        ,[W].[Route] AS [WipMaster_Route]
        ,[W].[WipCtlGlCode] AS [WipMaster_WipCtlGlCode]
        ,[W].[Decimals] AS [WipMaster_Decimals]
        ,[W].[SalesOrderLine] AS [WipMaster_SalesOrderLine]
        ,[W].[MatCostToDate1] AS [WipMaster_DateMatCostTo1]
        ,[W].[MatCostToDate2] AS [WipMaster_DateMatCostTo2]
        ,[W].[MatCostToDate3] AS [WipMaster_DateMatCostTo3]
        ,[W].[LabCostToDate1] AS [WipMaster_DateLabCostTo1]
        ,[W].[LabCostToDate2] AS [WipMaster_DateLabCostTo2]
        ,[W].[LabCostToDate3] AS [WipMaster_DateLabCostTo3]
        ,[W].[HrsBookToDate1] AS [WipMaster_DateHrsBookTo1]
        ,[W].[HrsBookToDate2] AS [WipMaster_DateHrsBookTo2]
        ,[W].[HrsBookToDate3] AS [WipMaster_DateHrsBookTo3]
        ,[W].[MatValueIssues1] AS [WipMaster_MatValueIssues1]
        ,[W].[MatValueIssues2] AS [WipMaster_MatValueIssues2]
        ,[W].[MatValueIssues3] AS [WipMaster_MatValueIssues3]
        ,[W].[LabValueIssues1] AS [WipMaster_LabValueIssues1]
        ,[W].[LabValueIssues2] AS [WipMaster_LabValueIssues2]
        ,[W].[LabValueIssues3] AS [WipMaster_LabValueIssues3]
        ,[W].[NarrationNum] AS [WipMaster_NarrationNum]
        ,[W].[ReqPlnFlag] AS [WipMaster_ReqPlnFlag]
        ,[W].[DateJobLstUpd] AS [WipMaster_DateJobLstUpd]
        ,[W].[TimeJobLstUpd] AS [WipMaster_TimeJobLstUpd]
        ,[W].[HierarchyFlag] AS [WipMaster_HierarchyFlag]
        ,[W].[NextLineHier] AS [WipMaster_NextLineHier]
        ,[W].[EstTrailLoad] AS [WipMaster_EstTrailLoad]
        ,[W].[OrdEntSource] AS [WipMaster_OrdEntSource]
        ,[W].[Version] AS [WipMaster_Version]
        ,[W].[Release] AS [WipMaster_Release]
        ,[W].[AllocationLine] AS [WipMaster_AllocationLine]
        ,[W].[PurgeJob] AS [WipMaster_PurgeJob]
        ,[W].[HierarchyJob] AS [WipMaster_HierarchyJob]
        ,[W].[MrpFromJob] AS [WipMaster_MrpFromJob]
        ,[W].[MrpToJob] AS [WipMaster_MrpToJob]
        ,[W].[OrigDueDate] AS [WipMaster_DateOrigDue]
        ,[W].[GrossFlg] AS [WipMaster_GrossFlg]
        ,[W].[GrossQty] AS [WipMaster_GrossQty]
        ,[W].[ExpLabCurrent] AS [WipMaster_ExpLabCurrent]
        ,[W].[ExpMatCurrent] AS [WipMaster_ExpMatCurrent]
        ,[W].[ReservedLotSerFlag] AS [WipMaster_ReservedLotSerFlag]
        ,[W].[NotionalPart] AS [WipMaster_NotionalPart]
        ,[W].[CoProductCostMet] AS [WipMaster_CoProductCostMet]
        ,[W].[CoProductCostVal] AS [WipMaster_CoProductCostVal]
        ,[W].[CoProductType] AS [WipMaster_CoProductType]
        ,[W].[CapexCode] AS [WipMaster_CapexCode]
        ,[W].[CapexLine] AS [WipMaster_CapexLine]
        ,[W].[UomFlag] AS [WipMaster_UomFlag]
        ,[W].[ConvFactUom] AS [WipMaster_ConvFactUom]
        ,[W].[ConvMulDiv] AS [WipMaster_ConvMulDiv]
        ,[W].[ScheduleFlag] AS [WipMaster_ScheduleFlag]
        ,[W].[SchStartDate] AS [WipMaster_DateSchStart]
        ,[W].[SchStartTime] AS [WipMaster_SchStartTime]
        ,[W].[SchEndDate] AS [WipMaster_DateSchEnd]
        ,[W].[SchEndTime] AS [WipMaster_SchEndTime]
        ,[W].[QtyToMakeEnt] AS [WipMaster_QtyToMakeEnt]
        ,[W].[QtyManufacturedEnt] AS [WipMaster_QtyManufacturedEnt]
        ,[W].[TotQtyScrappedEnt] AS [WipMaster_TotQtyScrappedEnt]
        ,[W].[GrossQtyEnt] AS [WipMaster_GrossQtyEnt]
        ,[W].[ProductCode] AS [WipMaster_ProductCode]
        ,[W].[LibraryCode] AS [WipMaster_LibraryCode]
        ,[W].[TimeStamp] AS [WipMaster_TimeStamp]
        ,[W].[NestAllocs] AS [WipMaster_NestAllocs]
        ,[W].[CreatedForNest] AS [WipMaster_CreatedForNest]

		,[dt2].[ProdSchedID#] AS [dtProdSched_ProdSchedID]
        ,[dt2].[SGQuote] AS [dtProdSched_SGQuote]
        ,[dt2].[WO#] AS [dtProdSched_WO]
        ,[dt2].[InputField1] AS [dtProdSched_InputField1]
        ,[dt2].[InputField2] AS [dtProdSched_InputField2]
        ,[dt2].[Beam Line] AS [dtProdSched_BeamLine]
        ,[dt2].[Beam Date] AS [dtProdSched_DateBeam]
        ,[dt2].[GN Line] AS [dtProdSched_GNLine]
        ,[dt2].[GN Date] AS [dtProdSched_DateGN]
        ,[dt2].[WO Line 1] AS [dtProdSched_WOLine1]
        ,[dt2].[Prod Date 1] AS [dtProdSched_DateProd1]
        ,[dt2].[WO Line 2] AS [dtProdSched_WOLine2]
        ,[dt2].[Prod Date 2] AS [dtProdSched_DateProd2]
        ,[dt2].[Other] AS [dtProdSched_Other]
        ,[dt2].[Other Line] AS [dtProdSched_OtherLine]
        ,[dt2].[Other Date] AS [dtProdSched_DateOther]
        ,[dt2].[HideFromProdInput] AS [dtProdSched_HideFromProdInput]
        ,[dt2].[Step1SYSPROBudget] AS [dtProdSched_Step1SYSPROBudget]
        ,[dt2].[Step2SYSPROBudget] AS [dtProdSched_Step2SYSPROBudget]
        ,[dt2].[dtprodschedts] AS [dtProdSched_dtprodschedts]
        ,[dt2].[ApplyUpdate] AS [dtProdSched_ApplyUpdate]
        ,[dt2].[ApplyUpdateUser] AS [dtProdSched_ApplyUpdateUser]
        ,[dt2].[Slot#] AS [dtProdSched_Slot]
        ,[dt2].[Slot/Quote] AS [dtProdSched_SlotQuote]
        ,[dt2].[Slot Approved] AS [dtProdSched_SlotApproved]
        ,[dt2].[Prod On] AS [dtProdSched_ProdOn]
        ,[dt2].[Prod On Time] AS [dtProdSched_ProdOnTime]
        ,[dt2].[Prod Off] AS [dtProdSched_ProdOff]
        ,[dt2].[Prod Off Time] AS [dtProdSched_ProdOffTime]
        ,[dt2].[Prod PM] AS [dtProdSched_ProdPM]
        ,[dt2].[Prod Complete] AS [dtProdSched_ProdComplete]
        ,[dt2].[Prod2 On] AS [dtProdSched_Prod2On]
        ,[dt2].[Prod2 On Time] AS [dtProdSched_Prod2OnTime]
        ,[dt2].[Prod2 Off] AS [dtProdSched_Prod2Off]
        ,[dt2].[Prod2 Off Time] AS [dtProdSched_Prod2OffTime]
        ,[dt2].[Prod2 PM] AS [dtProdSched_Prod2PM]
        ,[dt2].[Prod2 Complete] AS [dtProdSched_Prod2Complete]
        ,[dt2].[Prod Instructions] AS [dtProdSched_ProdInstructions]
        ,[dt2].[Beam On] AS [dtProdSched_BeamOn]
        ,[dt2].[Beam Off] AS [dtProdSched_BeamOff]
        ,[dt2].[Beam Complete] AS [dtProdSched_BeamComplete]
        ,[dt2].[Beam PM] AS [dtProdSched_BeamPM]
        ,[dt2].[Beam Instructions] AS [dtProdSched_BeamInstructions]
        ,[dt2].[GN On] AS [dtProdSched_GNOn]
        ,[dt2].[GN Off] AS [dtProdSched_GNOff]
        ,[dt2].[GN Complete] AS [dtProdSched_GNComplete]
        ,[dt2].[GN PM] AS [dtProdSched_GNPM]
        ,[dt2].[GN Instructions] AS [dtProdSched_GNInstructions]
        ,[dt2].[Axle] AS [dtProdSched_Axle]
        ,[dt2].[Axle On] AS [dtProdSched_AxleOn]
        ,[dt2].[Axle Off] AS [dtProdSched_AxleOff]
        ,[dt2].[Axle Complete] AS [dtProdSched_AxleComplete]
        ,[dt2].[Axle PM] AS [dtProdSched_AxlePM]
        ,[dt2].[Axle Instructions] AS [dtProdSched_AxleInstructions]
        ,[dt2].[Other On] AS [dtProdSched_OtherOn]
        ,[dt2].[Other On Time] AS [dtProdSched_OtherOnTime]
        ,[dt2].[Other Off] AS [dtProdSched_OtherOff]
        ,[dt2].[Other Off Time] AS [dtProdSched_OtherOffTime]
        ,[dt2].[Other Complete] AS [dtProdSched_OtherComplete]
        ,[dt2].[Other PM] AS [dtProdSched_OtherPM]
        ,[dt2].[Other Instructions] AS [dtProdSched_OtherInstructions]
        ,[dt2].[Stargate WO#] AS [dtProdSched_StargateWO]
		
		,(CASE 
			WHEN [O2].[Quote Date] IS NULL THEN NULL
			ELSE DATEDIFF(YEAR, [O2].[Quote Date], GETDATE())
		END) AS [YearGroup]
		,(CASE 
			WHEN [O2].[Quote Date] IS NULL THEN NULL
			ELSE DATEDIFF(MONTH, [O2].[Quote Date], GETDATE())
		END) AS [MonthGroup]
		,DATEPART(WEEKDAY, [O2].[Quote Date]) AS [QuoteWeekday]
		,DATEDIFF(DAY, [O2].[Quote Date], [O2].[Order Date]) AS [DaysQuoteToOrder]
		,DATEDIFF(DAY, [O2].[Quote Date], [O2].[Delivery Date]) AS [DaysQuoteToDelivery]
		,DATEDIFF(DAY, [O2].[Order Date], [O2].[Delivery Date]) AS [DaysOrderToDelivery]
		,DATEDIFF(DAY, [O2].[Quote Date], [O2].[Date Declined]) AS [DaysQuoteToDecline]

	FROM
		[OrdersV2] AS [O2] WITH (NOLOCK)
	LEFT JOIN
		[DealersV2] AS [D2] WITH (NOLOCK)
	ON
		[O2].[DealerID] = [D2].[ID]
	LEFT JOIN
		[ProductsV2] AS [P2] WITH (NOLOCK)
	ON
		[O2].[ProductID] = [P2].[IDTrailer]
	LEFT JOIN
		[Sales Staff] AS [SS] WITH (NOLOCK)
	ON
		[O2].[Sale PersonID] = [SS].[ID-SaleStaff]
	LEFT JOIN
		[SysproCompanyS].[dbo].[SorMaster] AS [SO] WITH (NOLOCK)
	ON
		[O2].[Sales Order#] = [SO].[SalesOrder]
	LEFT JOIN
		[SysproCompanyS].[dbo].[WipMaster] AS [W] WITH (NOLOCK)
	ON
		CAST([O2].[WO#] AS NVARCHAR(MAX)) = [W].[Job]
	LEFT JOIN
		[Stargatedb].[dbo].[dtProductionSchedule] AS [dt2]
	ON
		[O2].[SGQuote] = [dt2].[SGQuote]
		AND [O2].[CompanyID] = 0
--) AS [Src]
--ORDER BY
--	[Orders_DateQuote]
--;

GO


