/****** 2023-12-06 1657 ******/

CREATE VIEW [v_SFC_BWSUnionSTGDealers] AS

SELECT
	'DealersV2' AS [OGTable]
	,[ID]
	,[COMPANY NAME]
	,[ADDRESS]
	,[CITY]
	,[PROVINCE]
	,[POSTAL CODE]
	,[PHONE]
	,[TOLL FREE]
	,[FAX]
	,[CONTACT]
	,[CELL]
	,[EMAIL]
	,[DEALER NUMBER]
	,[CURRENT DEALER]
	,[CURRENT DEALER CDN]
	,[CURRENT DEALER US]
	,[Invoice]
	,[Eastern Canada]
	,[Eastern US]
	,[Central Canada]
	,[Central US]
	,[Western Canada]
	,[Western US]
	,[American]
	,[Proprietary/Direct/Other]
	,[Initials]
	,[dealers_timestamp]
	,[DataEntryCheck]
	,[DataEntryUser]
	,[DefaultPayID]
	,[SendDealerStatusEmail?]
	,[CompanyID]
	,[SlotsRequestedPerMonth]
FROM
	[BWSdb].[dbo].[DealersV2]

UNION ALL

SELECT
	'Dealers' AS [OGTable]
	,[ID]
	,[COMPANY NAME]
	,[ADDRESS]
	,[CITY]
	,[PROVINCE]
	,[POSTAL CODE]
	,[PHONE]
	,[TOLL FREE]
	,[FAX]
	,[CONTACT]
	,[CELL]
	,[EMAIL]
	,[DEALER NUMBER]
	,[CURRENT DEALER]
	,[CURRENT DEALER CDN]
	,[CURRENT DEALER US]
	,[Invoice]
	,[Eastern Canada]
	,[Eastern US]
	,[Central Canada]
	,[Central US]
	,[Western Canada]
	,[Western US]
	,[American]
	,[Proprietary/Direct/Other]
	,[Initials]
	,[dealers_timestamp]
	,[DataEntryCheck]
	,[DataEntryUser]
	,[DefaultPayID]
	,[SendDealerStatusEmail?]
	,[SlotsRequestedPerMonth]
	,[CompanyID]
FROM
	[BWSdb].[dbo].[Dealers]

;