USE [BWSdb]
GO

--/****** Object:  View [dbo].[v_SFC_BWSUnionSTGOrders]    Script Date: 2023-11-21 5:50:28 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--/****** Script for SelectTopNRows command from SSMS  ******/

--ALTER VIEW [dbo].[v_SFC_BWSUnionSTGOrders] AS

SELECT
	[OrderID] AS [TableOrderID]
	,'OrdersV2' AS [OriginTable]
	,[SGQuote] AS [QuoteNum]
	,[Quote Date] AS [DateQuote]
	,[Order Date] AS [DateOrder]
	,[WO#] AS [WONum]
	,[Sales Order#] AS [SaledOrderNum]
	,[Model No] AS [ModelNo]
	,[Width]
	,[Spread]
	,[DealerID]
	,[Sale PersonID] AS [IDSalesPerson]
	,[Price]
	,[Prom Drawing] AS [PromoDrawing]
	,[Special Instructions] AS [SpecialInstructions]
	,[Date Declined] AS [DateDeclined]
	,[Decline/Rejected] AS [Decline_Rejected]
	,[Serial Number] AS [SerialNumber]
	,[Available Date] AS [DateAvailable] 
	,[Delivery Date] AS [DateDelivery]
	,[Requested Delivery Date] AS [DateRequestedDelivery]
	,[Finish Date] AS [DateFinish]
	,[Purchase Order] AS [PurchaseOrder]
	,[PO Date] AS [DatePO]
	,[PayID]
	,[Volume Discount] AS [VolumeDiscount]
	,[Program Discount] AS [ProgramDiscount]
	,[Discount1_Name]
	,[Discount1_Type]
	,[Discount1]
	,[Discount2_Name]
	,[Discount2_Type]
	,[Discount2]
	,[Discount3_Name]
	,[Discount3_Type]
	,[Discount3]
	,[Est Pro Date] AS [DateEstPro]
	,[Notes]
	,[EngNotes]
	,[CarrierID]
	,[CustID]
	,[US Sale] AS [USSale]
	,[Shipped Date] AS [DateShipped]
	,[GL Override Date] AS [DateGLOverride]
	,[FE Rate] AS [FERate]
	,[PDD]
	,[Deck Length] AS [DeckLength]
	,[Invoice #] AS [InvoiceNum]
	,[Date Registered] AS [DateRegistered]
	,[Date In Service] AS [DateInService]
	,[Invoice Date] AS [DateInvoice]
	,[Date Requested] AS [DateRequested]
	,[GVWR]
	,[Tare]
	,[Selection]
	,[Warranty]
	,[BWSPaid]
	,[BWSPaidDate]
	,[CommPaid]
	,[CommPaidDate]
	,[ts_timestamp]
	,[ModifiedBy]
	,[Lead Date] AS [DateLead]
	,[Lead Source] AS [LeadSource]
	,[LeadID]
	,[DealerBranchID]
	,[DealerSalesPersonID]
	,[DataEntryCheck]
	,[DataEntryUser]
	,[FinishedGoodsDealerLocID]
	,[WO Reviewed] AS [WOReviewed]
	,[WO Review Date] AS [DateWOReview]
	,[Follow Up Date] AS [DateFollowUp]
	,[MSOIsDifferent]
	,[MSOLocID]
	,[EstInvDateOverride]
	,[Estimated Invoice Date] AS [DateInvoiceEstimated]
	,[AdditionalPricingInfo]
	,[Slot#] AS [SlotNum]
	,[TempModel?] AS [TempModel]
	,[HighRiskUnit]
	,[EngNotes V2] AS [EngNotesV2]
	,[CompanyID]
	,[Customer WO#] AS [CustomerWONum]
	,[PriceSecured]
	,[DateSecured]
	,[SecuredBy]
	,[InternalSalesComments]
	,[InternalSalesCommentDate]
	,[InternalSalesCommenter]
	,[DiscountSetDate] AS [DateDiscountSet]
	,[DiscountSetBy]
	,[ProductID]
	,[DiscountID]
FROM 
	[BWSdb].[dbo].[OrdersV2]

UNION ALL

SELECT
	ROW_NUMBER() OVER(
		PARTITION BY [Quote#]
		ORDER BY [Quote#]
	) AS [OrderID]
	,'Orders' AS [OriginTable]
	,CAST([Quote#] AS NVARCHAR(MAX))
	,[Quote Date]
	,[Order Date]
	,[WO#]
	,[Sales Order#]
	,[Model No]
	,[Width]
	,[Spread]
	,[DealerID]
	,[Sale PersonID]
	,[Price]
	,[Prom Drawing]
	,[Special Instructions]
	,[Date Declined]
	,[Decline/Rejected]
	,[Serial Number]
	,[Available Date]
	,[Delivery Date]
	,[Requested Delivery Date]
	,[Finish Date]
	,[Purchase Order]
	,[PO Date]
	,[PayID]
	,[Volume Discount]
	,[Program Discount]
	,[Discount1_Name]
	,[Discount1_Type]
	,[Discount1]
	,[Discount2_Name]
	,[Discount2_Type]
	,[Discount2]
	,[Discount3_Name]
	,[Discount3_Type]
	,[Discount3]
	,[Est Pro Date]
	,[Notes]
	,[EngNotes]
	,[CarrierID]
	,[CustID]
	,[US Sale]
	,[Shipped Date]
	,[GL Override Date]
	,[FE Rate]
	,[PDD]
	,[Deck Length]
	,[Invoice #]
	,[Date Registered]
	,[Date In Service]
	,[Invoice Date]
	,[Date Requested]
	,[GVWR]
	,[Tare]
	,[Selection]
	,[Warranty]
	,[BWSPaid]
	,[BWSPaidDate]
	,[CommPaid]
	,[CommPaidDate]
	,[ts_timestamp]
	,[ModifiedBy]
	,[Lead Date]
	,[Lead Source]
	,[LeadID]
	,[DealerBranchID]
	,[DealerSalesPersonID]
	,[DataEntryCheck]
	,[DataEntryUser]
	,[FinishedGoodsDealerLocID]
	,[WO Reviewed]
	,[WO Review Date]
	,[Follow Up Date]
	,[MSOIsDifferent]
	,[MSOLocID]
	,[EstInvDateOverride]
	,[Estimated Invoice Date]
	,[AdditionalPricingInfo]
	,[Slot#]
	,[TempModel?]
	,[HighRiskUnit]
	,[EngNotes V2]
	,[CompanyID]
	,[Customer WO#]
	,[PriceSecured]
	,[DateSecured]
	,[SecuredBy]
	,[InternalSalesComment]
	,[InternalSalesCommentDate]
	,[InternalSalesCommenter]
	,[DiscountSetDate]
	,[DiscountSetBy]
	,[ProductID]
	,[DiscountID]
FROM
	[Orders]
GO


