USE BWSdb
GO

SELECT
	*
FROM
	[SysproCompanyA].[dbo].[v_CalendarWorkDays]
WHERE
	[WorkDay] = 1
	AND [CalendarDate] BETWEEN DATEADD(DAY, -6, GETDATE()) AND DATEADD(DAY, 5, GETDATE())
;

SELECT
	GETDATE(), 5, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), 5)
UNION
SELECT
	GETDATE(), 4, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), 4)
UNION
SELECT
	GETDATE(), 3, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), 3)
UNION
SELECT
	GETDATE(), 2, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), 2)
UNION
SELECT
	GETDATE(), 1, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), 1)
UNION
SELECT
	GETDATE(), 0, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), 0)
UNION
SELECT
	GETDATE(), -1, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -1)
UNION
SELECT
	GETDATE(), -2, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -2)
UNION
SELECT
	GETDATE(), -3, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -3)
UNION
SELECT
	GETDATE(), -4, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -4)
UNION
SELECT
	GETDATE(), -5, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -5)
UNION
SELECT
	GETDATE(), -6, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -6)
UNION
SELECT
	GETDATE(), -7, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -7)
UNION
SELECT
	GETDATE(), -8, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -8)
UNION
SELECT
	GETDATE(), -9, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -9)
UNION
SELECT
	GETDATE(), -10, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -10)
UNION
SELECT
	GETDATE(), -11, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -11)
UNION
SELECT
	GETDATE(), -12, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -12)
UNION
SELECT
	GETDATE(), -13, [dbo].[NEXT_BUSINESS_DAY](GETDATE(), -13)