SELECT
	[Curr].[SGQuote],
	[Curr].[WO#],
	[Curr].[Available Date] AS [Curr Available Date],
	[Old].[Available Date] AS [Old Available Date],
	[Curr].[JobAvailableLine] AS [Curr Line],
	[Old].[JobAvailableLine] AS [Old Line],
	[Curr].[JobAvailableScheduled] AS [Curr Scheduled On],
	[Old].[JobAvailableScheduled] AS [Old Scheduled On],
	[Curr].[JobAvailableScheduledBy] AS [Curr Sched By],
	[Old].[JobAvailableScheduledBy] AS [Old Sched By],
	(CASE
		WHEN [Curr].[JobAvailableLine] <> [Old].[JobAvailableLine] THEN 
			(CASE 
				WHEN [Curr].[Available Date] <> [Old].[Available Date] THEN 'New Line & New Date'
				ELSE 'New Line & Same Date'
			END)
		ELSE 
		(CASE
			WHEN [Curr].[Available Date] <> [Old].[Available Date] THEN 'Same Line & New Date'
			ELSE
				(CASE
					WHEN [Curr].[JobAvailableScheduledBy] <> [Old].[JobAvailableScheduledBy] THEN 'Rescheduled by a new user'
					ELSE
						(CASE
							WHEN [Curr].[JobAvailableScheduled] <> [Old].[JobAvailableScheduled] THEN 'Rescheduled at a later time'	
							ELSE 'No Change'
						END)
				END)
		END)
	END) AS [Change]
FROM (
	SELECT
		[OrderID]
		,[SGQuote]
		,[Quote Date]
		,[Order Date]
		,[WO#]
		,[Sales Order#]
		,[Model No]
		,[Width]
		,[Spread]
		,[DealerID]
		,[Sale PersonID]
		,[Price]
		,[Prom Drawing]
		,[Special Instructions]
		,[Date Declined]
		,[Decline/Rejected]
		,[Serial Number]
		,[Available Date]
		,[Delivery Date]
		,[Requested Delivery Date]
		,[Finish Date]
		,[Purchase Order]
		,[PO Date]
		,[PayID]
		,[Volume Discount]
		,[Program Discount]
		,[Discount1_Name]
		,[Discount1_Type]
		,[Discount1]
		,[Discount2_Name]
		,[Discount2_Type]
		,[Discount2]
		,[Discount3_Name]
		,[Discount3_Type]
		,[Discount3]
		,[Est Pro Date]
		,[Notes]
		,[EngNotes]
		,[CarrierID]
		,[CustID]
		,[US Sale]
		,[Shipped Date]
		,[GL Override Date]
		,[FE Rate]
		,[PDD]
		,[Deck Length]
		,[Invoice #]
		,[Date Registered]
		,[Date In Service]
		,[Invoice Date]
		,[Date Requested]
		,[GVWR]
		,[Tare]
		,[Selection]
		,[Warranty]
		,[BWSPaid]
		,[BWSPaidDate]
		,[CommPaid]
		,[CommPaidDate]
		,[ts_timestamp]
		,[ModifiedBy]
		,[Lead Date]
		,[Lead Source]
		,[LeadID]
		,[DealerBranchID]
		,[DealerSalesPersonID]
		,[DataEntryCheck]
		,[DataEntryUser]
		,[FinishedGoodsDealerLocID]
		,[WO Reviewed]
		,[WO Review Date]
		,[Follow Up Date]
		,[MSOIsDifferent]
		,[MSOLocID]
		,[EstInvDateOverride]
		,[Estimated Invoice Date]
		,[AdditionalPricingInfo]
		,[Slot#]
		,[TempModel?]
		,[HighRiskUnit]
		,[EngNotes V2]
		,[CompanyID]
		,[Customer WO#]
		,[PriceSecured]
		,[DateSecured]
		,[SecuredBy]
		,[InternalSalesComments]
		,[InternalSalesCommentDate]
		,[InternalSalesCommenter]
		,[DiscountSetDate]
		,[DiscountSetBy]
		,[ProductID]
		,[DiscountID]
		,[DateLastQuoteReport]
		,[JobAvailableLine]
		,[JobAvailableScheduled]
		,[JobAvailableScheduledBy]
	FROM
		[BWSdb_20240716].[dbo].[OrdersV2]
	WHERE
		[JobAvailableScheduledBy] IS NOT NULL
) AS [Old]
INNER JOIN (
	SELECT
		[OrderID]
		,[SGQuote]
		,[Quote Date]
		,[Order Date]
		,[WO#]
		,[Sales Order#]
		,[Model No]
		,[Width]
		,[Spread]
		,[DealerID]
		,[Sale PersonID]
		,[Price]
		,[Prom Drawing]
		,[Special Instructions]
		,[Date Declined]
		,[Decline/Rejected]
		,[Serial Number]
		,[Available Date]
		,[Delivery Date]
		,[Requested Delivery Date]
		,[Finish Date]
		,[Purchase Order]
		,[PO Date]
		,[PayID]
		,[Volume Discount]
		,[Program Discount]
		,[Discount1_Name]
		,[Discount1_Type]
		,[Discount1]
		,[Discount2_Name]
		,[Discount2_Type]
		,[Discount2]
		,[Discount3_Name]
		,[Discount3_Type]
		,[Discount3]
		,[Est Pro Date]
		,[Notes]
		,[EngNotes]
		,[CarrierID]
		,[CustID]
		,[US Sale]
		,[Shipped Date]
		,[GL Override Date]
		,[FE Rate]
		,[PDD]
		,[Deck Length]
		,[Invoice #]
		,[Date Registered]
		,[Date In Service]
		,[Invoice Date]
		,[Date Requested]
		,[GVWR]
		,[Tare]
		,[Selection]
		,[Warranty]
		,[BWSPaid]
		,[BWSPaidDate]
		,[CommPaid]
		,[CommPaidDate]
		,[ts_timestamp]
		,[ModifiedBy]
		,[Lead Date]
		,[Lead Source]
		,[LeadID]
		,[DealerBranchID]
		,[DealerSalesPersonID]
		,[DataEntryCheck]
		,[DataEntryUser]
		,[FinishedGoodsDealerLocID]
		,[WO Reviewed]
		,[WO Review Date]
		,[Follow Up Date]
		,[MSOIsDifferent]
		,[MSOLocID]
		,[EstInvDateOverride]
		,[Estimated Invoice Date]
		,[AdditionalPricingInfo]
		,[Slot#]
		,[TempModel?]
		,[HighRiskUnit]
		,[EngNotes V2]
		,[CompanyID]
		,[Customer WO#]
		,[PriceSecured]
		,[DateSecured]
		,[SecuredBy]
		,[InternalSalesComments]
		,[InternalSalesCommentDate]
		,[InternalSalesCommenter]
		,[DiscountSetDate]
		,[DiscountSetBy]
		,[ProductID]
		,[DiscountID]
		,[DateLastQuoteReport]
		,[JobAvailableLine]
		,[JobAvailableScheduled]
		,[JobAvailableScheduledBy]
	FROM
		[BWSdb].[dbo].[OrdersV2]
	WHERE
		[JobAvailableScheduledBy] IS NOT NULL
) AS [Curr]
ON
	[Old].[SGQuote] = [Curr].[SGQuote]
WHERE
	([Curr].[Available Date] <> [Old].[Available Date])
	OR ([Curr].[JobAvailableLine] <> [Old].[JobAvailableLine])
	OR ([Curr].[JobAvailableScheduled] <> [Old].[JobAvailableScheduled])
	OR ([Curr].[JobAvailableScheduledBy] <> [Old].[JobAvailableScheduledBy])
ORDER BY
	[Curr].[JobAvailableScheduled]
