SELECT [UpdateID]
      ,[UpdateDate]
      ,[SGQuote]
      ,[UpdaterName]
      ,[NewAvailableDate]
      ,[NewLine]
      ,[OldAvailableDate]
      ,[OldLine]
  FROM [Stargatedb].[dbo].[PDS Updates]
