import datetime
from dataclasses import dataclass


@dataclass
class Unit:

    # [Stargatedb].[dbo].[dtProductionSchedule]
    prod_sched_id: int
    quote: str
    wo_num: str
    InputField1: str  # Model No
    InputField2: str  # Customer Name
    Beam_Line: str
    Beam_Date: datetime.datetime
    GN_Line: str
    GN_Date: datetime.datetime
    WO_Line_1: str
    Prod_Date_1: datetime.datetime
    WO_Line_2: str
    Prod_Date_2: datetime.datetime
    Other: str
    Other_Line: str
    Other_Date: datetime.datetime
    HideFromProdInput: bool
    Step1SYSPROBudget: float
    Step2SYSPROBudget: float
    dtprodschedts: str
    ApplyUpdate: int
    ApplyUpdateUser: str
    Slot: int
    Slot_Quote: bool
    Slot_Approved: bool
    Prod_On: datetime.datetime
    Prod_On_Time: float
    Prod_Off: datetime.datetime
    Prod_Off_Time: float
    Prod_PM: bool
    Prod_Complete: bool
    Prod2_On: datetime.datetime
    Prod2_On_Time: float
    Prod2_Off: datetime.datetime
    Prod2_Off_Time: float
    Prod2_PM: bool
    Prod2_Complete: bool
    Prod_Instructions: str
    Beam_On: datetime.datetime
    Beam_Off: datetime.datetime
    Beam_Complete: bool
    Beam_PM: bool
    Beam_Instructions: str
    GN_On: datetime.datetime
    GN_Off: datetime.datetime
    GN_Complete: bool
    GN_PM: bool
    GN_Instructions: str
    Axle: datetime.datetime
    Axle_On: datetime.datetime
    Axle_Off: datetime.datetime
    Axle_Complete: bool
    Axle_PM: bool
    Axle_Instructions: str
    Other_On: datetime.datetime
    Other_On_Time: float
    Other_Off: datetime.datetime
    Other_Off_Time: float
    Other_Complete: bool
    Other_PM: bool
    Other_Instructions: str
    Stargate_WO: str

    # [BWSdb].[dbo].[Orders]
    OrderID: int
    SGQuote: str
    Quote_Date: datetime.datetime
    Order_Date: datetime.datetime
    WO: str
    Sales_Order: int
    Model_No: str
    Width: int
    Spread: int
    DealerID: int
    Sale_PersonID: int
    Price: float
    Prom_Drawing: str
    Special_Instructions: str
    Date_Declined: datetime.datetime
    Decline_Rejected: int
    Serial_Number: str
    Available_Date: datetime.datetime
    Delivery_Date: datetime.datetime
    Requested_Delivery_Date: datetime.datetime
    Finish_Date: datetime.datetime
    Purchase_Order: str
    PO_Date: datetime.datetime
    PayID: int
    Volume_Discount: float
    Program_Discount: float
    Discount1_Name: str
    Discount1_Type: str
    Discount1: float
    Discount2_Name: str
    Discount2_Type: str
    Discount2: float
    Discount3_Name: str
    Discount3_Type: str
    Discount3: float
    Est_Pro_Date: datetime.datetime
    Notes: str
    EngNotes: str
    CarrierID: int
    CustID: int
    US_Sale: bool
    Shipped_Date: datetime.datetime
    GL_Override_Date: datetime.datetime
    FE_Rate: float
    PDD: datetime.datetime
    Deck_Length: int
    Invoice: str
    Date_Registered: datetime.datetime
    Date_In_Service: datetime.datetime
    Invoice_Date: datetime.datetime
    Date_Requested: datetime.datetime
    GVWR: int
    Tare: int
    Selection: bool
    Warranty: bool
    BWSPaid: bool
    BWSPaidDate: datetime.datetime
    CommPaid: bool
    CommPaidDate: datetime.datetime
    ts_timestamp: str
    ModifiedBy: str
    Lead_Date: datetime.datetime
    Lead_Source: str
    LeadID: int
    DealerBranchID: int
    DealerSalesPersonID: int
    DataEntryCheck: int
    DataEntryUser: str
    FinishedGoodsDealerLocID: int
    WO_Reviewed: bool
    WO_Review_Date: datetime.datetime
    Follow_Up_Date: datetime.datetime
    MSOIsDifferent: bool
    MSOLocID: int
    EstInvDateOverride: bool
    Estimated_Invoice_Date: datetime.datetime
    AdditionalPricingInfo: str
    Slot_Orders: int
    TempModel: bool
    HighRiskUnit: bool
    EngNotes_V2: str
    CompanyID: int
    Customer_WO: int
    PriceSecured: bool
    DateSecured: datetime.datetime
    SecuredBy: str
