
non_current = 0
current = 1

models = {
    "Agriculture": [
        ("LP14", "14 Ft Land Pro", non_current),
        ("LP18", "18 Ft Land Pro", current),
        ("PD14", "14 Ft Production Dozer", current),
        ("PD16", "16 Ft Production Dozer", current),
        ("PD18", "18 Ft Production Dozer", current)
    ],
    "Cable Reel": [
        ("14CR1X", "14 ft. Single Axle Cable Reel", current)
    ],
    "Chassis": [
        ("12CC2X", "12 Ft. Tandem Container Chassis", non_current),
        ("20PC2X", "20 Ft. Tandem Electric Brake", non_current),
        ("27CC2X", "27 ft. Tandem Pull B-Train", current),
        ("27CC3X", "27 ft. Tridem Lead B-Train", current),
        ("30CC2X", "30 Ft. Tandem Container Chassis", non_current),
        ("30PC3X", "30 Ft. Tridem Electric Brake", non_current),
        ("40CC3X", "40 ft. Container Chassis", current),
        ("40CC3X53EXT", "40 ft. Extendible Container Chassis", current),
        ("42CC3X", "42 Ft. Container Chassis", current),
        ("Pony 3X17", "Pony Trailer Quad", current)
    ],
    "Container Chassis": [
        ("10GT1X", "Single Axle - Glass", current),
        ("10GT2X", "Tandem - Glass", non_current),
        ("12GT1X", "Single Axle - Glass", non_current),
        ("12GT2X", "Tandem - Glass", current),
        ("20VT1V Mexico", "20 ft. 1 Van - DCI Mexico", non_current),
        ("25VT2V DCI", "25 ft. 2 Van - DCI", non_current),
        ("26VT1V Mexico", "26 ft. Single Axle", non_current),
        ("30DT3X-CHASSIS", "30 ft. Dump Chassis", non_current),
        ("33VT2V DCI Tag", "33 ft. 2 Van - DCI Tag", current),
        ("34VT1V Hostler", "34 ft. Single Axle", non_current),
        ("38GT1X", "38 ft. Single Axle - Glass", non_current),
        ("38GT2X", "38 ft. Tandem - Glass", non_current),
        ("40CC2X", "40 ft. Tandem", non_current),
        ("40GT1X", "40 ft. Single Axle - Glass", non_current),
        ("40GT2X", "40 ft. Tandem - Glass", current),
        ("40VT2V Mexico", "40 ft. 2 Van - DCI Mexico", current),
        ("42VT2V Mexico", "42 ft. 2 Van - DCI Mexico", non_current),
        ("47GT2X", "47 ft. Tandem - Glass", non_current),
        ("48GT2X", "48 ft. Tandem - Glass", non_current),
        ("51GT2X", "51 ft. Tandem - Glass", non_current),
        ("51VT2V DCI", "51 ft. 2 Van - DCI", non_current),
        ("51VT4V DCI", "51' 4 Van - DCI", current),
        ("53VT2V CAL", "53 ft. 2 Van - California", current),
        ("53VT2V DCI", "53 ft. 2 Van - DCI", current),
        ("53VT2V DCI LD", "53 ft. 2 Van - DCI Low Deck", non_current),
        ("53VT2V FL CA", "53 ft. 2 Van - Frito Lay Canada", current),
        ("53VT2V FL CA-53", "53 ft. 2 Van - Frito Lay Canada", current),
        ("53VT2V FL CA-97", "53 ft. 2 Van - Frito Lay Canada", current),
        ("53VT2V FL US", "53 ft. 2 Van - Tandem Axle Truck Frito Lay US", non_current),
        ("53VT2V FL US-97", "53 ft. 2 Van - Tandem Axle Truck Frito Lay US", current),
        ("53VT2V Frito Lay", "53 ft. 2 Van - DCI Frito Lay", non_current),
        ("53VT2V JB HUNT", "53 ft. 2 Van - J.B. Hunt", current),
        ("53VT2V Penske", "53 ft. 2 Van - DCI PENSKE", current),
        ("53VT2VSAT Frito Lay US 2018", "53 ft. 2 Van - Single Axle Truck Frito Lay US", non_current),
        ("53VT2VTAT Frito Lay US 2018", "53 ft. 2 Van - Tandem Axle Truck Frito Lay US", non_current),
        ("53VT3V DCI", "53 ft. 3 Van - DCI", current),
        ("53VT3V PENSKE", "53 ft. 3 Van - PENSKE", current),
        ("53VT3X DCI V2021", "53 ft. 3 Van - DCI", current)
    ],
    "Converters/Boosters": [
        ("11CD1X", "11 Ton Single Axle Convertor Dolly", non_current),
        ("11SB1X", "11 Ton Steer Single Axle Booster", current),
        ("11SB1X SB", "11 Ton Steer Single Axle Booster", non_current),
        ("11SB2X SB", "11 Ton Steer Tandem Axle Booster", non_current),
        ("22CD2X", "22 Ton Converter Dolly Tandem", non_current)
    ],
    "Dump": [
        ("26DT2X", "26 ft. Tandem 1/4 Frame U-Body", non_current),
        ("27DT2X", "27 ft. Tandem 1/4 Frame U-Body", non_current),
        ("27DT2X HV", "27 ft. Tandem 1/4 Frame U-Body High Volume", non_current),
        ("27DT2X V2018", "27 ft. Tandem 1/4 Frame U-Body", current),
        ("27DT2XU", "27 ft. Tandem 1/4 Frame U-Body", non_current),
        ("27PD2X", "28 ft. Tandem Pup Dump", non_current),
        ("28DPT2X", "28 ft. Tandem Pup Chassie", non_current),
        ("28DPT3X", "28 ft. Tridem Pup Chassie", non_current),
        ("32DT3X", "32 ft. Tridem 1/4 Frame U-Body", non_current),
        ("32DT3X V2018", "32 ft. Tridem 1/4 Frame U-Body", current),
        ("36ALB2X", "36 ft. Tandem", non_current),
        ("37DT2X", "37 ft.Tandem 1/4 Frame U-Body", non_current),
        ("37DT2X HV", "37 ft.Tandem 1/4 Frame U-Body, High Volume", non_current),
        ("37DT3X", "37 ft. Tridem 1/4 Frame U-Body", current),
        ("37DT4X FF", "37 ft. Tridem Full Frame U-Body", non_current),
        ("38ALB3XS", "38 ft. Triaxle", non_current),
        ("39ALB3X", "39 ft. Tridem", non_current),
        ("41ALB3X", "41 ft. Tridem", non_current),
        ("48ALB4X", "48 ft. QUAD-SPIF", non_current),
        ("53EWF4X", "53Ft. Quad Elliptical Walking Floor Transfer Trailer", current),
        ("SFUB2X", "U-Body Frameless Steel Scrap Tandem Dump", non_current),
        ("SPECIAL", "PROPOSED", non_current)
    ],
    "End Dumps": [
        ("End Dump 4X", "End Dump 4X", current),
        ("Frameless Alum. U Body 2X", "Frameless Alum. U Body 2X", current),
        ("Frameless Alum. U Body 3X", "Frameless Alum. U Body 3X", current)
    ],
    "Equipment": [
        ("42ET2X", "42 ft. Tandem", current),
        ("42ET3X", "42 ft. Tridem", current),
        ("48ET2X", "48 ft. Tandem", current),
        ("48ET3X", "48 ft. Tridem", current),
        ("48ET3X MR", "48 ft. Tridem Manual Ramp", non_current),
        ("53ET2X", "53 ft. Tandem", current),
        ("53ET3X", "53 ft. Tridem", current),
        ("53ET3X MR EAST", "53 ft. Tridem Manual Ramp", current),
        ("53ET3X MR WEST", "53 ft. Tridem Manual Ramp", current),
        ("53ET4X", "53 ft. Quad", current),
        ("53ET4X MR", "53 ft. Quad Manual Ramp", current)
    ],
    "Highway": [
        ("28HBT2X", "28 ft. Tandem Pull B-Train - Lumber Spec", current),
        ("28HBT2X 2018", "28 ft. Tandem Pull B-Train", current),
        ("28HBT2XHD", "28 ft. Tandem Pull B-Train - Heavy Duty Spec", non_current),
        ("28HBT3X", "28 ft. Tridem Pull B Train", current),
        ("29HD3X Rail", "29 ft. Tridem Drop Deck, Rail", non_current),
        ("32HBT3X", "32 ft.Tridem Lead B-Train - Lumber Spec", current),
        ("32HBT3X 2018", "32 ft. Tridem Lead B-Train", current),
        ("32HBT3XHD", "32 ft. Tridem Lead B-Train - Heavy Duty Spec", non_current),
        ("32HBT4X", "32 ft. Quad Lead B-Train", current),
        ("35HD2X", "35 ft. Tandem Drop Deck", non_current),
        ("40HD2X Penske CUSTOM", "40 ft. Tandem Drop Deck - Penske Custom", current),
        ("40HD3XB", "40 Ft. Tridem Drop Deck", non_current),
        ("42HD2X HD", "42 FT. Tandem Heavy Duty Drop Deck", non_current),
        ("42HD3X 2018", "42 ft. Tridem Drop Deck", non_current),
        ("42HD3X HD", "42 FT. Tridem Heavy Duty Drop Deck", non_current),
        ("42HF2X", "42 ft. Tridem Flat Deck - Single Tire", non_current),
        ("42HF3X HD", "42 ft. Tridem Flat Deck - Single Tire", non_current),
        ("45HD2X", "45 ft. Tandem Drop Deck", non_current),
        ("46HDD2X Custom", "46 ft. Tandem Double Drop Deck - Custom", non_current),
        ("48HD2X", "48 ft. Tandem Drop Deck", non_current),
        ("48HD2X SPECIAL", "48 ft. Tandem Drop Deck", non_current),
        ("48HD3X", "48 ft. Tridem Drop Deck", current),
        ("48HD5X", "48 ft. Five Drop Deck", non_current),
        ("48HDD2X", "48 ft. Tridem Double Drop Deck", non_current),
        ("48HDD2X Custom", "48 ft. Tandem Double Drop Deck - Custom", non_current),
        ("48HDD2X Custom V1", "48 ft. Tandem Double Drop Deck - Custom Ver. 1", non_current),
        ("48HDD2X EXT", "48 ft. Tandem Doubel Drop Deck Extendable", current),
        ("48HDD3X", "48 ft. Tridem Double Drop Deck", current),
        ("48HF2X", "48 ft. Tandem Flat Deck", current),
        ("48HF3X", "48 ft. Tridem Flat Deck", current),
        ("48HF4X", "48 ft. Quad Flat Deck", current),
        ("50HF5X", "50 ft. 5 Axle Flat Deck", current),
        ("51HD3X CON", "51 ft. Tridem Drop Deck", current),
        ("53HD2X", "53 ft. Tandem Drop Deck", current),
        ("53HD2X Crane", "53 ft. Tandem Bridge Crane Drop Deck", current),
        ("53HD2X EXT", "53 ft. Highway Drop Deck Extendable", current),
        ("53HD2X EXT H", "53 ft. Highway Drop Deck Extendable", non_current),
        ("53HD2X EXT_temp1", "53 ft. Highway Drop Deck Extendable", non_current),
        ("53HD3X", "53 ft. Tridem Drop Deck", non_current),
        ("53HD3X 2018", "53 ft. Tridem Drop Deck", current),
        ("53HD3X EXT", "53 ft. Highway Drop Deck Extendable", current),
        ("53HD4X", "53 ft. Quad Drop Deck", current),
        ("53HDD2X", "53 ft. Tandem Double Drop Deck", non_current),
        ("53HDD3X", "53 ft. Tridem Double Drop Deck", current),
        ("53HF3X", "53 ft. Tridem Flat Deck", non_current),
        ("53HF3X 2018", "53 ft. Tridem Flat Deck", current),
        ("53HF3X Pioneer", "53 ft. Tridem Flat Deck - Pioneer", current),
        ("53HF3XEXT", "53 ft. Tridem Flat Deck Extendable", current),
        ("53HF4X", "53 ft. Quad Flat Deck", current),
        ("53HF4X - Super Single", "53 ft. Quad Flat Deck", non_current),
        ("53OHD3X", "53 ft. Tridem Oilfield Drop Deck", non_current),
        ("FA", "Single Axle Flip", current),
        ("Fleet Only", "", non_current)
    ],
    "Hydraulics": [
        ("25HDG2X Mini", "25 Ton Tandem Square Back Mini Deck", non_current),
        ("25HDG2X Mini NR", "25 Ton Tandem Square Back Mini Deck", non_current),
        ("25HDG2X SB", "25 Ton Tandem Mini Quad Deck", current),
        ("35HDG2X Mini", "35 Ton Tandem Square Back Mini Deck", current),
        ("35HDG2X Mini NR", "35 Ton Tandem Square Back Mini Deck", non_current),
        ("35HDG2X NR", "35 Ton Tandem 48 ft. Non RTAC", current),
        ("35HDG2X SB", "35 Ton Tandem Mini Quad Deck", current),
        ("35HDG2X48 AGULP", "35 Ton Tandem - 48 ft. Agri Ultra Low Pro HDG", current),
        ("35HDG2X53 AGC", "35 Ton Tandem 53 ft. Agri - Chopper", non_current),
        ("35HDG2X53 AGNR", "35 Ton Tandem 53 ft. Agri - Non RTAC", current),
        ("40HDG3X AG", "40 Ton Tridem  Agriculture", current),
        ("40HDG3X53 AG", "40 Ton Tridem 53 ft. Agri", current),
        ("40HDG4X SB P", "40 Ton Quad Squareback Paver", current),
        ("40HSN3X", "", current),
        ("50FA AGRI", "50 Ton Single Axle Flip Agriculture", current),
        ("50HDG3X AG", "50 Ton Tridem  Agriculture", current),
        ("51HDG3X SB", "51 Ton Tridem Square Back", current),
        ("51HDG3X SBLH", "51 Ton Tridem Square Back Light Haul", current),
        ("55FA", "55 Ton Single Axle Flip - Heavy Haul", non_current),
        ("55FA  B", "55 Ton Single Axle Flip", current),
        ("55FA LH", "55 Ton Single Axle Flip - Light Haul", current),
        ("55HDG3X", "55 ton Tridem Square Back", current),
        ("55HDG3X BT", "55 Ton Tridem Beavertail", current),
        ("55HDG3X BTHH", "55 Ton Tridem Beavertail - Heavy Haul", current),
        ("55HDG3X BTHH AG", "55 Ton Tridem Beavertail - Heavy Haul AG", current),
        ("55HDG3X E", "55 ton Tridem Square Back - Elite", current),
        ("55HDG3X H", "55 ton Tridem Square Back Heavy", current),
        ("55HDG3X HS", "55 ton Tridem Square Back Heavy Spread Axle", current),
        ("55HDG3X Q1", "55 Ton Tridem Square Back", non_current),
        ("55HDG3X SB", "55 Ton Tridem Square Back", non_current),
        ("55HDG3X SBHH", "55 Ton Tridem Square Back - Heavy Haul", current),
        ("55HDG3X SBHH AG", "55 Ton Tridem Square Back - Heavy Haul", current),
        ("55HDG3X SBLH", "55 Ton Tridem Square Back - Light Haul", current),
        ("55HDG3X SBLH PQ", "55 Ton Tridem Square Back - Light Haul PQ", non_current),
        ("55HDG3X SBPD", "55 Ton Tridem Square Back Pin Deck", current),
        ("55HDG3X US", "55 ton Tridem Square Back", current),
        ("55HDG4X SB", "55 Ton Quad Squareback", non_current),
        ("60HDG3X HB_temp1", "60 ton Tridem Square Back", non_current),
        ("60HDG4X SB", "60 Ton Quad Squareback", non_current),
        ("60HDGSB", "60 Ton Tridem Squareback", non_current),
        ("70HDG4X SB", "70 Ton Quad Squareback", non_current),
        ("DECK - Bellemar", "55 ton Drop Side Pin Deck", current),
        ("GNK - Bellemare", "55 Ton Gooseneck", current)
    ],
    "Jeep Dolly": [
        ("20JD1X HP", "20 Ton Single Axle High Profile", non_current),
        ("20JD1X LP", "20 Ton Single Axle Low Profile", current),
        ("40JD2X HG", "40 Ton Tandem Hydraulic", current),
        ("40JD2X OF", "40 Ton Tandem Oilfield", current),
        ("40JD2X WL", "40 Ton Tandem  Western Log", current),
        ("60JD3X HG", "60 Ton Tridem Hydraulic", non_current),
        ("JD2+1X", "Tridem Hydraulic", current),
        ("JD2X", "Tandem Hydraulic", current)
    ],
    "Log": [
        ("50LF4X5T NB", "50' 5 Tier Quad - NB", current),
        ("51LF4X5T NB", "51' 5 Tier Quad - NB", current),
        ("53LF4X5T NB", "53' 5 Tier Quad - NB", current),
        ("64LBT5X NL", "64' 5 Axle B-Train - NL", current)
    ],
    "Log Eastern": [
        ("25LPT2X", "25 Foot Tandem", non_current),
        ("25LPT3X", "25 Foot Tridem Pup", non_current),
        ("25LPT3X JDI", "25 ft. Logging Pup Trailer", non_current),
        ("27LBT2X NL", "27 ft. Tandem 1 Tier Pull B-Train - NL", current),
        ("28LBT2X NS", "28 ft. Tandem 3 Tier Pull B-Train - NS", current),
        ("30LBT2X ON", "30 ft. Tandem 3 Tier  Pull B-Train - Ontario", non_current),
        ("37LBT3X NL", "37 ft. Tridem 1 Tier Lead B-Train - NL", current),
        ("39LBT3X NS", "39 ft.Tridem 3 Tier Lead B-Train - NS", current),
        ("39LBT3X ON", "39 ft. Tridem 3 Tier Lead B-Train - Ontario", non_current),
        ("42LD3X NL", "42 ft. Tridem Pulp -  NL", non_current),
        ("46LD3X4T NS", "46 ft. Tridem 4 Tier Drop Frame - NS", non_current),
        ("46LD3X4T NS V2016", "46 ft. Tridem 4 Tier Drop Frame - NS", current),
        ("46LD3X4T V2016", "46 ft. Tridem 4 Tier Drop Frame", non_current),
        ("46LD3X4T V2018", "46 ft. Tridem 4 Tier Drop Frame - NS", current),
        ("46LD3X4TLW NS", "46`4 Tier Tridem - NS Lightweight", non_current),
        ("46LD4X NL", "46 ft. Quad Pulp - NL", non_current),
        ("46LD4X4T NS", "46 ft. Quad 4 Tier Drop Frame - NS", non_current),
        ("46LF3X4T NL", "46 ft.Tridem 4 Tier Taper Frame -  NL", non_current),
        ("46LF3X4T NS", "46 ft. Tridem 4 Tier Taper Frame -  NS", non_current),
        ("46LF3X4T NS V2017", "46 ft. Tridem 4 Tier Taper Frame -  NS", non_current),
        ("46LF3X4T V2018", "46 ft. Tridem 4 Tier Taper Frame", current),
        ("46LF4X NL", "46 ft. Quad Pulp Taper Frame - NL", current),
        ("48LD3X5T V2018", "48 ft. Tri 5 Tier Drop Frame", current),
        ("48LD4X4T NB V2017", "48 ft. Quad 4 Tier Drop Frame - NB", non_current),
        ("48LD4X4T V2018", "48 ft. Quad 4 Tier Drop Frame", non_current),
        ("48LD4X5T NB V2016", "48 ft. Quad 5 Tier Drop Frame - NB", current),
        ("48LD4X5T ON", "48 ft. Quad 5 Tier Drop Frame - ON", non_current),
        ("48LD4X5T V2018", "48 ft. Quad 5 Tier Drop Frame", current),
        ("48LF3X NL", "48 ft. Tridem Pulp Taper Frame - NL", non_current),
        ("48LF3X5T NB", "48 ft. Tridem 5  Tier Taper Frame - NB", current),
        ("48LF3X5T NB V2016", "48 ft. Tridem 5  Tier Taper Frame - NB", non_current),
        ("48LF3X5T NB V2018", "48 ft. Tridem 5  Tier Taper Frame - NB", non_current),
        ("48LF3X5T V2018", "48 ft. Tridem 5  Tier Taper Frame", current),
        ("48LF4X NL", "48 ft. Quad Pulp Taper Frame - NL", non_current),
        ("48LF4X5T NB", "48 ft. Quad 5 Tier Taper Frame - NB", current),
        ("48LF4X5T NB V2016", "48 ft. Quad 5 Tier Taper Frame - NB", current),
        ("48LF4X5T V2018", "48 ft. Quad 5 Tier Taper Frame - NB", non_current),
        ("51LD4X5T NB V2016", "51 ft. Quad  5 Tier Drop Frame - NB", current),
        ("51LD4X5T NS/NB", "51' 5 Tier Quad - NS/NB", current),
        ("51LD4X5T ON", "51 ft. Quad 5 Tier Drop Frame - ON", current),
        ("51LD4X5T V2018", "51 ft. Quad  5 Tier Drop Frame - NB", current),
        ("51LD5X5T ON", "51 ft.  5 Axle 5 Tier Drop Frame  - ON", non_current),
        ("51LD5X5T ON V2017", "51 ft. Five Axle 5 Tier Drop Frame - ON", non_current),
        ("51LF3X5T NB", "51 ft. Tridem 5  Tier Taper Frame - NB", current),
        ("51LF3X5T NB V2016", "51 ft. Tridem 5  Tier Taper Frame - NB", non_current),
        ("51LF4X5T NB TRI V2016", "51 ft. Quad 5 Tier Taper Frame , Tri drive capable- NB", current),
        ("51LF4X5T NB V2013", "51' 5 Tier Quad - NB", current),
        ("51LF4X5T NB V2016", "51 ft. Quad 5 Tier Taper Frame - NB", current),
        ("51LF4X5T V2018", "51 ft. Quad 5 Tier Taper Frame", current),
        ("52LD4X5T", "52 ft. Quad 5 Tier Drop Frame", current),
        ("52LF4X5T", "52 ft. Quad 5 Tier Taper Frame", current),
        ("53LD3X5T JDIHD", "53 ft. 5 Tier Tridem Drop Frame Heavy Duty - JDI", non_current)
    ],
    "Log US": [
        ("42LD3X4T USAE", "42 ft. Tridem 4 Tier Drop Frame - USAE", non_current),
        ("46LD2X4T US", "46 ft. Tandem  4 Tier - US", non_current),
        ("46LD3X2T US", "46 ft. Tridem 2 Tier - US", non_current),
        ("46LD3X4T US", "46 ft. Tridem 4 Tier  -  US", non_current),
        ("46LD3X4T USAE", "46 ft. Tridem 4 Tier Drop Frame - USAE", non_current),
        ("46LD3X5T HALE", "46 ft. Tridem  5 Tier Drop Frame", current),
        ("46LF3X MN", "46 ft. Tridem Pulp Taper Frame -  MN", non_current),
        ("46LF3X4T USAE", "46 ft. Tridem 4 Tier Taper Frame - USAE", non_current),
        ("48LD3X5T US", "48 ft. Tridem 5 Tier Drop Frame -  US", non_current),
        ("48LD3X5T USAE", "48 ft. Tridem  5 Tier Drop Frame - USAE", non_current),
        ("48LF3X5T USAE", "48 ft. Tridem 5 Tier Taper Frame- USAE", non_current),
        ("51LF4X3T US", "51 ft. Quad 3 Tier Taper Frame - US", non_current)
    ]
}

current_models = []
non_current_models = []

for clazz, lst in models.items():
    for model in lst:
        model_abbr, model_name, status = model
        if status == current:
            current_models.append(model)
        elif status == non_current:
            non_current_models.append(model)
        else:
            raise ValueError("UNKNOWN status classification")

print("{n} total classes".format(n=len(models)))
print("{n} total models".format(n=len(current_models) + len(non_current_models)))
print("{n} current models".format(n=len(current_models)))
print("{n} non-current models".format(n=len(non_current_models)))