/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Quote#]
      ,[Quote Date]
      ,[Order Date]
      ,[WO#]
      ,[Sales Order#]
      ,[Model No]
      ,[Width]
      ,[Spread]
      ,[DealerID]
      ,[Sale PersonID]
      ,[Price]
      ,[Prom Drawing]
      ,[Special Instructions]
      ,[Date Declined]
      ,[Decline/Rejected]
      ,[Serial Number]
      ,[Available Date]
      ,[Delivery Date]
      ,[Requested Delivery Date]
      ,[Finish Date]
      ,[Purchase Order]
      ,[PO Date]
      ,[PayID]
      ,[Volume Discount]
      ,[Program Discount]
      ,[Discount1_Name]
      ,[Discount1_Type]
      ,[Discount1]
      ,[Discount2_Name]
      ,[Discount2_Type]
      ,[Discount2]
      ,[Discount3_Name]
      ,[Discount3_Type]
      ,[Discount3]
      ,[Est Pro Date]
      ,[Notes]
      ,[EngNotes]
      ,[CarrierID]
      ,[CustID]
      ,[US Sale]
      ,[Shipped Date]
      ,[GL Override Date]
      ,[FE Rate]
      ,[PDD]
      ,[Deck Length]
      ,[Invoice #]
      ,[Date Registered]
      ,[Date In Service]
      ,[Invoice Date]
      ,[Date Requested]
      ,[GVWR]
      ,[Tare]
      ,[Selection]
      ,[Warranty]
      ,[BWSPaid]
      ,[BWSPaidDate]
      ,[CommPaid]
      ,[CommPaidDate]
      ,[ts_timestamp]
      ,[ModifiedBy]
      ,[Lead Date]
      ,[Lead Source]
      ,[LeadID]
      ,[DealerBranchID]
      ,[DealerSalesPersonID]
      ,[DataEntryCheck]
      ,[DataEntryUser]
      ,[FinishedGoodsDealerLocID]
      ,[WO Reviewed]
      ,[WO Review Date]
      ,[Follow Up Date]
      ,[MSOIsDifferent]
      ,[MSOLocID]
      ,[EstInvDateOverride]
      ,[Estimated Invoice Date]
      ,[AdditionalPricingInfo]
      ,[Slot#]
      ,[TempModel?]
      ,[HighRiskUnit]
      ,[EngNotes V2]
      ,[CompanyID]
      ,[Customer WO#]
      ,[Step 2 Slot#]
      ,[PriceSecured]
      ,[DateSecured]
      ,[SecuredBy]
      ,[InternalSalesComment]
      ,[InternalSalesCommentDate]
      ,[InternalSalesCommenter]
      ,[DiscountID]
      ,[DiscountSetDate]
      ,[DiscountSetBy]
      ,[ProductID]
  FROM [BWSdb].[dbo].[Orders]
  WHERE
	[Order Date] >= '2022-11-16'
  ORDER BY
	[Order Date] DESC