USE [BWSdb]
GO

/****** Object:  Table [dbo].[BWSWOBOM_6867]    Script Date: 2022-01-21 9:52:02 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BWSWOBOM_6867](
	[IDSGWO267] [int] IDENTITY(1,1) NOT NULL,
	[Component] [varchar](30) NULL,
	[Qty] [decimal](18, 6) NULL,
	[SeqNo] [varchar](6) NULL,
	[Operation] [decimal](5, 0) NULL,
 CONSTRAINT [PK_BWSWOBOM_6967] PRIMARY KEY CLUSTERED 
(
	[IDSGWO267] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BWSWOBOM_6867] ADD  CONSTRAINT [DF_BWSWOBOM_6967_Qty]  DEFAULT ((0)) FOR [Qty]
GO


